Repository firebase/firebase-cpp-sdk, pull requests merged in 2021-05, with the labels that each got.

#295 Work on deflaking Storage integration test on mobile, particularly the large file download/pause/resume.
  installations/integration_test/src/integration_test.cc
  messaging/integration_test/src/integration_test.cc
  scripts/gha/summarize_test_results.py
  storage/integration_test/src/integration_test.cc
  testing/test_framework/src/firebase_test_framework.cc
  testing/test_framework/src/firebase_test_framework.h
Labels: cla: yes, tests: succeeded

#407 Remove STLPort from C++ packaging workflow.
  .github/workflows/cpp-packaging.yml
Labels: cla: yes

#391 Made parameters in QueryParams optional.
  database/src/common/query_spec.h
  database/src/desktop/persistence/flatbuffer_conversions.cc
  database/src/desktop/query_desktop.cc
  database/src/desktop/util_desktop.cc
  database/tests/desktop/core/indexed_variant_test.cc
  database/tests/desktop/core/sync_point_spec_test.cc
Labels: cla: yes, tests: succeeded

#404 Allow running integration tests on an external PR
  .github/workflows/integration_tests.yml
  scripts/gha/summarize_test_results.py
Labels: cla: yes, tests: succeeded

#403 Re-enable FirestoreIntegrationTest.AuthWorks on MacOS
  firestore/integration_test_internal/src/firestore_test.cc
Labels: api: firestore, cla: yes, tests: succeeded

#405 Re-enable FirestoreIntegrationTest.FirestoreCanBeDeletedFromTransaction
  firestore/integration_test_internal/src/firestore_test.cc
Labels: api: firestore, cla: yes, tests: succeeded

#398 Remove support for STLPort and deprecate support for gnustl on Android
  app/src/include/firebase/app.h
  build_scripts/android/build.sh
  build_scripts/android/package.sh
  build_scripts/desktop/get_variant.sh
  release_build_files/readme.md
Labels: cla: yes

#410 Add Firestore source tests
  firestore/integration_test_internal/CMakeLists.txt
  firestore/integration_test_internal/src/firestore_integration_test.cc
  firestore/integration_test_internal/src/firestore_integration_test.h
  firestore/integration_test_internal/src/source_test.cc
Labels: cla: yes

#411 Minor fixes to Firestore Source Tests.
  firestore/integration_test_internal/src/source_test.cc
Labels: cla: yes

#413 Remove redundant flatbuffer dependencies.
  database/CMakeLists.txt
  remote_config/CMakeLists.txt
Labels: cla: yes

#408 Removed SetCurrentScreen method from Analytics
  analytics/integration_test/src/integration_test.cc
  analytics/src/analytics_android.cc
  analytics/src/analytics_ios.mm
  analytics/src/analytics_stub.cc
  analytics/src/include/firebase/analytics.h
  analytics/src_ios/fake/FIRAnalytics.h
  analytics/src_ios/fake/FIRAnalytics.mm
  analytics/src_java/fake/com/google/firebase/analytics/FirebaseAnalytics.java
  analytics/tests/analytics_test.cc
  release_build_files/readme.md
Labels: cla: yes, tests: succeeded

#412 Remove the STLPort mention from the docs and mark gnustl as deprecated
  release_build_files/readme.md
Labels: cla: yes

#417 Disable Firestore Source Tests
  firestore/integration_test_internal/src/source_test.cc
Labels: cla: yes, tests: succeeded

#415 Create build matrices & test matrices for integration test workflow
  .github/workflows/integration_tests.yml
  scripts/gha/build_testapps.py
  scripts/gha/desktop_tester.py
  scripts/gha/integration_testing/gameloop/gameloop.xcodeproj/project.pbxproj
  scripts/gha/integration_testing/gameloop_android/app/src/main/java/com/google/firebase/gameloop/MainActivity.kt
  scripts/gha/integration_testing/gameloop_android/app/src/main/res/xml/file_paths.xml
  scripts/gha/integration_testing/test_validation.py
  scripts/gha/integration_testing/xcodebuild.py
  scripts/gha/print_matrix_configuration.py
  scripts/gha/restore_secrets.py
  scripts/gha/summarize_test_results.py
  scripts/gha/test_lab.py
  scripts/gha/test_simulator.py
Labels: cla: yes, tests: succeeded

#421 Downgraded minSdkVersion to 14
  messaging/src/android/java/LibraryManifest.xml
Labels: cla: yes, tests: succeeded

#430 Reduce the minSdkVersion of the messaging test to match the others
  messaging/integration_test/build.gradle
Labels: cla: yes, tests: succeeded

#432 Scheduled integration test workflow disable using expand matrix
  .github/workflows/cpp-packaging.yml
  .github/workflows/integration_tests.yml
Labels: cla: yes, tests: succeeded

#431 Fix Firestore's snapshot_metadata_android_test
  firestore/integration_test_internal/src/android/snapshot_metadata_android_test.cc
Labels: api: firestore, cla: yes, tests: succeeded

#425 Provide an easy way to edit the googletest arguments in integration tests
  testing/test_framework/src/firebase_test_framework.cc
Labels: cla: yes, tests: succeeded

#429 Fix GetPlatformAppByName() crash on KitKat when the app was not found
  app/src/app_android.cc
  release_build_files/readme.md
Labels: cla: yes

#420 Feature/python scripts update ios android dependencies
  release_build_files/readme.md
  scripts/update_ios_android_dependencies.py
Labels: cla: yes

#428 Feature/fix broken admob android
  Android/firebase_dependencies.gradle
  admob/admob_resources/AndroidManifest.xml
  admob/admob_resources/build.gradle
  admob/integration_test/build.gradle
  admob/integration_test/src/integration_test.cc
  admob/src/android/ad_request_converter.cc
  admob/src/android/ad_request_converter.h
  admob/src/android/admob_android.cc
  admob/src/android/admob_android.h
  admob/src/include/firebase/admob.h
  admob/src/include/firebase/admob/types.h
  admob/src_java/com/google/firebase/admob/internal/cpp/AdRequestHelper.java
  admob/src_java/com/google/firebase/admob/internal/cpp/BannerViewHelper.java
Labels: cla: yes

#394 Implement Firestore Bundles
  .gitignore
  app/CMakeLists.txt
  firestore/.clang-format
  firestore/CMakeLists.txt
  firestore/firestore_resources/build.gradle
  firestore/integration_test_internal/CMakeLists.txt
  firestore/integration_test_internal/src/bundle_test.cc
  firestore/integration_test_internal/src/firestore_integration_test.cc
  firestore/integration_test_internal/src/firestore_integration_test.h
  firestore/integration_test_internal/src/firestore_test.cc
  firestore/integration_test_internal/src/transaction_test.cc
  firestore/integration_test_internal/src/util/bundle_builder.cc
  firestore/integration_test_internal/src/util/bundle_builder.h
  firestore/integration_test_internal/src/util/event_accumulator.h
  firestore/src/android/event_listener_android.cc
  firestore/src/android/event_listener_android.h
  firestore/src/android/firestore_android.cc
  firestore/src/android/firestore_android.h
  firestore/src/android/load_bundle_task_android.cc
  firestore/src/android/load_bundle_task_android.h
  firestore/src/android/load_bundle_task_progress_android.cc
  firestore/src/android/load_bundle_task_progress_android.h
  firestore/src/common/firestore.cc
  firestore/src/common/load_bundle_task_progress.cc
  firestore/src/common/type_mapping.h
  firestore/src/include/firebase/firestore.h
  firestore/src/include/firebase/firestore/load_bundle_task_progress.h
  firestore/src/ios/firestore_ios.cc
  firestore/src/ios/firestore_ios.h
  firestore/src_java/com/google/firebase/firestore/internal/cpp/FirestoreTasks.java
  firestore/src_java/com/google/firebase/firestore/internal/cpp/LoadBundleProgressListener.java
  firestore/src_java/com/google/firebase/firestore/internal/cpp/SilentRejectionSingleThreadExecutor.java
Labels: cla: yes, tests: succeeded

#435 Update gitingore for integration test
  .gitignore
  scripts/gha/build_testapps.py
Labels: cla: yes, tests: succeeded

#437 More accurate error reporting when an Auth error occurs.
  firestore/src/ios/credentials_provider_desktop.cc
Labels: cla: yes, tests: succeeded

#438 Fix the API client header that is sent in the user agent.
  app/src/app_common.cc
Labels: cla: yes

#440 Disable more bundles tests that fail in Windows CI
  firestore/integration_test_internal/src/bundle_test.cc
Labels: api: firestore, cla: yes, tests: succeeded
