Repository firebase/firebase-cpp-sdk, pull requests merged in 2021-06, with the labels that each got.

#443 Feature/tvos support
  CMakeLists.txt
  admob/src/common/banner_view_internal.cc
  admob/src/common/interstitial_ad_internal.cc
  admob/src/common/native_express_ad_view_internal.cc
  admob/src/common/rewarded_video_internal.cc
  admob/src/include/firebase/admob/types.h
  app/CMakeLists.txt
  app/src/app_common.cc
  app/src/include/firebase/app.h
  app/src/include/firebase/internal/platform.h
  app/src/locale.cc
  app/src/semaphore.h
  app/src/time.h
  app/tests/app_test.cc
  auth/src/ios/credential_ios.mm
  auth/src/ios/user_ios.mm
  auth/tests/auth_test.cc
  auth/tests/user_test.cc
  build_scripts/tvos/Info.plist
  build_scripts/tvos/build.sh
  build_scripts/tvos/install_prereqs.sh
  build_scripts/tvos/package.sh
  cmake/external_rules.cmake
  cmake/toolchains/apple.toolchain.cmake
  database/src/common/data_snapshot.cc
  database/src/common/database.cc
  database/src/common/database_reference.cc
  database/src/common/disconnection.cc
  database/src/common/mutable_data.cc
  database/src/common/query.cc
  functions/src/common/callable_reference.cc
  functions/src/common/functions.cc
  installations/src/installations_internal.h
  messaging/src/ios/messaging.mm
  remote_config/src/remote_config.cc
  storage/src/common/controller.cc
  storage/src/common/listener.cc
  storage/src/common/metadata.cc
  storage/src/common/storage.cc
  storage/src/common/storage_reference.cc
Labels: cla: yes

#444 Fix BoringSSL Windows CI targets failing with windows-latest
  .github/workflows/cpp-packaging.yml
  .github/workflows/integration_tests.yml
  scripts/gha/print_matrix_configuration.py
Labels: cla: yes, tests: succeeded

#436 Converted RegistrationIntentService to a JobIntentService
  messaging/AndroidManifest.xml
  messaging/src/android/java/com/google/firebase/messaging/JobIds.java
  messaging/src/android/java/com/google/firebase/messaging/cpp/RegistrationIntentService.java
Labels: cla: yes, tests: succeeded

#426 Fix Firestore transaction_extra_test.cc on iOS and re-enable the tests
  firestore/integration_test_internal/src/transaction_extra_test.cc
  testing/sample_framework/src/ios/ios_app_framework.mm
Labels: api: firestore, cla: yes, tests: succeeded

#447 Feature/tvos support integration tests
  app/src/include/firebase/internal/platform.h
  remote_config/integration_test/Podfile
  remote_config/integration_test/integration_test.xcodeproj/project.pbxproj
  remote_config/integration_test/integration_test.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  remote_config/integration_test/integration_test.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  remote_config/integration_test/integration_test.xcodeproj/project.xcworkspace/xcuserdata/vimanyujain.xcuserdatad/UserInterfaceState.xcuserstate
  remote_config/integration_test/integration_test.xcodeproj/xcuserdata/vimanyujain.xcuserdatad/xcschemes/xcschememanagement.plist
  remote_config/integration_test/integration_test_tvos/Assets.xcassets/AccentColor.colorset/Contents.json
  remote_config/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Back.imagestacklayer/Content.imageset/Contents.json
  remote_config/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Back.imagestacklayer/Contents.json
  remote_config/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Contents.json
  remote_config/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Front.imagestacklayer/Content.imageset/Contents.json
  remote_config/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Front.imagestacklayer/Contents.json
  remote_config/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Middle.imagestacklayer/Content.imageset/Contents.json
  remote_config/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Middle.imagestacklayer/Contents.json
  remote_config/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Back.imagestacklayer/Content.imageset/Contents.json
  remote_config/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Back.imagestacklayer/Contents.json
  remote_config/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Contents.json
  remote_config/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Front.imagestacklayer/Content.imageset/Contents.json
  remote_config/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Front.imagestacklayer/Contents.json
  remote_config/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Middle.imagestacklayer/Content.imageset/Contents.json
  remote_config/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Middle.imagestacklayer/Contents.json
  remote_config/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/Contents.json
  remote_config/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/Top Shelf Image Wide.imageset/Contents.json
  remote_config/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/Top Shelf Image.imageset/Contents.json
  remote_config/integration_test/integration_test_tvos/Assets.xcassets/Contents.json
  remote_config/integration_test/integration_test_tvos/Base.lproj/LaunchScreen.storyboard
  remote_config/integration_test/integration_test_tvos/Base.lproj/Main.storyboard
  remote_config/integration_test/integration_test_tvos/Info.plist
  testing/sample_framework/src/ios/ios_app_framework.mm
  testing/test_framework/src/ios/ios_firebase_test_framework.mm
Labels: cla: yes

#448 Auth Integration Test Project for tvOS
  auth/integration_test/Podfile
  auth/integration_test/integration_test.xcodeproj/project.pbxproj
  auth/integration_test/integration_test.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  auth/integration_test/integration_test.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  auth/integration_test/integration_test_tvos/Assets.xcassets/AccentColor.colorset/Contents.json
  auth/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Back.imagestacklayer/Content.imageset/Contents.json
  auth/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Back.imagestacklayer/Contents.json
  auth/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Contents.json
  auth/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Front.imagestacklayer/Content.imageset/Contents.json
  auth/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Front.imagestacklayer/Contents.json
  auth/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Middle.imagestacklayer/Content.imageset/Contents.json
  auth/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Middle.imagestacklayer/Contents.json
  auth/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Back.imagestacklayer/Content.imageset/Contents.json
  auth/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Back.imagestacklayer/Contents.json
  auth/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Contents.json
  auth/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Front.imagestacklayer/Content.imageset/Contents.json
  auth/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Front.imagestacklayer/Contents.json
  auth/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Middle.imagestacklayer/Content.imageset/Contents.json
  auth/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Middle.imagestacklayer/Contents.json
  auth/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/Contents.json
  auth/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/Top Shelf Image Wide.imageset/Contents.json
  auth/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/Top Shelf Image.imageset/Contents.json
  auth/integration_test/integration_test_tvos/Assets.xcassets/Contents.json
  auth/integration_test/integration_test_tvos/Base.lproj/LaunchScreen.storyboard
  auth/integration_test/integration_test_tvos/Base.lproj/Main.storyboard
  auth/integration_test/integration_test_tvos/Info.plist
  auth/integration_test/src/integration_test.cc
  testing/test_framework/src/firebase_test_framework.h
Labels: cla: yes

#433 Update iOS and Android dependencies to Firebase 8.0.0, except for AdMob.
  .github/workflows/cpp-packaging.yml
  Android/firebase_dependencies.gradle
  admob/admob_resources/build.gradle
  admob/integration_test/Podfile
  admob/integration_test/build.gradle
  admob/integration_test/integration_test.xcodeproj/project.pbxproj
  analytics/integration_test/Podfile
  analytics/integration_test/build.gradle
  app/app_resources/build.gradle
  app/google_api_resources/build.gradle
  app/integration_test/Podfile
  app/integration_test/build.gradle
  app/invites_resources/build.gradle
  auth/auth_resources/build.gradle
  auth/integration_test/Podfile
  auth/integration_test/build.gradle
  database/database_resources/build.gradle
  database/integration_test/Podfile
  database/integration_test/build.gradle
  dynamic_links/integration_test/Podfile
  dynamic_links/integration_test/build.gradle
  firestore/firestore_resources/build.gradle
  firestore/integration_test/Podfile
  firestore/integration_test/build.gradle
  firestore/integration_test_internal/build.gradle
  functions/integration_test/Podfile
  functions/integration_test/build.gradle
  installations/integration_test/Podfile
  installations/integration_test/build.gradle
  ios_pod/Podfile
  messaging/integration_test/Podfile
  messaging/integration_test/build.gradle
  messaging/messaging_java/build.gradle
  messaging/src/android/java/com/google/firebase/messaging/cpp/RegistrationIntentService.java
  release_build_files/Android/firebase_dependencies.gradle
  release_build_files/readme.md
  remote_config/integration_test/Podfile
  remote_config/integration_test/build.gradle
  scripts/gha/print_matrix_configuration.py
  scripts/gha/summarize_test_results.py
  storage/integration_test/Podfile
  storage/integration_test/build.gradle
  storage/storage_resources/build.gradle
Labels: cla: yes, tests: succeeded

#419 Update build & test summary report
  .github/workflows/integration_tests.yml
  scripts/gha/build_testapps.py
  scripts/gha/integration_testing/gameloop_ios/gameloop.xcodeproj/project.pbxproj
  scripts/gha/integration_testing/gameloop_ios/gameloop/AppDelegate.swift
  scripts/gha/integration_testing/gameloop_ios/gameloop/Assets.xcassets/AccentColor.colorset/Contents.json
  scripts/gha/integration_testing/gameloop_ios/gameloop/Assets.xcassets/AppIcon.appiconset/Contents.json
  scripts/gha/integration_testing/gameloop_ios/gameloop/Assets.xcassets/Contents.json
  scripts/gha/integration_testing/gameloop_ios/gameloop/Base.lproj/LaunchScreen.storyboard
  scripts/gha/integration_testing/gameloop_ios/gameloop/Base.lproj/Main.storyboard
  scripts/gha/integration_testing/gameloop_ios/gameloop/Constants.swift
  scripts/gha/integration_testing/gameloop_ios/gameloop/Info.plist
  scripts/gha/integration_testing/gameloop_ios/gameloop/ViewController.swift
  scripts/gha/integration_testing/gameloop_ios/gameloopUITests/Info.plist
  scripts/gha/integration_testing/gameloop_ios/gameloopUITests/gameloopUITests.swift
  scripts/gha/integration_testing/test_validation.py
  scripts/gha/print_matrix_configuration.py
  scripts/gha/summarize_test_results.py
  scripts/gha/test_lab.py
  scripts/gha/test_simulator.py
Labels: cla: yes

#451 Fix GHA CI Windows Path Limits
  .github/workflows/cpp-packaging.yml
Labels: cla: yes, tests: succeeded

#452 Temporarily remove `NamedQuery` from the public API
  firestore/integration_test_internal/src/bundle_test.cc
  firestore/src/common/firestore.cc
  firestore/src/include/firebase/firestore.h
  firestore/src/main/firestore_main.cc
  firestore/src/main/firestore_main.h
Labels: cla: yes

#454 Git Patch BoringSSL to disable Windows build warnings/errors
  .github/workflows/cpp-packaging.yml
  .github/workflows/integration_tests.yml
  CMakeLists.txt
  cmake/external/boringssl.cmake
  scripts/gha/print_matrix_configuration.py
  scripts/git/patches/boringssl/0001-disable-C4255-converting-empty-params-to-void.patch
Labels: cla: yes

#462 format_code.py changed to print the diff when not formatting files inline
  scripts/format_code.py
Labels: cla: yes

#461 Fix FTAViewController incorrectly calling openURL off the main thread.
  testing/sample_framework/src/ios/ios_app_framework.mm
Labels: cla: yes, tests: succeeded

#465 Add changelog entry for firestore::LoadBundle()
  release_build_files/readme.md
Labels: cla: yes

#460 Increase the visibility of the static methods in FirebaseTest
  testing/test_framework/src/firebase_test_framework.h
Labels: cla: yes

#469 Update to Firebase iOS SDK 8.1.1 and latest Android
  Android/firebase_dependencies.gradle
  admob/integration_test/Podfile
  analytics/integration_test/Podfile
  app/integration_test/Podfile
  app/invites_resources/build.gradle
  auth/integration_test/Podfile
  database/integration_test/Podfile
  dynamic_links/integration_test/Podfile
  firestore/firestore_resources/build.gradle
  firestore/integration_test/Podfile
  functions/integration_test/Podfile
  installations/integration_test/Podfile
  ios_pod/Podfile
  messaging/integration_test/Podfile
  release_build_files/Android/firebase_dependencies.gradle
  release_build_files/readme.md
  remote_config/integration_test/Podfile
  storage/integration_test/Podfile
Labels: cla: yes, tests: succeeded

#468 Prevent Windows GHA CI disk exhausation
  .github/workflows/integration_tests.yml
Labels: cla: yes, tests: succeeded

#475 Database Integration tests on tvOS
  database/integration_test/Podfile
  database/integration_test/integration_test.xcodeproj/project.pbxproj
  database/integration_test/integration_test.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  database/integration_test/integration_test.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  database/integration_test/integration_test_tvos/Assets.xcassets/AccentColor.colorset/Contents.json
  database/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Back.imagestacklayer/Content.imageset/Contents.json
  database/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Back.imagestacklayer/Contents.json
  database/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Contents.json
  database/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Front.imagestacklayer/Content.imageset/Contents.json
  database/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Front.imagestacklayer/Contents.json
  database/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Middle.imagestacklayer/Content.imageset/Contents.json
  database/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Middle.imagestacklayer/Contents.json
  database/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Back.imagestacklayer/Content.imageset/Contents.json
  database/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Back.imagestacklayer/Contents.json
  database/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Contents.json
  database/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Front.imagestacklayer/Content.imageset/Contents.json
  database/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Front.imagestacklayer/Contents.json
  database/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Middle.imagestacklayer/Content.imageset/Contents.json
  database/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Middle.imagestacklayer/Contents.json
  database/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/Contents.json
  database/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/Top Shelf Image Wide.imageset/Contents.json
  database/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/Top Shelf Image.imageset/Contents.json
  database/integration_test/integration_test_tvos/Assets.xcassets/Contents.json
  database/integration_test/integration_test_tvos/Base.lproj/LaunchScreen.storyboard
  database/integration_test/integration_test_tvos/Base.lproj/Main.storyboard
  database/integration_test/integration_test_tvos/Info.plist
Labels: cla: yes

#459 Test Result Report Notification
  .github/workflows/integration_tests.yml
  scripts/gha/build_testapps.py
  scripts/gha/github.py
  scripts/gha/it_workflow.py
  scripts/gha/requirements.txt
  scripts/gha/summarize_test_results.py
Labels: cla: yes, tests: succeeded

#477 Format Firestore source code with clang-format
  firestore/.clang-format
  firestore/src/android/blob_android.cc
  firestore/src/android/blob_android.h
  firestore/src/android/converter_android.h
  firestore/src/android/document_reference_android.cc
  firestore/src/android/exception_android.cc
  firestore/src/android/exception_android.h
  firestore/src/android/field_value_android.cc
  firestore/src/android/firestore_android.h
  firestore/src/android/lambda_event_listener.h
  firestore/src/android/lambda_transaction_function.h
  firestore/src/android/listener_registration_android.cc
  firestore/src/android/load_bundle_task_progress_android.cc
  firestore/src/android/load_bundle_task_progress_android.h
  firestore/src/android/promise_android.h
  firestore/src/android/promise_factory_android.h
  firestore/src/android/query_android.cc
  firestore/src/android/query_android.h
  firestore/src/android/transaction_android.cc
  firestore/src/android/transaction_android.h
  firestore/src/android/write_batch_android.h
  firestore/src/common/cleanup.h
  firestore/src/common/exception_common.cc
  firestore/src/common/exception_common.h
  firestore/src/common/firestore.cc
  firestore/src/common/hard_assert_common.cc
  firestore/src/common/hard_assert_common.h
  firestore/src/common/load_bundle_task_progress.cc
  firestore/src/common/transaction.cc
  firestore/src/include/firebase/firestore/event_listener.h
  firestore/src/include/firebase/firestore/load_bundle_task_progress.h
  firestore/src/include/firebase/firestore/transaction.h
  firestore/src/jni/env.cc
  firestore/src/jni/env.h
  firestore/src/jni/loader.cc
  firestore/src/jni/loader.h
  firestore/src/jni/string.cc
  firestore/src/jni/string.h
  firestore/src/main/converter_main.h
  firestore/src/main/credentials_provider_desktop.cc
  firestore/src/main/firestore_main.cc
  firestore/src/main/firestore_main.h
  firestore/src/main/promise_main.h
  firestore/src/main/query_main.cc
  firestore/src/main/query_main.h
  firestore/src/main/transaction_main.cc
  firestore/src/main/transaction_main.h
  firestore/src/main/user_data_converter_main.cc
  firestore/src/main/write_batch_main.h
  firestore/src/stub/transaction_stub.h
  firestore/src/stub/write_batch_stub.h
Labels: api: firestore, cla: yes

#476 Format Firestore integration test code with clang-format
  firestore/integration_test_internal/src/android/firestore_integration_test_android.h
  firestore/integration_test_internal/src/android/promise_android_test.cc
  firestore/integration_test_internal/src/firestore_integration_test.cc
  firestore/integration_test_internal/src/firestore_integration_test.h
  firestore/integration_test_internal/src/firestore_test.cc
  firestore/integration_test_internal/src/transaction_test.cc
  firestore/integration_test_internal/src/util/event_accumulator.h
  firestore/integration_test_internal/src/util/future_test_util.cc
  firestore/integration_test_internal/src/validation_test.cc
Labels: api: firestore, cla: yes

#473 [RemoteConfig] Fix the fetch interval bug
  remote_config/integration_test/src/integration_test.cc
  remote_config/src/desktop/remote_config_desktop.cc
  remote_config/src/include/firebase/remote_config.h
  remote_config/src/remote_config.cc
Labels: cla: yes

#472 Firestore integration tests on tvos
  firestore/integration_test/Podfile
  firestore/integration_test/integration_test.xcodeproj/project.pbxproj
  firestore/integration_test/integration_test.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  firestore/integration_test/integration_test.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  firestore/integration_test/integration_test.xcworkspace/contents.xcworkspacedata
  firestore/integration_test/integration_test.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  firestore/integration_test/integration_test_tvos/Assets.xcassets/AccentColor.colorset/Contents.json
  firestore/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Back.imagestacklayer/Content.imageset/Contents.json
  firestore/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Back.imagestacklayer/Contents.json
  firestore/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Contents.json
  firestore/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Front.imagestacklayer/Content.imageset/Contents.json
  firestore/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Front.imagestacklayer/Contents.json
  firestore/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Middle.imagestacklayer/Content.imageset/Contents.json
  firestore/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Middle.imagestacklayer/Contents.json
  firestore/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Back.imagestacklayer/Content.imageset/Contents.json
  firestore/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Back.imagestacklayer/Contents.json
  firestore/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Contents.json
  firestore/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Front.imagestacklayer/Content.imageset/Contents.json
  firestore/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Front.imagestacklayer/Contents.json
  firestore/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Middle.imagestacklayer/Content.imageset/Contents.json
  firestore/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Middle.imagestacklayer/Contents.json
  firestore/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/Contents.json
  firestore/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/Top Shelf Image Wide.imageset/Contents.json
  firestore/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/Top Shelf Image.imageset/Contents.json
  firestore/integration_test/integration_test_tvos/Assets.xcassets/Contents.json
  firestore/integration_test/integration_test_tvos/Base.lproj/LaunchScreen.storyboard
  firestore/integration_test/integration_test_tvos/Base.lproj/Main.storyboard
  firestore/integration_test/integration_test_tvos/Info.plist
Labels: cla: yes

#471 Feature/tvos support integration tests functions
  functions/integration_test/Podfile
  functions/integration_test/integration_test.xcodeproj/project.pbxproj
  functions/integration_test/integration_test.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  functions/integration_test/integration_test.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  functions/integration_test/integration_test.xcworkspace/contents.xcworkspacedata
  functions/integration_test/integration_test.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  functions/integration_test/integration_test_tvos/Assets.xcassets/AccentColor.colorset/Contents.json
  functions/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Back.imagestacklayer/Content.imageset/Contents.json
  functions/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Back.imagestacklayer/Contents.json
  functions/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Contents.json
  functions/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Front.imagestacklayer/Content.imageset/Contents.json
  functions/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Front.imagestacklayer/Contents.json
  functions/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Middle.imagestacklayer/Content.imageset/Contents.json
  functions/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Middle.imagestacklayer/Contents.json
  functions/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Back.imagestacklayer/Content.imageset/Contents.json
  functions/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Back.imagestacklayer/Contents.json
  functions/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Contents.json
  functions/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Front.imagestacklayer/Content.imageset/Contents.json
  functions/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Front.imagestacklayer/Contents.json
  functions/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Middle.imagestacklayer/Content.imageset/Contents.json
  functions/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Middle.imagestacklayer/Contents.json
  functions/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/Contents.json
  functions/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/Top Shelf Image Wide.imageset/Contents.json
  functions/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/Top Shelf Image.imageset/Contents.json
  functions/integration_test/integration_test_tvos/Assets.xcassets/Contents.json
  functions/integration_test/integration_test_tvos/Base.lproj/LaunchScreen.storyboard
  functions/integration_test/integration_test_tvos/Base.lproj/Main.storyboard
  functions/integration_test/integration_test_tvos/Info.plist
Labels: cla: yes, tests: succeeded

#470 Feature/tvos support integration tests storage
  storage/integration_test/Podfile
  storage/integration_test/integration_test.xcodeproj/project.pbxproj
  storage/integration_test/integration_test.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  storage/integration_test/integration_test.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  storage/integration_test/integration_test.xcworkspace/contents.xcworkspacedata
  storage/integration_test/integration_test.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  storage/integration_test/integration_test_tvos/Assets.xcassets/AccentColor.colorset/Contents.json
  storage/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Back.imagestacklayer/Content.imageset/Contents.json
  storage/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Back.imagestacklayer/Contents.json
  storage/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Contents.json
  storage/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Front.imagestacklayer/Content.imageset/Contents.json
  storage/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Front.imagestacklayer/Contents.json
  storage/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Middle.imagestacklayer/Content.imageset/Contents.json
  storage/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Middle.imagestacklayer/Contents.json
  storage/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Back.imagestacklayer/Content.imageset/Contents.json
  storage/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Back.imagestacklayer/Contents.json
  storage/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Contents.json
  storage/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Front.imagestacklayer/Content.imageset/Contents.json
  storage/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Front.imagestacklayer/Contents.json
  storage/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Middle.imagestacklayer/Content.imageset/Contents.json
  storage/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Middle.imagestacklayer/Contents.json
  storage/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/Contents.json
  storage/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/Top Shelf Image Wide.imageset/Contents.json
  storage/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/Top Shelf Image.imageset/Contents.json
  storage/integration_test/integration_test_tvos/Assets.xcassets/Contents.json
  storage/integration_test/integration_test_tvos/Base.lproj/LaunchScreen.storyboard
  storage/integration_test/integration_test_tvos/Base.lproj/Main.storyboard
  storage/integration_test/integration_test_tvos/Info.plist
Labels: cla: yes, tests: succeeded

#481 Fixed typos in doxygen documentation
  performance/src/include/firebase/performance/trace.h
  remote_config/src/include/firebase/remote_config.h
Labels: cla: yes

#480 Added build source to user agent string.
  .github/workflows/cpp-packaging.yml
  .github/workflows/desktop.yml
  CMakeLists.txt
  app/src/app_common.cc
  app/src/app_common.h
  scripts/gha/build_desktop.py
Labels: cla: yes

#474 Fix "Undefined symbols" linker error when DocumentChange::npos was used
  firestore/integration_test/src/integration_test.cc
  firestore/integration_test_internal/src/integration_test.cc
  firestore/src/common/document_change.cc
  release_build_files/readme.md
Labels: api: firestore, cla: yes

#479 Feature/tvos support integration tests firestore internal
  firestore/integration_test_internal/Podfile
  firestore/integration_test_internal/integration_test.xcodeproj/project.pbxproj
  firestore/integration_test_internal/integration_test.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  firestore/integration_test_internal/integration_test.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  firestore/integration_test_internal/integration_test.xcworkspace/contents.xcworkspacedata
  firestore/integration_test_internal/integration_test.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  firestore/integration_test_internal/integration_test_tvos/Assets.xcassets/AccentColor.colorset/Contents.json
  firestore/integration_test_internal/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Back.imagestacklayer/Content.imageset/Contents.json
  firestore/integration_test_internal/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Back.imagestacklayer/Contents.json
  firestore/integration_test_internal/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Contents.json
  firestore/integration_test_internal/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Front.imagestacklayer/Content.imageset/Contents.json
  firestore/integration_test_internal/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Front.imagestacklayer/Contents.json
  firestore/integration_test_internal/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Middle.imagestacklayer/Content.imageset/Contents.json
  firestore/integration_test_internal/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Middle.imagestacklayer/Contents.json
  firestore/integration_test_internal/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Back.imagestacklayer/Content.imageset/Contents.json
  firestore/integration_test_internal/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Back.imagestacklayer/Contents.json
  firestore/integration_test_internal/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Contents.json
  firestore/integration_test_internal/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Front.imagestacklayer/Content.imageset/Contents.json
  firestore/integration_test_internal/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Front.imagestacklayer/Contents.json
  firestore/integration_test_internal/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Middle.imagestacklayer/Content.imageset/Contents.json
  firestore/integration_test_internal/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Middle.imagestacklayer/Contents.json
  firestore/integration_test_internal/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/Contents.json
  firestore/integration_test_internal/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/Top Shelf Image Wide.imageset/Contents.json
  firestore/integration_test_internal/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/Top Shelf Image.imageset/Contents.json
  firestore/integration_test_internal/integration_test_tvos/Assets.xcassets/Contents.json
  firestore/integration_test_internal/integration_test_tvos/Base.lproj/LaunchScreen.storyboard
  firestore/integration_test_internal/integration_test_tvos/Base.lproj/Main.storyboard
  firestore/integration_test_internal/integration_test_tvos/Info.plist
Labels: cla: yes, tests: failed

#483 Integration test remove "update podfile" logic
  scripts/gha/build_testapps.py
  scripts/gha/integration_testing/update_podfile.py
Labels: cla: yes

#482 Fix Linux OS is "ubuntu" not "linux"
  scripts/gha/print_matrix_configuration.py
Labels: cla: yes

#485 boringSSL clone specific commit
  .github/workflows/integration_tests.yml
  cmake/external/boringssl.cmake
Labels: cla: yes, tests: failed

#490 Disable remote config test interval for ios.
  remote_config/integration_test/src/integration_test.cc
Labels: cla: yes

#484 Remove cruft related to FIRESTORE_STUB_BUILD.
  firestore/integration_test_internal/src/collection_reference_test.cc
  firestore/integration_test_internal/src/document_change_test.cc
  firestore/integration_test_internal/src/document_reference_test.cc
  firestore/integration_test_internal/src/document_snapshot_test.cc
  firestore/integration_test_internal/src/field_value_test.cc
  firestore/integration_test_internal/src/firestore_test.cc
  firestore/integration_test_internal/src/includes_test.cc
  firestore/integration_test_internal/src/listener_registration_test.cc
  firestore/integration_test_internal/src/query_network_test.cc
  firestore/integration_test_internal/src/query_snapshot_test.cc
  firestore/integration_test_internal/src/query_test.cc
  firestore/integration_test_internal/src/transaction_extra_test.cc
  firestore/integration_test_internal/src/transaction_test.cc
  firestore/integration_test_internal/src/write_batch_test.cc
  firestore/src/common/collection_reference.cc
  firestore/src/common/document_change.cc
  firestore/src/common/document_reference.cc
  firestore/src/common/document_snapshot.cc
  firestore/src/common/field_path.cc
  firestore/src/common/field_value.cc
  firestore/src/common/firestore.cc
  firestore/src/common/futures.h
  firestore/src/common/listener_registration.cc
  firestore/src/common/query.cc
  firestore/src/common/query_snapshot.cc
  firestore/src/common/settings.cc
  firestore/src/common/transaction.cc
  firestore/src/common/wrapper_assertions.h
  firestore/src/common/write_batch.cc
  firestore/src/include/firebase/firestore/field_path.h
  firestore/src/include/firebase/firestore/settings.h
  firestore/src/stub/collection_reference_stub.h
  firestore/src/stub/document_change_stub.h
  firestore/src/stub/document_reference_stub.h
  firestore/src/stub/document_snapshot_stub.h
  firestore/src/stub/field_value_stub.h
  firestore/src/stub/firestore_stub.cc
  firestore/src/stub/firestore_stub.h
  firestore/src/stub/firestore_stub_test_main.cc
  firestore/src/stub/listener_registration_stub.h
  firestore/src/stub/query_snapshot_stub.h
  firestore/src/stub/transaction_stub.h
  firestore/src/stub/write_batch_stub.h
Labels: cla: yes

#466 Feature/tvos ios one build script
  build_scripts/tvos/Info_ios_and_tvos.plist
  scripts/gha/build_ios_tvos.py
Labels: cla: yes

#467 Fix for headers not copied over to firebase.framework while building ios/tvos
  app/CMakeLists.txt
Labels: cla: yes

#492 [RemoteConfig] Fix iOS SetConfigSettings
  remote_config/integration_test/src/integration_test.cc
  remote_config/src/ios/remote_config_ios.mm
Labels: cla: yes

#486 Resolve macros related to STLPort.
  app/CMakeLists.txt
  firestore/integration_test/src/integration_test.cc
  firestore/integration_test_internal/src/cleanup_test.cc
  firestore/integration_test_internal/src/firestore_integration_test.h
  firestore/integration_test_internal/src/firestore_test.cc
  firestore/integration_test_internal/src/integration_test.cc
  firestore/integration_test_internal/src/server_timestamp_test.cc
  firestore/integration_test_internal/src/transaction_extra_test.cc
  firestore/integration_test_internal/src/transaction_test.cc
  firestore/integration_test_internal/src/validation_test.cc
  firestore/src/android/document_reference_android.cc
  firestore/src/android/document_reference_android.h
  firestore/src/android/event_listener_android.h
  firestore/src/android/firestore_android.cc
  firestore/src/android/firestore_android.h
  firestore/src/android/lambda_event_listener.h
  firestore/src/android/lambda_transaction_function.h
  firestore/src/android/listener_registration_android.h
  firestore/src/android/query_android.cc
  firestore/src/android/query_android.h
  firestore/src/android/timestamp_portable.cc
  firestore/src/common/document_reference.cc
  firestore/src/common/event_listener.h
  firestore/src/common/field_path.cc
  firestore/src/common/firestore.cc
  firestore/src/common/query.cc
  firestore/src/include/firebase/firestore.h
  firestore/src/include/firebase/firestore/document_reference.h
  firestore/src/include/firebase/firestore/field_path.h
  firestore/src/include/firebase/firestore/map_field_value.h
  firestore/src/include/firebase/firestore/query.h
  firestore/src/main/firestore_main.h
Labels: cla: yes, tests: succeeded

#478 Add the FIREBASE_PYTHON_EXECUTABLE cache variable to cmake
  CMakeLists.txt
  admob/integration_test/CMakeLists.txt
  analytics/CMakeLists.txt
  analytics/integration_test/CMakeLists.txt
  app/CMakeLists.txt
  app/integration_test/CMakeLists.txt
  auth/integration_test/CMakeLists.txt
  cmake/binary_to_array.cmake
  cmake/external_rules.cmake
  database/integration_test/CMakeLists.txt
  dynamic_links/integration_test/CMakeLists.txt
  external/vcpkg_custom_data/toolchains/linux_32.cmake
  firestore/integration_test/CMakeLists.txt
  firestore/integration_test_internal/CMakeLists.txt
  functions/integration_test/CMakeLists.txt
  installations/integration_test/CMakeLists.txt
  messaging/integration_test/CMakeLists.txt
  remote_config/integration_test/CMakeLists.txt
  storage/integration_test/CMakeLists.txt
Labels: api: firestore, cla: yes, tests: succeeded

#495 Roll back #486
  app/CMakeLists.txt
  firestore/integration_test/src/integration_test.cc
  firestore/integration_test_internal/src/cleanup_test.cc
  firestore/integration_test_internal/src/firestore_integration_test.h
  firestore/integration_test_internal/src/firestore_test.cc
  firestore/integration_test_internal/src/integration_test.cc
  firestore/integration_test_internal/src/server_timestamp_test.cc
  firestore/integration_test_internal/src/transaction_extra_test.cc
  firestore/integration_test_internal/src/transaction_test.cc
  firestore/integration_test_internal/src/validation_test.cc
  firestore/src/android/document_reference_android.cc
  firestore/src/android/document_reference_android.h
  firestore/src/android/event_listener_android.h
  firestore/src/android/firestore_android.cc
  firestore/src/android/firestore_android.h
  firestore/src/android/lambda_event_listener.h
  firestore/src/android/lambda_transaction_function.h
  firestore/src/android/listener_registration_android.h
  firestore/src/android/query_android.cc
  firestore/src/android/query_android.h
  firestore/src/android/timestamp_portable.cc
  firestore/src/common/document_reference.cc
  firestore/src/common/field_path.cc
  firestore/src/common/firestore.cc
  firestore/src/common/query.cc
  firestore/src/include/firebase/firestore.h
  firestore/src/include/firebase/firestore/document_reference.h
  firestore/src/include/firebase/firestore/event_listener.h
  firestore/src/include/firebase/firestore/field_path.h
  firestore/src/include/firebase/firestore/map_field_value.h
  firestore/src/include/firebase/firestore/query.h
  firestore/src/main/firestore_main.h
Labels: cla: yes, tests: succeeded

#497 Workaround for issue with Doxygen doc generation.
  auth/src/include/firebase/auth/credential.h
  firestore/src/include/firebase/firestore/collection_reference.h
  firestore/src/include/firebase/firestore/document_reference.h
  firestore/src/include/firebase/firestore/query.h
  firestore/src/include/firebase/firestore/write_batch.h
Labels: cla: yes

#491 Fix absl leakage by using Firebase 8.2.0
  cmake/external/firestore.cmake
  firestore/integration_test_internal/Podfile
  firestore/integration_test_internal/integration_test.xcodeproj/project.pbxproj
  firestore/integration_test_internal/src/bundle_test.cc
  firestore/src/common/firestore.cc
  firestore/src/include/firebase/firestore.h
  firestore/src/main/firestore_main.cc
  firestore/src/main/firestore_main.h
  ios_pod/Podfile
  release_build_files/readme.md
Labels: cla: yes, tests: succeeded

#498 updating android and ios versions across repo.
  admob/integration_test/Podfile
  analytics/integration_test/Podfile
  app/integration_test/Podfile
  auth/integration_test/Podfile
  database/integration_test/Podfile
  dynamic_links/integration_test/Podfile
  firestore/integration_test/Podfile
  functions/integration_test/Podfile
  installations/integration_test/Podfile
  messaging/integration_test/Podfile
  release_build_files/readme.md
  remote_config/integration_test/Podfile
  scripts/gha/integration_testing/gameloop_android/app/build.gradle
  storage/integration_test/Podfile
Labels: cla: yes
