Repository firebase/firebase-cpp-sdk, pull requests merged in 2021-12, with the labels that each got.

#756 Timeout and Retry FTL failures and mark flakiness
  .github/workflows/integration_tests.yml
  scripts/gha/integration_testing/test_validation.py
  scripts/gha/it_workflow.py
  scripts/gha/summarize_test_results.py
  scripts/gha/test_lab.py
Labels: cla: yes, tests: succeeded, skip-release-notes

#775 Add Analytics header update to iOS SDK update.
  .github/workflows/update-dependencies.yml
Labels: cla: yes, skip-release-notes

#774 Change Xcode version from 12.2 to 12.4 to ensure GitHub support.
  .github/workflows/cpp-packaging.yml
  .github/workflows/desktop.yml
  .github/workflows/integration_tests.yml
  release_build_files/readme.md
  scripts/gha/print_matrix_configuration.py
Labels: cla: yes

#767 Properly convert milliseconds to seconds
  release_build_files/readme.md
  remote_config/src/desktop/remote_config_desktop.cc
Labels: cla: yes, tests: failed

#783 Change LogDebug to NSLog in app's swizzling code.
  app/src/invites/ios/invites_ios_startup.mm
  release_build_files/readme.md
Labels: cla: yes

#780 Add copyright line when importing Analytics iOS headers, if missing
  .github/workflows/update-dependencies.yml
Labels: cla: yes, skip-release-notes

#786 Also set Xcode version explicitly in Android workflow.
  .github/workflows/android.yml
Labels: cla: yes, skip-release-notes

#785 Timeout & retry "install integration test deps" step
  .github/workflows/integration_tests.yml
  build_scripts/android/install_prereqs.sh
Labels: cla: yes, skip-release-notes

#787 Feature/admob 2021 merge from main 2
  .github/workflows/android.yml
  .github/workflows/cpp-packaging.yml
  .github/workflows/desktop.yml
  .github/workflows/integration_tests.yml
  .github/workflows/update-dependencies.yml
  Android/firebase_dependencies.gradle
  README.md
  admob/integration_test/Podfile
  analytics/integration_test/Podfile
  analytics/ios_headers/FIREventNames.h
  analytics/ios_headers/FIRParameterNames.h
  analytics/ios_headers/FIRUserPropertyNames.h
  app/integration_test/Podfile
  app/src/invites/ios/invites_ios_startup.mm
  app/src/util_ios.h
  app/src/util_ios.mm
  auth/integration_test/Podfile
  build_scripts/android/install_prereqs.sh
  cmake/external/firestore.cmake
  cpp_sdk_version.json
  database/database_resources/build.gradle
  database/integration_test/Podfile
  dynamic_links/integration_test/Podfile
  firestore/integration_test/Podfile
  firestore/integration_test_internal/Podfile
  functions/integration_test/Podfile
  installations/integration_test/Podfile
  ios_pod/Podfile
  messaging/integration_test/Podfile
  release_build_files/Android/firebase_dependencies.gradle
  release_build_files/readme.md
  remote_config/integration_test/Podfile
  remote_config/src/desktop/remote_config_desktop.cc
  scripts/gha/build_testapps.py
  scripts/gha/integration_testing/test_validation.py
  scripts/gha/it_workflow.py
  scripts/gha/print_matrix_configuration.py
  scripts/gha/summarize_test_results.py
  scripts/gha/test_lab.py
  scripts/gha/trigger_workflow.py
  storage/integration_test/Podfile
Labels: cla: yes, tests: in-progress, tests: failed

#788 Add a delay to the Analytics test app.
  analytics/integration_test/src/integration_test.cc
Labels: cla: yes, tests: succeeded, skip-release-notes

#784 In the test report, if test failed on all devices. Mark [All x test devices]
  scripts/gha/summarize_test_results.py
Labels: cla: yes, skip-release-notes

#769 AdMob AdRequest Neighboring Content URLS
  admob/integration_test/src/integration_test.cc
  admob/src/android/ad_request_converter.cc
  admob/src/android/admob_android.h
  admob/src/common/admob_common.cc
  admob/src/include/firebase/admob/types.h
  admob/src/ios/FADRequest.mm
  app/src/util_android.cc
  app/src/util_android.h
  app/src/util_ios.h
  app/src/util_ios.mm
Labels: cla: yes

#782 Disable -Wnullability-completeness on iOS and macOS.
  .github/workflows/android.yml
  CMakeLists.txt
Labels: cla: yes, skip-release-notes

#789 Update public documentation for C++ FCM SDK.
  messaging/samples/AndroidManifest.xml
  messaging/samples/src/java/com/google/firebase/messaging/cpp/samples/MyActivity.java
Labels: skip-release-notes

#751 Split mutex.h into .h and .cc files
  app/CMakeLists.txt
  app/src/mutex.h
  app/src/mutex_pthread.cc
  app/src/mutex_windows.cc
  app/src/reference_counted_future_impl.h
  app/src/secure/user_secure_fake_internal.cc
  app/src/secure/user_secure_windows_internal.cc
  database/src/desktop/persistence/noop_persistence_manager.cc
Labels: cla: yes, tests: succeeded, skip-release-notes

#772 Functions to Disable AdMob Automatic Services on iOS
  admob/integration_test/src/integration_test.cc
  admob/src/android/admob_android.cc
  admob/src/include/firebase/admob.h
  admob/src/ios/admob_ios.mm
  admob/src/stub/admob_stub.cc
  app/src/util_android.h
  app/src/util_ios.h
  app/src/util_ios.mm
Labels: cla: yes

#794 future.h: Fix minor typo in the docs for FutureBase
  app/src/include/firebase/future.h
Labels: skip-release-notes

#792 Move mutex.h header to public internal
  app/CMakeLists.txt
  app/src/include/firebase/internal/mutex.h
  app/src/mutex.h
  docs/Doxyfile
  testing/CMakeLists.txt
Labels: tests: succeeded, skip-release-notes

#798 future.h: replace std::mutex with firebase::Mutex
  app/src/include/firebase/future.h
  app/src/include/firebase/internal/future_impl.h
Labels: tests: succeeded, skip-release-notes

#802 Change setup-gcloud to use @v0 instead of @master as per their readme.
  .github/workflows/integration_tests.yml
Labels: skip-release-notes
