Repository firebase/firebase-cpp-sdk, pull requests merged in 2021-03, with the labels that each got.

#288 Bump Firestore version to 7.7.0
  cmake/external/firestore.cmake
Labels: api: firestore, cla: yes

#293 update firestore version
  cmake/external/firestore.cmake
Labels: cla: yes

#289 Feature/android resources crash old devices
  admob/CMakeLists.txt
  android_build_files/extract_and_dex.gradle
  app/CMakeLists.txt
  auth/CMakeLists.txt
  cmake/binary_to_array.cmake
  database/CMakeLists.txt
  firestore/CMakeLists.txt
  release_build_files/readme.md
  storage/CMakeLists.txt
Labels: cla: yes

#291 [RemoteConfig]Update desktop rest unit test
  remote_config/CMakeLists.txt
  remote_config/src/desktop/remote_config_request.h
  remote_config/src/desktop/remote_config_response.cc
  remote_config/src/desktop/request.fbs
  remote_config/src/desktop/rest.cc
  remote_config/src/desktop/rest.h
  remote_config/src/desktop/rest_fake.cc
  remote_config/src/desktop/rest_nanopb.h
  remote_config/src/desktop/rest_nanopb_decode.cc
  remote_config/src/desktop/rest_nanopb_decode.h
  remote_config/src/desktop/rest_nanopb_encode.cc
  remote_config/src/desktop/rest_nanopb_encode.h
  remote_config/tests/desktop/rest_test.cc
Labels: cla: yes

#290 Remove the extra delay in storage integration test on mobile.
  storage/integration_test/src/integration_test.cc
Labels: cla: yes

#294 Update .gitignore to ignore all *_build folders
  .gitignore
Labels: cla: yes

#287 build ios xcframework
  .github/workflows/cpp-packaging.yml
  .github/workflows/ios.yml
  build_scripts/ios/Info.plist
  build_scripts/ios/build.sh
  build_scripts/ios/package.sh
  release_build_files/readme.md
  scripts/gha/build_testapps.py
  scripts/gha/integration_testing/build_testapps.json
Labels: cla: yes

#301 Python script to extract matrix values used in github workflows.
  scripts/gha/print_matrix_configuration.py
Labels: cla: yes

#300 Fixed race condition when removing listeners.
  database/integration_test/src/integration_test.cc
  database/src/desktop/core/event_registration.cc
  database/src/desktop/core/event_registration.h
  database/src/desktop/core/repo.cc
  database/src/desktop/database_desktop.cc
  database/src/desktop/database_desktop.h
  database/src/desktop/query_desktop.cc
  database/src/desktop/query_desktop.h
  release_build_files/readme.md
Labels: cla: yes

#299 Fix a memory leak in android task/callback pattern
  installations/src/android/installations_android.cc
  remote_config/src/android/remote_config_android.cc
Labels: cla: yes

#296 Update issue templates
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/issue.md
Labels: cla: yes

#304 separate config and matrix parameters.
  scripts/gha/print_matrix_configuration.py
Labels: cla: yes

#308 Remove the build_type_header logic
  app/CMakeLists.txt
  app/src/invites/ios/invites_receiver_internal_ios.mm
  auth/src/android/credential_android.cc
  auth/src/ios/credential_ios.mm
  build_type_header.py
  build_type_header_test.py
  dynamic_links/src/dynamic_links_ios.mm
Labels: cla: yes

#297 Add "expanded matrix" option to workflows
  .github/workflows/android.yml
  .github/workflows/cpp-packaging.yml
  .github/workflows/desktop.yml
  .github/workflows/integration_tests.yml
  .github/workflows/ios.yml
  scripts/gha/print_matrix_configuration.py
Labels: cla: yes

#313 Delete config.proto
  remote_config/src_protos/config.proto
Labels: cla: yes

#320 LSC: Replace uses of `int64` with `int64_t` and similar integer type aliases.
  app/rest/tests/transport_curl_test.cc
  app/tests/util_android_test.cc
Labels: cla: yes

#312 Update the BUILD file with the 7.5.0 Pods
  version.sh
Labels: cla: yes

#314 Updating android dependencies versions for firebase-cpp-sdk.
  release_build_files/Android/firebase_dependencies.gradle
Labels: cla: yes

#315 Update the Unity Remote Config API
  remote_config/src/common.cc
  remote_config/src/common.h
  remote_config/src/include/firebase/remote_config.h
Labels: cla: yes

#319 Firestore: Add JniRunnable, a Java Runnable class whose run() method invokes a C++ function.
  firestore/CMakeLists.txt
  firestore/src/android/firestore_android.cc
  firestore/src/android/jni_runnable_android.cc
  firestore/src/android/jni_runnable_android.h
  firestore/src/tests/android/jni_runnable_android_test.cc
  firestore/src_java/com/google/firebase/firestore/internal/cpp/JniRunnable.java
Labels: cla: yes

#317 Firestore: Migrate to SimpleThrowInvalidArgument
  firestore/CMakeLists.txt
  firestore/src/ios/hard_assert_ios.cc
  firestore/src/ios/hard_assert_ios.h
  firestore/src/ios/query_ios.cc
  firestore/src/ios/user_data_converter_ios.cc
Labels: cla: yes

#318 Firestore: Translate Java exceptions to C++ exceptions of the right type
  firestore/src/android/exception_android.cc
  firestore/src/android/exception_android.h
  firestore/src/tests/firestore_test.cc
  firestore/src/tests/query_test.cc
  firestore/src/tests/validation_test.cc
Labels: cla: yes

#316 Firestore: Remove firestore_cc_library
  firestore/run_local_tests.sh
Labels: cla: yes

#322 Updating Integration tests to FTL iOS Version 12.4
  .github/workflows/integration_tests.yml
  scripts/gha/print_matrix_configuration.py
Labels: cla: yes

#323 Allow integration_tests workflow to run against a packaged SDK.
  .github/workflows/cpp-packaging.yml
  .github/workflows/integration_tests.yml
  database/integration_test/src/integration_test.cc
  scripts/gha/trigger_workflow.py
Labels: cla: yes

#311 [RemoteConfig] Fix the default cache value
  remote_config/src/include/firebase/remote_config.h
Labels: cla: yes

#327 Deflake: Cache NDK Downloads
  .github/workflows/android.yml
  .github/workflows/cpp-packaging.yml
  .github/workflows/integration_tests.yml
  build_scripts/android/install_prereqs.sh
Labels: cla: yes

#324 Firestore: Expand validation_test to cover other platforms
  firestore/src/android/field_path_portable.cc
  firestore/src/android/field_path_portable.h
  firestore/src/android/firestore_android.cc
  firestore/src/android/transaction_android.cc
  firestore/src/common/field_path.cc
  firestore/src/include/firebase/firestore/field_path.h
  firestore/src/ios/user_data_converter_ios.cc
  firestore/src/tests/validation_test.cc
Labels: cla: yes

#325 Firestore: Migrate hard assertions to common infrastructure too
  firestore/CMakeLists.txt
  firestore/src/common/hard_assert_common.cc
  firestore/src/common/hard_assert_common.h
  firestore/src/ios/credentials_provider_desktop.cc
  firestore/src/ios/document_change_ios.cc
  firestore/src/ios/document_snapshot_ios.cc
  firestore/src/ios/field_value_ios.cc
  firestore/src/ios/firestore_ios.cc
  firestore/src/ios/promise_factory_ios.h
  firestore/src/ios/promise_ios.h
  firestore/src/ios/query_ios.cc
  firestore/src/ios/source_ios.h
  firestore/src/ios/transaction_ios.cc
  firestore/src/ios/user_data_converter_ios.cc
  firestore/src/tests/util/integration_test_util.cc
Labels: cla: yes

#332 Added experimental Firebase Performance library code.
  performance/example_usage.cc
  performance/src/android/firebase_performance.cc
  performance/src/android/http_metric.cc
  performance/src/android/performance_android_internal.h
  performance/src/android/trace.cc
  performance/src/http_metric_test.cc
  performance/src/include/firebase/performance.h
  performance/src/include/firebase/performance/http_metric.h
  performance/src/include/firebase/performance/trace.h
  performance/src/ios/firebase_performance.mm
  performance/src/ios/http_metric.mm
  performance/src/ios/trace.mm
  performance/src/performance_common.cc
  performance/src/performance_common.h
  performance/src/performance_test.cc
  performance/src/trace_test.cc
  performance/src_ios/fake/FIRHTTPMetric.h
  performance/src_ios/fake/FIRHTTPMetric.mm
  performance/src_ios/fake/FIRPerformance.h
  performance/src_ios/fake/FIRPerformance.mm
  performance/src_ios/fake/FIRPerformanceAttributable.h
  performance/src_ios/fake/FIRTrace.h
  performance/src_ios/fake/FIRTrace.mm
  performance/src_java/fake/com/google/firebase/perf/FirebasePerformance.java
  performance/src_java/fake/com/google/firebase/perf/FirebasePerformanceAttributable.java
  performance/src_java/fake/com/google/firebase/perf/metrics/HttpMetric.java
  performance/src_java/fake/com/google/firebase/perf/metrics/Trace.java
  performance/stubs/http_metric_stub.cc
  performance/stubs/performance_stub.cc
  performance/stubs/trace_stub.cc
Labels: cla: yes

#329 cl/361792354: Call `Terminate()` from `~FirebaseFirestore()` so that the cached Java instance will be cleared.
  firestore/src/android/firestore_android.cc
  firestore/src/tests/firestore_integration_test.cc
  firestore/src/tests/firestore_integration_test.h
  firestore/src/tests/firestore_test.cc
  firestore/src_java/com/google/firebase/firestore/internal/cpp/FirestoreTasks.java
Labels: api: firestore, cla: yes

#331 Port cl/362275804: Fix build error in promise_android_test.cc
  firestore/src/tests/android/promise_android_test.cc
Labels: cla: yes

#330 Port cl/361876089: JniRunnable: Fix a deadlock when Detach() is called from Run()
  firestore/src/android/jni_runnable_android.cc
  firestore/src/android/jni_runnable_android.h
  firestore/src/tests/android/jni_runnable_android_test.cc
  firestore/src_java/com/google/firebase/firestore/internal/cpp/JniRunnable.java
Labels: api: firestore, cla: yes

#336 Add platform include to installations header
  installations/src/installations_internal.h
Labels: cla: yes

#344 Bugfix Database Large String Crash on Set on Desktop
  cmake/external_rules.cmake
  database/integration_test/src/integration_test.cc
  release_build_files/readme.md
  scripts/patch_websockets.py
Labels: cla: yes

#346 Feature/fix android windows builds
  .github/workflows/android.yml
  android_build_files/android_abis.gradle
  cmake/external_rules.cmake
  firestore/integration_test_internal/CMakeLists.txt
  firestore/integration_test_internal/abseil-cpp.cmake
  scripts/gha/print_matrix_configuration.py
Labels: cla: yes

#348 Improve integration test results reporting.
  .github/workflows/integration_tests.yml
  scripts/gha/summarize_test_results.py
Labels: cla: yes

#345 Fix `Mutex` destructors being incorrectly run at exit (cl/364325997)
  app/rest/transport_curl.cc
  app/rest/util.cc
  app/src/app_common.cc
  app/src/callback.cc
  app/src/cleanup_notifier.cc
  app/src/cleanup_notifier.h
  app/src/secure/user_secure_manager.cc
  app/src/secure/user_secure_manager.h
  app/src/util.cc
  app/src/util.h
  auth/src/auth.cc
  auth/src/desktop/rpcs/auth_request.cc
  firestore/src/common/firestore.cc
  release_build_files/readme.md
Labels: api: firestore, cla: yes

#350 Don't run the internal integration tests on the packaged SDK.
  scripts/gha/build_testapps.py
Labels: cla: yes, tests: succeeded
