Repository firebase/firebase-cpp-sdk, pull requests merged in 2021-08, with the labels that each got.

#582 Add check for release notes update.
  .github/workflows/checks.yml
Labels: cla: yes, skip-release-notes

#584 updated docs for tvos
  README.md
Labels: cla: yes

#587 Fix Android test devices
  scripts/gha/print_matrix_configuration.py
Labels: cla: yes

#589 Deflake TestInvalidatingReferencesWhenDeletingStorage and App
  storage/integration_test/src/integration_test.cc
Labels: cla: yes, tests: succeeded, skip-release-notes

#592 Add Firestore to README.md.
  README.md
Labels: api: firestore, cla: yes

#597 Add retry to RTDB .info/connected test on iOS.
  database/integration_test/src/integration_test.cc
Labels: cla: yes, tests: succeeded, skip-release-notes

#596 operator== and operator!= for SnapshotMetadata and Settings
  firestore/integration_test_internal/CMakeLists.txt
  firestore/integration_test_internal/src/android/settings_android_test.cc
  firestore/integration_test_internal/src/cleanup_test.cc
  firestore/integration_test_internal/src/settings_test.cc
  firestore/src/include/firebase/firestore/settings.h
  firestore/src/include/firebase/firestore/snapshot_metadata.h
  release_build_files/readme.md
Labels: api: firestore, cla: yes, tests: succeeded

#598 operator== and operator!= for QuerySnapshot.
  firestore/integration_test_internal/src/query_snapshot_test.cc
  firestore/src/android/query_snapshot_android.cc
  firestore/src/android/query_snapshot_android.h
  firestore/src/common/query_snapshot.cc
  firestore/src/include/firebase/firestore/query_snapshot.h
  firestore/src/main/query_snapshot_main.cc
  firestore/src/main/query_snapshot_main.h
  release_build_files/readme.md
Labels: api: firestore, cla: yes

#599 Print out integration test result for desktop platform
  scripts/gha/desktop_tester.py
Labels: cla: yes, tests: succeeded

#601 Define new error codes for passthrough errors.
  auth/src/android/common_android.cc
  auth/src/include/firebase/auth/types.h
Labels: cla: yes, skip-release-notes

#549 Run Firestore tests against Emulators where possible.
  .github/workflows/integration_tests.yml
  scripts/gha/integration_testing/gameloop_android/app/src/main/java/com/google/firebase/gameloop/MainActivity.kt
  testing/sample_framework/src/ios/ios_app_framework.mm
Labels: cla: yes

#577 Migrate CPP SDK from FieldValue to Protobuf
  Android/firebase_dependencies.gradle
  admob/integration_test/Podfile
  analytics/integration_test/Podfile
  app/integration_test/Podfile
  auth/integration_test/Podfile
  cmake/external/firestore.cmake
  cpp_sdk_version.json
  database/integration_test/Podfile
  dynamic_links/integration_test/Podfile
  firestore/CMakeLists.txt
  firestore/integration_test/Podfile
  firestore/integration_test_internal/CMakeLists.txt
  firestore/integration_test_internal/Podfile
  firestore/integration_test_internal/integration_test.xcodeproj/project.pbxproj
  firestore/src/main/document_snapshot_main.cc
  firestore/src/main/document_snapshot_main.h
  firestore/src/main/field_value_main.cc
  firestore/src/main/field_value_main.h
  firestore/src/main/query_main.cc
  firestore/src/main/query_main.h
  firestore/src/main/transaction_main.cc
  firestore/src/main/user_data_converter_main.cc
  firestore/src/main/user_data_converter_main.h
  functions/integration_test/Podfile
  installations/integration_test/Podfile
  ios_pod/Podfile
  messaging/integration_test/Podfile
  release_build_files/Android/firebase_dependencies.gradle
  release_build_files/readme.md
  remote_config/integration_test/Podfile
  storage/integration_test/Podfile
Labels: api: firestore, cla: yes

#606 operator== and operator!= for SetOptions.
  firestore/integration_test_internal/CMakeLists.txt
  firestore/integration_test_internal/src/set_options_test.cc
  firestore/src/common/set_options.cc
  firestore/src/include/firebase/firestore/set_options.h
  firestore/src/main/set_options_main.h
  firestore/src/main/user_data_converter_main.cc
  firestore/src/main/user_data_converter_main.h
  release_build_files/readme.md
Labels: api: firestore, cla: yes, tests: succeeded

#611 Add a comment about using --gtest_catch_exceptions=0 to get full stack traces
  testing/test_framework/src/firebase_test_framework.cc
Labels: cla: yes, skip-release-notes

#607 operator== and operator!= for DocumentChange
  firestore/integration_test_internal/src/document_change_test.cc
  firestore/src/android/document_change_android.cc
  firestore/src/android/document_change_android.h
  firestore/src/common/document_change.cc
  firestore/src/include/firebase/firestore/document_change.h
  firestore/src/main/document_change_main.cc
  firestore/src/main/document_change_main.h
  release_build_files/readme.md
Labels: api: firestore, cla: yes, tests: succeeded

#613 Add private function that returns a query's hash code.
  firestore/integration_test_internal/src/query_test.cc
  firestore/src/android/query_android.cc
  firestore/src/android/query_android.h
  firestore/src/common/query.cc
  firestore/src/include/firebase/firestore/query.h
  firestore/src/main/query_main.h
Labels: api: firestore, cla: yes, tests: succeeded, skip-release-notes

#616 Replace HARD_ASSERT with SIMPLE_HARD_ASSERT to fix absl linker breakage.
  firestore/src/main/transaction_main.cc
Labels: api: firestore, cla: yes, tests: succeeded, skip-release-notes

#617 Update android and ios versions for M102
  Android/firebase_dependencies.gradle
  admob/admob_resources/build.gradle
  admob/integration_test/Podfile
  analytics/integration_test/Podfile
  app/app_resources/build.gradle
  app/google_api_resources/build.gradle
  app/integration_test/Podfile
  app/invites_resources/build.gradle
  auth/auth_resources/build.gradle
  auth/integration_test/Podfile
  cmake/external/firestore.cmake
  database/database_resources/build.gradle
  database/integration_test/Podfile
  dynamic_links/integration_test/Podfile
  firestore/firestore_resources/build.gradle
  firestore/integration_test/Podfile
  firestore/integration_test_internal/Podfile
  functions/integration_test/Podfile
  installations/integration_test/Podfile
  ios_pod/Podfile
  messaging/integration_test/Podfile
  messaging/messaging_java/build.gradle
  release_build_files/Android/firebase_dependencies.gradle
  release_build_files/readme.md
  remote_config/integration_test/Podfile
  storage/integration_test/Podfile
  storage/storage_resources/build.gradle
Labels: cla: yes

#618 Replace ThrowInvalidArgument with SimpleThrowInvalidArgument to fix iOS absl linker error in Unity SDK
  firestore/src/main/firestore_main.cc
  firestore/src/main/transaction_main.cc
Labels: api: firestore, cla: yes, tests: succeeded, skip-release-notes
