Repository firebase/firebase-cpp-sdk, pull requests merged in 2021-04, with the labels that each got.

#349 Add test on iOS simulator
  .github/workflows/integration_tests.yml
  scripts/gha/build_testapps.py
  scripts/gha/integration_testing/gameloop/gameloop.xcodeproj/project.pbxproj
  scripts/gha/integration_testing/gameloop/gameloop/AppDelegate.swift
  scripts/gha/integration_testing/gameloop/gameloop/Assets.xcassets/AccentColor.colorset/Contents.json
  scripts/gha/integration_testing/gameloop/gameloop/Assets.xcassets/AppIcon.appiconset/Contents.json
  scripts/gha/integration_testing/gameloop/gameloop/Assets.xcassets/Contents.json
  scripts/gha/integration_testing/gameloop/gameloop/Base.lproj/LaunchScreen.storyboard
  scripts/gha/integration_testing/gameloop/gameloop/Base.lproj/Main.storyboard
  scripts/gha/integration_testing/gameloop/gameloop/Constants.swift
  scripts/gha/integration_testing/gameloop/gameloop/Info.plist
  scripts/gha/integration_testing/gameloop/gameloop/ViewController.swift
  scripts/gha/integration_testing/gameloop/gameloopUITests/Info.plist
  scripts/gha/integration_testing/gameloop/gameloopUITests/gameloopUITests.swift
  scripts/gha/integration_testing/test_validation.py
  scripts/gha/print_matrix_configuration.py
  scripts/gha/summarize_test_results.py
  scripts/gha/test_simulator.py
Labels: cla: yes

#353 fix bug: disable test on simulator
  .github/workflows/integration_tests.yml
Labels: cla: yes

#354 disable test on simulator
  .github/workflows/integration_tests.yml
Labels: cla: yes

#357 Add 3rd Party Notices File for Packaged Releases
  release_build_files/NOTICES
Labels: cla: yes

#358 Change GKLocalPlayer to be runtime referenced
  auth/src/ios/credential_ios.mm
Labels: cla: yes

#352 Delete Firestore's Unity glue code, which now lives with the Unity C# code
  build_scripts/other/package.sh
  firestore/src/include/firebase/csharp/api_headers.h
  firestore/src/include/firebase/csharp/document_event_listener.cc
  firestore/src/include/firebase/csharp/document_event_listener.h
  firestore/src/include/firebase/csharp/firestore_instance_management.cc
  firestore/src/include/firebase/csharp/firestore_instance_management.h
  firestore/src/include/firebase/csharp/map.h
  firestore/src/include/firebase/csharp/query_event_listener.cc
  firestore/src/include/firebase/csharp/query_event_listener.h
  firestore/src/include/firebase/csharp/snapshots_in_sync_listener.cc
  firestore/src/include/firebase/csharp/snapshots_in_sync_listener.h
  firestore/src/include/firebase/csharp/transaction_manager.cc
  firestore/src/include/firebase/csharp/transaction_manager.h
  firestore/src/include/firebase/csharp/vector.h
Labels: api: firestore, cla: yes, tests: succeeded

#351 Tie up the loose ends from moving Firestore's integration tests into integration_test_internal
  firestore/integration_test_internal/src/android/jni_runnable_android_test.cc
  firestore/integration_test_internal/src/android/promise_android_test.cc
  firestore/integration_test_internal/src/firestore_integration_test.cc
  firestore/integration_test_internal/src/firestore_integration_test.h
  firestore/integration_test_internal/src/firestore_test.cc
  firestore/integration_test_internal/src/type_test.cc
  firestore/src/tests/android/cancellation_token_source.cc
  firestore/src/tests/android/cancellation_token_source.h
  firestore/src/tests/android/field_path_portable_test.cc
  firestore/src/tests/android/firebase_firestore_settings_android_test.cc
  firestore/src/tests/android/firestore_android_test_main.cc
  firestore/src/tests/android/firestore_integration_test_android.cc
  firestore/src/tests/android/firestore_integration_test_android.h
  firestore/src/tests/android/firestore_integration_test_android_test.cc
  firestore/src/tests/android/geo_point_android_test.cc
  firestore/src/tests/android/jni_runnable_android_test.cc
  firestore/src/tests/android/promise_android_test.cc
  firestore/src/tests/android/settings_android_test.cc
  firestore/src/tests/android/snapshot_metadata_android_test.cc
  firestore/src/tests/android/task_completion_source.cc
  firestore/src/tests/android/task_completion_source.h
  firestore/src/tests/android/timestamp_android_test.cc
Labels: api: firestore, cla: yes, tests: succeeded

#355 Feature/zlibwrapper fixes
  app/rest/tests/zlibwrapper_unittest.cc
  app/rest/zlibwrapper.cc
  app/rest/zlibwrapper.h
Labels: cla: yes

#334 cl/361880889: Uncomment Firestore test `RestartFirestoreLeadsToNewInstance` for Android now that auth is a soft dependency
  firestore/integration_test_internal/src/firestore_test.cc
Labels: api: firestore, cla: yes, tests: succeeded

#362 Port cl/365835301: Fix flaky tests in firestore_test.cc.
  firestore/integration_test_internal/src/firestore_test.cc
Labels: api: firestore, cla: yes, tests: succeeded

#366 Deprecate the STLPort support
  app/src/include/firebase/app.h
  release_build_files/readme.md
Labels: cla: yes

#367 Don't bother printing ccache stats on packaging workflow.
  .github/workflows/cpp-packaging.yml
Labels: cla: yes

#363 Update C++ SDK version to 7.2.0, and dependencies to M93.
  Android/firebase_dependencies.gradle
  admob/integration_test/Podfile
  analytics/integration_test/Podfile
  app/integration_test/Podfile
  auth/integration_test/Podfile
  cmake/external/firestore.cmake
  cpp_sdk_version.json
  database/integration_test/Podfile
  dynamic_links/integration_test/Podfile
  firestore/integration_test/Podfile
  firestore/integration_test_internal/Podfile
  functions/integration_test/Podfile
  installations/integration_test/Podfile
  instance_id/integration_test/Podfile
  ios_pod/Podfile
  messaging/integration_test/Podfile
  release_build_files/Android/firebase_dependencies.gradle
  release_build_files/readme.md
  remote_config/integration_test/Podfile
  storage/integration_test/Podfile
Labels: cla: yes

#361 Removing google play requirement.
  auth/src/auth.cc
  database/src/common/database.cc
  functions/src/common/functions.cc
  release_build_files/readme.md
  storage/src/common/storage.cc
Labels: cla: yes

#369 Feature/update brew version
  .github/workflows/android.yml
  .github/workflows/cpp-packaging.yml
  .github/workflows/desktop.yml
  .github/workflows/integration_tests.yml
Labels: cla: yes

#370 Fix Firestore 7.10.0 build in C++ SDK, and match NanoPB versions.
  cmake/external/nanopb.cmake
  firestore/CMakeLists.txt
Labels: cla: yes

#371 Fix 7.2.0 test issues.
  Android/firebase_dependencies.gradle
  app/src/google_play_services/availability_android.cc
  firestore/CMakeLists.txt
  release_build_files/Android/firebase_dependencies.gradle
Labels: cla: yes, tests: in-progress

#373 Switch to a Firestore commit that fixes a Windows build error.
  cmake/external/firestore.cmake
  firestore/CMakeLists.txt
  scripts/gha/summarize_test_results.py
Labels: cla: yes, tests: failed, tests: in-progress

#374 Prevent absl_time_zone from using weak symbols on Windows.
  firestore/CMakeLists.txt
Labels: cla: yes

#364 Added example implementation of Firebase Test Lab Game Loop library.
  testlab/src/android/testlab.cc
  testlab/src/android/util.cc
  testlab/src/android/util.h
  testlab/src/common/common.cc
  testlab/src/common/common.h
  testlab/src/common/scenario_result.fbs
  testlab/src/desktop/testlab_desktop.cc
  testlab/src/desktop/testlab_macos.h
  testlab/src/desktop/testlab_macos.mm
  testlab/src/include/firebase/testlab.h
  testlab/src/ios/custom_results.h
  testlab/src/ios/custom_results.mm
  testlab/src/ios/testlab.mm
Labels: cla: yes

#368 Fix docs for setting and getting the dispatch queue in Firestore's settings class
  firestore/src/include/firebase/firestore/settings.h
Labels: cla: yes

#359 Added a new test suite for SyncPoints
  database/src/desktop/core/child_event_registration.cc
  database/src/desktop/core/repo.cc
  database/src/desktop/core/value_event_registration.cc
  database/src/desktop/data_snapshot_desktop.cc
  database/src/desktop/data_snapshot_desktop.h
  database/src/desktop/database_reference_desktop.cc
  database/src/desktop/persistence/persistence_manager.cc
  database/src/desktop/query_desktop.cc
  database/src/desktop/util_desktop.cc
  database/src/desktop/util_desktop.h
  database/tests/CMakeLists.txt
  database/tests/desktop/core/sync_point_spec.fbs
  database/tests/desktop/core/sync_point_spec.json
  database/tests/desktop/core/sync_point_spec_test.cc
Labels: cla: yes, tests: succeeded

#377 Added a code format python script to drive clang-format
  .clang-format
  auth/integration_test/src/integration_test.cc
  scripts/format_code.py
Labels: cla: yes

#378 Use Firebase/Crashlytics instead of Crashlytics.
  ios_pod/Podfile
Labels: cla: yes

#379 Solve misc build errors
  firestore/firestore_resources/AndroidManifest.xml
  firestore/firestore_resources/build.gradle
Labels: cla: yes, tests: succeeded

#385 Fix NPE in android_abis.gradle if ANDROID_NDK_HOME is not set
  android_build_files/android_abis.gradle
Labels: cla: yes, tests: succeeded

#384 Remove playbilling
  app/src/future_manager.h
  app/src/include/firebase/internal/future_impl.h
  app/src/include/firebase/util.h
  app/src/reference_counted_future_impl.h
  app/tests/CMakeLists.txt
  cmake/future_lib.cmake
Labels: api: firestore, cla: yes, tests: succeeded

#376 Enable test on android emulator
  .github/workflows/integration_tests.yml
  scripts/gha/integration_testing/gameloop/gameloopUITests/gameloopUITests.swift
  scripts/gha/integration_testing/gameloop_android/app/build.gradle
  scripts/gha/integration_testing/gameloop_android/app/src/androidTest/AndroidManifest.xml
  scripts/gha/integration_testing/gameloop_android/app/src/androidTest/java/com/google/firebase/gameloop/GameLoopUITest.kt
  scripts/gha/integration_testing/gameloop_android/app/src/main/AndroidManifest.xml
  scripts/gha/integration_testing/gameloop_android/app/src/main/java/com/google/firebase/gameloop/MainActivity.kt
  scripts/gha/integration_testing/gameloop_android/app/src/main/res/layout/activity_main.xml
  scripts/gha/integration_testing/gameloop_android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  scripts/gha/integration_testing/gameloop_android/app/src/main/res/values/colors.xml
  scripts/gha/integration_testing/gameloop_android/app/src/main/res/values/strings.xml
  scripts/gha/integration_testing/gameloop_android/app/src/main/res/values/styles.xml
  scripts/gha/integration_testing/gameloop_android/app/src/main/res/xml/file_paths.xml
  scripts/gha/integration_testing/gameloop_android/build.gradle
  scripts/gha/integration_testing/gameloop_android/gradle.properties
  scripts/gha/integration_testing/gameloop_android/gradle/wrapper/gradle-wrapper.jar
  scripts/gha/integration_testing/gameloop_android/gradle/wrapper/gradle-wrapper.properties
  scripts/gha/integration_testing/gameloop_android/gradlew
  scripts/gha/integration_testing/gameloop_android/gradlew.bat
  scripts/gha/integration_testing/gameloop_android/settings.gradle
  scripts/gha/integration_testing/test_validation.py
  scripts/gha/summarize_test_results.py
  scripts/gha/test_lab.py
  scripts/gha/test_simulator.py
Labels: cla: yes

#380 Source Code Format Checks
  .github/workflows/check-labels.yml
  .github/workflows/checks.yml
  CONTRIBUTING.md
  scripts/format_code.py
  scripts/gha/install_prereqs_desktop.py
  scripts/git/hooks/pre-commit
Labels: cla: yes

#395 Update Cocoapods to 7.11.0 and C++ SDK version to 7.3.0.
  admob/integration_test/Podfile
  admob/integration_test/integration_test.xcodeproj/project.pbxproj
  analytics/integration_test/Podfile
  analytics/integration_test/integration_test.xcodeproj/project.pbxproj
  app/integration_test/Podfile
  app/integration_test/integration_test.xcodeproj/project.pbxproj
  auth/integration_test/Podfile
  auth/integration_test/integration_test.xcodeproj/project.pbxproj
  cmake/external/firestore.cmake
  cpp_sdk_version.json
  database/integration_test/Podfile
  database/integration_test/integration_test.xcodeproj/project.pbxproj
  dynamic_links/integration_test/Podfile
  dynamic_links/integration_test/integration_test.xcodeproj/project.pbxproj
  firestore/integration_test/Podfile
  firestore/integration_test/integration_test.xcodeproj/project.pbxproj
  firestore/integration_test_internal/Podfile
  firestore/integration_test_internal/integration_test.xcodeproj/project.pbxproj
  functions/integration_test/Podfile
  functions/integration_test/integration_test.xcodeproj/project.pbxproj
  installations/integration_test/Podfile
  installations/integration_test/integration_test.xcodeproj/project.pbxproj
  instance_id/integration_test/Podfile
  instance_id/integration_test/integration_test.xcodeproj/project.pbxproj
  ios_pod/Podfile
  messaging/integration_test/Podfile
  messaging/integration_test/integration_test.xcodeproj/project.pbxproj
  release_build_files/readme.md
  remote_config/integration_test/Podfile
  remote_config/integration_test/integration_test.xcodeproj/project.pbxproj
  storage/integration_test/Podfile
  storage/integration_test/integration_test.xcodeproj/project.pbxproj
  testing/sample_framework/src/ios/ios_app_framework.mm
  testing/test_framework/download_googletest.py
Labels: cla: yes, tests: succeeded

#397 Fix noformat_file / format_file discrepenency on iOS headers
  .github/workflows/checks.yml
  scripts/format_code.py
Labels: cla: yes

#390 use native android call with app as parameter
  release_build_files/readme.md
  remote_config/src/android/remote_config_android.cc
Labels: cla: yes, tests: succeeded

#389 Ttluse native android call with app as parameter
  remote_config/src/android/remote_config_android.cc
Labels: cla: no

#392 Fixed a number of minor issues with database.
  database/src/desktop/core/indexed_variant.cc
  database/src/desktop/view/child_change_accumulator.cc
  database/src/desktop/view/indexed_filter.cc
  database/src/desktop/view/limited_filter.cc
  database/src/desktop/view/ranged_filter.cc
  database/src/desktop/view/view.cc
  database/src/desktop/view/view_processor.cc
  database/tests/desktop/core/sync_point_spec_test.cc
  database/tests/desktop/view/child_change_accumulator_test.cc
  database/tests/desktop/view/indexed_filter_test.cc
  database/tests/desktop/view/view_test.cc
Labels: cla: yes, tests: succeeded

#400 Removed deprecated copy constructor from MutableData
  database/src/android/mutable_data_android.cc
  database/src/android/mutable_data_android.h
  database/src/common/mutable_data.cc
  database/src/desktop/mutable_data_desktop.cc
  database/src/desktop/mutable_data_desktop.h
  database/src/include/firebase/database/mutable_data.h
  database/src/ios/mutable_data_ios.h
  database/src/ios/mutable_data_ios.mm
Labels: cla: yes

#402 Remove the Deprecated Remote Config Impl
  release_build_files/readme.md
  remote_config/integration_test/src/integration_test.cc
  remote_config/src/android/remote_config_android.cc
  remote_config/src/include/firebase/remote_config.h
  remote_config/src/remote_config.cc
Labels: cla: yes, tests: succeeded

#401 Fix release build notes formatting
  release_build_files/readme.md
Labels: cla: yes
