Repository firebase/firebase-cpp-sdk, pull requests merged in 2021-09, with the labels that each got.

#624 Updates to Admob Android to reduce usage of BannerViewHelper.java
  admob/src/android/admob_android.cc
  admob/src/android/banner_view_internal_android.cc
  admob/src/android/banner_view_internal_android.h
  admob/src_java/com/google/firebase/admob/internal/cpp/BannerViewHelper.java
Labels: cla: yes

#625 iOS Baseline to build upon for the Admob 2021 SDK
  admob/src/android/admob_android.h
  admob/src/common/interstitial_ad.cc
  admob/src/ios/FADNativeExpressAdView.h
  admob/src/ios/FADNativeExpressAdView.mm
  admob/src/ios/FADRequest.mm
  admob/src/ios/FADRewardBasedVideoAdDelegate.h
  admob/src/ios/FADRewardBasedVideoAdDelegate.mm
  admob/src/ios/admob_ios.mm
  admob/src/ios/native_express_ad_view_internal_ios.h
  admob/src/ios/native_express_ad_view_internal_ios.mm
  admob/src/ios/rewarded_video_internal_ios.h
  admob/src/ios/rewarded_video_internal_ios.mm
  admob/tools/ios/testapp/testapp.xcodeproj/project.pbxproj
  admob/tools/ios/testapp/testapp/game_engine.cpp
  admob/tools/ios/testapp/testapp/game_engine.h
Labels: cla: yes

#628 Add placeholder workflow for updating dependencies.
  .github/workflows/update-dependencies.yml
Labels: cla: yes, skip-release-notes

#629 Add workflow to automatically update iOS and Android dependencies.
  .github/workflows/lint.yml
  .github/workflows/update-dependencies.yml
  scripts/gha/create_pull_request.py
  scripts/gha/github.py
  scripts/update_android_ios_dependencies.py
Labels: cla: yes, skip-release-notes

#654 Add some licenses to `NOTICES`
  release_build_files/NOTICES
Labels: cla: yes

#656 Fix log file for when both Android and iOS are present.
  .github/workflows/update-dependencies.yml
Labels: cla: yes, skip-release-notes

#660 8.5.0 Release Notes and Version Update
  cpp_sdk_version.json
  release_build_files/readme.md
Labels: cla: yes

#661 Add a comment field, for when update-dependencies is triggered by others.
  .github/workflows/update-dependencies.yml
Labels: cla: yes, skip-release-notes

#664 Fix the logic to generate .pro file
  android_build_files/generate_proguard.gradle
  release_build_files/readme.md
Labels: cla: yes, tests: failed

#626 Add presubmit trigger with ccache in linux firestore
  .github/workflows/integration_tests.yml
  scripts/gha/it_workflow.py
  scripts/gha/print_matrix_configuration.py
Labels: cla: yes, skip-release-notes

#666 De-flake integration tests on Android devices
  scripts/gha/print_matrix_configuration.py
  scripts/gha/test_simulator.py
Labels: cla: yes, skip-release-notes

#668 Fix integration test check step
  .github/workflows/cpp-packaging.yml
  .github/workflows/integration_tests.yml
Labels: cla: yes, skip-release-notes

#667 Change the way to achieve token while init the app
  messaging/integration_test/src/integration_test.cc
  messaging/src/android/cpp/messaging.cc
  release_build_files/readme.md
Labels: cla: yes, tests: succeeded

#665 Feature/admob 2021 Set|Get RequestConfiguration
  admob/integration_test/src/integration_test.cc
  admob/src/android/ad_request_converter.cc
  admob/src/android/ad_request_converter.h
  admob/src/android/admob_android.cc
  admob/src/android/admob_android.h
  admob/src/android/banner_view_internal_android.cc
  admob/src/common/admob_common.cc
  admob/src/include/firebase/admob.h
  admob/src/include/firebase/admob/types.h
  admob/src/ios/FADRequest.mm
  admob/src/ios/admob_ios.mm
  admob/src/stub/admob_stub.cc
  app/src/util_ios.h
  app/src/util_ios.mm
Labels: cla: yes

#675 Do not hard code project id in expected error message
  firestore/integration_test_internal/src/validation_test.cc
Labels: cla: yes, tests: succeeded, skip-release-notes

#677 ARM Mac open-source and packaged build
  .github/workflows/cpp-packaging.yml
  .github/workflows/desktop.yml
  CMakeLists.txt
  build_scripts/desktop/finish_darwin.sh
  build_scripts/desktop/package.sh
  external/vcpkg_custom_data/response_files/arm64-osx.txt
  external/vcpkg_custom_data/toolchains/macos_arm64.cmake
  external/vcpkg_custom_data/triplets/arm64-osx.cmake
  release_build_files/readme.md
  scripts/gha/build_desktop.py
  scripts/gha/build_testapps.py
  scripts/gha/print_matrix_configuration.py
  scripts/gha/utils.py
  scripts/merge_libraries.py
Labels: cla: yes

#683 Move Pull Request Template for Auto Population
  pull_request_template.md
Labels: cla: yes, no-lint, skip-release-notes

#685 Fix bug in dependency update workflow.
  .github/workflows/update-dependencies.yml
  scripts/update_android_ios_dependencies.py
Labels: cla: yes, skip-release-notes

#694 Update version number for next release to 8.6.0.
  cpp_sdk_version.json
  release_build_files/readme.md
Labels: cla: yes

#697 Remove synchronize trigger check from integration test workflow
  .github/workflows/integration_tests.yml
Labels: cla: yes, tests: succeeded, skip-release-notes

#698 Run linux integration test in desktop workflow
  .github/workflows/desktop.yml
Labels: cla: yes, skip-release-notes

#692 Fix crash caused by ResponseJson::MarkCompleted() failing to set application_data_ if parsing the JSON body fails
  app/rest/response_json.h
  release_build_files/readme.md
Labels: api: auth, api: firestore, cla: yes, tests: succeeded
