Repository firebase/firebase-cpp-sdk, pull requests merged in 2021-07, with the labels that each got.

#488 Make it possible to run firestore tests against emulator
  firestore/integration_test_internal/AndroidManifest.xml
  firestore/integration_test_internal/src/firestore_integration_test.cc
  testing/sample_framework/src/android/android_app_framework.cc
Labels: cla: yes

#501 Fix an issue with Messaging needing a variable to be final
  messaging/src/android/java/com/google/firebase/messaging/cpp/RegistrationIntentService.java
Labels: cla: yes

#502 Update Auth ReauthenticateAndRetrieveData comments
  auth/src/include/firebase/auth/user.h
Labels: cla: yes

#503 Revert Android test tool dependency
  scripts/gha/integration_testing/gameloop_android/app/build.gradle
Labels: cla: yes

#504 Add copyright check to PR checks.
  .github/workflows/checks.yml
  scripts/gha/check_copyright.sh
Labels: cla: yes

#510 Remove STLPort support from public API.
  app/CMakeLists.txt
  firestore/integration_test/src/integration_test.cc
  firestore/integration_test_internal/src/cleanup_test.cc
  firestore/integration_test_internal/src/firestore_integration_test.h
  firestore/integration_test_internal/src/firestore_test.cc
  firestore/integration_test_internal/src/includes_test.cc
  firestore/integration_test_internal/src/integration_test.cc
  firestore/integration_test_internal/src/server_timestamp_test.cc
  firestore/integration_test_internal/src/transaction_extra_test.cc
  firestore/integration_test_internal/src/transaction_test.cc
  firestore/integration_test_internal/src/validation_test.cc
  firestore/src/android/document_reference_android.cc
  firestore/src/android/document_reference_android.h
  firestore/src/android/event_listener_android.h
  firestore/src/android/firestore_android.cc
  firestore/src/android/firestore_android.h
  firestore/src/android/lambda_event_listener.h
  firestore/src/android/lambda_transaction_function.h
  firestore/src/android/listener_registration_android.h
  firestore/src/android/query_android.cc
  firestore/src/android/query_android.h
  firestore/src/android/timestamp_portable.cc
  firestore/src/common/document_reference.cc
  firestore/src/common/event_listener.h
  firestore/src/common/field_path.cc
  firestore/src/common/firestore.cc
  firestore/src/common/query.cc
  firestore/src/include/firebase/firestore.h
  firestore/src/include/firebase/firestore/document_reference.h
  firestore/src/include/firebase/firestore/field_path.h
  firestore/src/include/firebase/firestore/map_field_value.h
  firestore/src/include/firebase/firestore/query.h
  firestore/src/main/firestore_main.h
Labels: cla: yes, tests: succeeded

#493 Address STLPort-specific workarounds
  firestore/src/common/field_value.cc
  firestore/src/common/firestore.cc
  firestore/src/jni/env.cc
  firestore/src/jni/env.h
Labels: cla: yes, tests: succeeded

#513 Remove all the remaining traces of 163140650.
  firestore/src/android/field_value_android.cc
  firestore/src/android/util_android.h
  firestore/src/common/exception_common.h
  firestore/src/common/macros.h
  firestore/src/common/settings.cc
Labels: cla: yes, tests: succeeded

#514 Use std::unique_ptr and std::shared_ptr.
  firestore/integration_test_internal/src/android/promise_android_test.cc
  firestore/integration_test_internal/src/firestore_integration_test.cc
  firestore/integration_test_internal/src/firestore_integration_test.h
  firestore/integration_test_internal/src/firestore_test.cc
  firestore/integration_test_internal/src/jni/env_test.cc
  firestore/src/android/field_value_android.cc
  firestore/src/android/field_value_android.h
  firestore/src/android/firestore_android.cc
  firestore/src/android/firestore_android.h
  firestore/src/android/promise_android.h
  firestore/src/android/transaction_android.cc
  firestore/src/android/transaction_android.h
  firestore/src/common/make_unique.h
  firestore/src/jni/loader.h
Labels: cla: yes, tests: succeeded

#508 Run lint checks on PRs, posting any warnings as comments directly on the files
  .github/workflows/lint.yml
  scripts/gha/lint_commenter.py
Labels: cla: yes

#500 GHA automatically build & test tvOS integration tests on tvOS Simulator
  .github/workflows/integration_tests.yml
  firestore/integration_test_internal/integration_test.xcodeproj/project.pbxproj
  scripts/gha/build_testapps.py
  scripts/gha/integration_testing/build_testapps.json
  scripts/gha/integration_testing/config_reader.py
  scripts/gha/integration_testing/gameloop_android/app/src/androidTest/java/com/google/firebase/gameloop/GameLoopUITest.kt
  scripts/gha/integration_testing/gameloop_apple/gameloopUITests/gameloopUITests.swift
  scripts/gha/integration_testing/xcode_tool.rb
  scripts/gha/integration_testing/xcodebuild.py
  scripts/gha/print_matrix_configuration.py
  scripts/gha/summarize_test_results.py
  scripts/gha/test_lab.py
  scripts/gha/test_simulator.py
Labels: cla: yes, tests: failed

#515 Create a PR template
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: cla: yes

#489 tvOS test script & tool
  .github/workflows/integration_tests.yml
  auth/integration_test/integration_test.xcodeproj/project.pbxproj
  database/integration_test/integration_test.xcodeproj/project.pbxproj
  firestore/integration_test/integration_test.xcodeproj/project.pbxproj
  firestore/integration_test_internal/integration_test.xcodeproj/project.pbxproj
  functions/integration_test/integration_test.xcodeproj/project.pbxproj
  scripts/gha/build_testapps.py
  scripts/gha/integration_testing/build_testapps.json
  scripts/gha/integration_testing/config_reader.py
  scripts/gha/integration_testing/gameloop_android/app/src/androidTest/java/com/google/firebase/gameloop/GameLoopUITest.kt
  scripts/gha/integration_testing/gameloop_apple/gameloop.xcodeproj/project.pbxproj
  scripts/gha/integration_testing/gameloop_apple/gameloop/AppDelegate.swift
  scripts/gha/integration_testing/gameloop_apple/gameloop/Base.lproj/LaunchScreen.storyboard
  scripts/gha/integration_testing/gameloop_apple/gameloop/Base.lproj/Main.storyboard
  scripts/gha/integration_testing/gameloop_apple/gameloop/Constants.swift
  scripts/gha/integration_testing/gameloop_apple/gameloop/Info.plist
  scripts/gha/integration_testing/gameloop_apple/gameloop/ViewController.swift
  scripts/gha/integration_testing/gameloop_apple/gameloopUITests/Info.plist
  scripts/gha/integration_testing/gameloop_apple/gameloopUITests/gameloopUITests.swift
  scripts/gha/integration_testing/gameloop_apple/gameloop_tvos/Base.lproj/LaunchScreen.storyboard
  scripts/gha/integration_testing/gameloop_apple/gameloop_tvos/Base.lproj/Main.storyboard
  scripts/gha/integration_testing/gameloop_ios/gameloop/Assets.xcassets/AccentColor.colorset/Contents.json
  scripts/gha/integration_testing/gameloop_ios/gameloop/Assets.xcassets/AppIcon.appiconset/Contents.json
  scripts/gha/integration_testing/gameloop_ios/gameloop/Assets.xcassets/Contents.json
  scripts/gha/integration_testing/xcode_tool.rb
  scripts/gha/integration_testing/xcodebuild.py
  scripts/gha/print_matrix_configuration.py
  scripts/gha/summarize_test_results.py
  scripts/gha/test_lab.py
  scripts/gha/test_simulator.py
  storage/integration_test/integration_test.xcodeproj/project.pbxproj
Labels: cla: yes

#517 Temporarily disable tvOS integration test against packaged SDK
  scripts/gha/trigger_workflow.py
Labels: cla: yes

#507 Use git apply patch to fix uWebsockets crash, previously fixed by python script in #344
  cmake/external/boringssl.cmake
  cmake/external/uWebSockets.cmake
  cmake/external_rules.cmake
  scripts/git/patches/uWebsockets/0001-fix-want-write-crash.patch
  scripts/patch_websockets.py
Labels: cla: yes

#439 Updated Android Dependency of Flatbuffers from 1.9 to 1.12
  Android/firebase_dependencies.gradle
  messaging/messaging_java/build.gradle
  release_build_files/Android/firebase_dependencies.gradle
  release_build_files/readme.md
  testing/build.gradle
Labels: cla: yes, tests: succeeded

#516 Deflake a few flaky tests
  installations/integration_test/src/integration_test.cc
  messaging/integration_test/src/integration_test.cc
  storage/integration_test/src/integration_test.cc
  testing/test_framework/src/firebase_test_framework.h
Labels: cla: yes, tests: succeeded

#521 Fixed errant uWebSockets git patch path
  scripts/git/patches/uWebSockets/0001-fix-want-write-crash.patch
Labels: cla: yes

#512 Deprecate RunTransaction which takes a TransactionFunction.
  firestore/integration_test_internal/src/includes_test.cc
  firestore/integration_test_internal/src/transaction_extra_test.cc
  firestore/integration_test_internal/src/transaction_test.cc
  firestore/src/include/firebase/firestore.h
Labels: api: firestore, cla: yes

#525 Update iOS and Android dependencies for C++ 8.2.0 release.
  Android/firebase_dependencies.gradle
  analytics/integration_test/Podfile
  app/integration_test/Podfile
  auth/integration_test/Podfile
  cmake/external/firestore.cmake
  cpp_sdk_version.json
  database/integration_test/Podfile
  dynamic_links/integration_test/Podfile
  firestore/firestore_resources/build.gradle
  firestore/integration_test/Podfile
  firestore/integration_test_internal/Podfile
  functions/integration_test/Podfile
  installations/integration_test/Podfile
  ios_pod/Podfile
  messaging/integration_test/Podfile
  release_build_files/Android/firebase_dependencies.gradle
  release_build_files/readme.md
  remote_config/integration_test/Podfile
  storage/integration_test/Podfile
Labels: cla: yes, tests: succeeded

#527 Add retry for brew update in integration test.
  .github/workflows/android.yml
  .github/workflows/cpp-packaging.yml
  .github/workflows/desktop.yml
  .github/workflows/integration_tests.yml
Labels: cla: yes

#524 Fix flaky test
  messaging/integration_test/src/integration_test.cc
  testing/test_framework/src/firebase_test_framework.h
Labels: cla: yes, tests: succeeded

#529 Update FTL test devices
  scripts/gha/print_matrix_configuration.py
Labels: cla: yes

#531 Add flaky test handling for Storage test
  storage/integration_test/src/integration_test.cc
Labels: cla: yes

#528 Add stub test flag for Unity build
  CMakeLists.txt
  cmake/external/CMakeLists.txt
  cmake/external/firebase_ios_sdk.cmake
  cmake/external_rules.cmake
Labels: cla: yes

#519 Remove unused field, since it can cause warnings
  firestore/src/android/load_bundle_task_progress_android.cc
Labels: cla: yes

#532 Test result report missing logs
  .github/workflows/integration_tests.yml
  scripts/gha/summarize_test_results.py
Labels: cla: yes

#533 GitHub REST API: add timeout and retry
  scripts/gha/github.py
  scripts/gha/it_workflow.py
Labels: cla: yes

#534 Clean up flaky tests a bit by adding std::function support to RunWithRetry/RunFlakyBlock.
  analytics/integration_test/src/integration_test.cc
  auth/integration_test/src/integration_test.cc
  messaging/integration_test/src/integration_test.cc
  storage/integration_test/src/integration_test.cc
  testing/test_framework/src/firebase_test_framework.h
Labels: cla: yes

#539 Fix detection of which tests to run when "quick" tests are requested.
  .github/workflows/integration_tests.yml
  scripts/gha/print_matrix_configuration.py
Labels: cla: yes

#522 Add generic PR file comment script, and use it to show docs errors.
  .github/workflows/checks.yml
  docs/Doxyfile
  scripts/gha/pr_file_commenter.py
Labels: cla: yes

#535 Add retry to iOS/tvOS/Android test on virtual device
  scripts/gha/integration_testing/gameloop_android/app/src/androidTest/java/com/google/firebase/gameloop/GameLoopUITest.kt
  scripts/gha/test_simulator.py
Labels: cla: yes

#540 Enable expanded matrix for integration test
  .github/workflows/cpp-packaging.yml
  .github/workflows/integration_tests.yml
  scripts/gha/print_matrix_configuration.py
Labels: cla: yes

#545 Refactor Remote Config deflake to use cleaner std::function version.
  remote_config/integration_test/src/integration_test.cc
Labels: cla: yes, tests: in-progress

#543 Clean up all flaky tests to be much more straightforward.
  analytics/integration_test/src/integration_test.cc
  auth/integration_test/src/integration_test.cc
  installations/integration_test/src/integration_test.cc
  messaging/integration_test/src/integration_test.cc
  storage/integration_test/src/integration_test.cc
  testing/test_framework/src/firebase_test_framework.h
Labels: cla: yes, tests: succeeded

#546 Removed reference to main_for_testing.cc in firestore
  firestore/CMakeLists.txt
  firestore/src/common/main_for_testing_build.cc
Labels: cla: yes, tests: succeeded

#536 Feature/update versions improvements
  scripts/update_android_ios_dependencies.py
Labels: cla: yes

#538 Add a "wrapper" header that includes `firestore_exceptions.h` from the iOS repo
  firestore/CMakeLists.txt
  firestore/src/common/firestore_exceptions_common.h
Labels: api: firestore, cla: yes

#548 Disable test on android min devices
  scripts/gha/print_matrix_configuration.py
Labels: cla: yes

#550 Add flaky retry logic for waiting for token in Messaging.
  messaging/integration_test/src/integration_test.cc
Labels: cla: yes

#551 After a branch is deleted, force quick tests to run the full suite.
  .github/workflows/integration_tests.yml
Labels: cla: yes, tests: succeeded

#547 Fix flaky bundle tests.
  firestore/integration_test_internal/src/bundle_test.cc
Labels: cla: yes, tests: succeeded

#544 Remove the deprecated RunTransaction function
  firestore/src/android/firestore_android.cc
  firestore/src/android/firestore_android.h
  firestore/src/android/lambda_transaction_function.h
  firestore/src/android/transaction_android.h
  firestore/src/common/firestore.cc
  firestore/src/common/transaction_function.h
  firestore/src/include/firebase/firestore.h
  firestore/src/include/firebase/firestore/transaction.h
  firestore/src/main/firestore_main.cc
  firestore/src/main/firestore_main.h
  release_build_files/readme.md
Labels: api: firestore, cla: yes, tests: succeeded

#553 Integration test workflow exclude tvOS build & test for certain apis
  .github/workflows/integration_tests.yml
  scripts/gha/print_matrix_configuration.py
Labels: cla: yes

#554 Remove unnecessary guard around FieldValue::Increment.
  firestore/CMakeLists.txt
  firestore/src/include/firebase/firestore/field_value.h
  release_build_files/readme.md
Labels: cla: yes, tests: succeeded

#557 [Bugfix] Test on Simulator/Emulator crash when missing test log
  scripts/gha/test_simulator.py
Labels: cla: yes

#556 Feature/tvos messaging support
  messaging/integration_test/Podfile
  messaging/integration_test/integration_test.xcodeproj/project.pbxproj
  messaging/integration_test/integration_test_tvos/Base.lproj/LaunchScreen.storyboard
  messaging/integration_test/integration_test_tvos/Base.lproj/Main.storyboard
  messaging/src/ios/messaging.mm
  scripts/gha/build_ios_tvos.py
  scripts/gha/integration_testing/build_testapps.json
Labels: cla: yes, tests: succeeded

#559 Fix ODR violation of FirestoreInternal on Android in integration_test_util.cc
  firestore/integration_test_internal/src/util/integration_test_util.cc
Labels: api: firestore, cla: yes, tests: succeeded

#555 Bugfix/Android emulator test failures
  .github/workflows/integration_tests.yml
  scripts/gha/print_matrix_configuration.py
  scripts/gha/test_simulator.py
Labels: cla: yes

#558 Ensure that argv specified to googletest has a null terminator.
  testing/test_framework/src/firebase_test_framework.cc
Labels: api: firestore, cla: yes, no-lint, tests: succeeded

#562 Fix regex replacement to properly quote meta characters.
  CMakeLists.txt
Labels: cla: yes

#572 On PRs from external users, dismiss stale reviews when a new commit is pushed.
  .github/workflows/checks_secure.yml
  scripts/gha/dismiss_reviews.py
  scripts/gha/github.py
Labels: cla: yes

#511 Make C++ validation tests run on all platforms
  cmake/external/googletest.cmake
  firestore/integration_test_internal/CMakeLists.txt
  firestore/integration_test_internal/src/cleanup_test.cc
  firestore/integration_test_internal/src/firestore_integration_test.cc
  firestore/integration_test_internal/src/firestore_integration_test.h
  firestore/integration_test_internal/src/util/integration_test_util.cc
  firestore/integration_test_internal/src/validation_test.cc
  firestore/src/android/promise_android.h
  firestore/src/common/collection_reference.cc
  firestore/src/common/document_change.cc
  firestore/src/common/document_reference.cc
  firestore/src/common/document_snapshot.cc
  firestore/src/common/field_value.cc
  firestore/src/common/firestore.cc
  firestore/src/common/query.cc
  firestore/src/common/query_snapshot.cc
  firestore/src/common/transaction.cc
  firestore/src/common/write_batch.cc
  firestore/src/main/document_snapshot_main.cc
  firestore/src/main/firestore_main.cc
  firestore/src/main/query_main.cc
  firestore/src/main/transaction_main.cc
  firestore/src/main/transaction_main.h
  release_build_files/readme.md
  testing/test_framework/download_googletest.py
Labels: api: firestore, cla: yes, tests: succeeded

#574 Use requests_retry_session to retry get_reviews/dismiss_review GitHub requests.
  scripts/gha/github.py
Labels: cla: yes

#563 Fix Emulator Error & Add Flake Tracker to nightly notification
  scripts/gha/integration_testing/gameloop_android/app/src/androidTest/java/com/google/firebase/gameloop/GameLoopUITest.kt
  scripts/gha/integration_testing/test_validation.py
  scripts/gha/it_workflow.py
  scripts/gha/test_simulator.py
Labels: cla: yes

#575 Fix a use-after-free bug in BundleTest.CanDeleteFirestoreFromProgressUpdate
  firestore/integration_test_internal/src/bundle_test.cc
Labels: api: firestore, cla: yes, tests: succeeded

#569 Feature/enable tvos packaging
  .github/workflows/cpp-packaging.yml
  CMakeLists.txt
  release_build_files/readme.md
  scripts/gha/build_ios_tvos.py
  scripts/gha/trigger_workflow.py
Labels: cla: yes

#579 Updated dependencies and SDK version
  Android/firebase_dependencies.gradle
  admob/integration_test/Podfile
  analytics/integration_test/Podfile
  app/integration_test/Podfile
  app/invites_resources/build.gradle
  auth/integration_test/Podfile
  cmake/external/firestore.cmake
  cpp_sdk_version.json
  database/database_resources/build.gradle
  database/integration_test/Podfile
  dynamic_links/integration_test/Podfile
  firestore/firestore_resources/build.gradle
  firestore/integration_test/Podfile
  firestore/integration_test_internal/Podfile
  functions/integration_test/Podfile
  installations/integration_test/Podfile
  ios_pod/Podfile
  messaging/integration_test/Podfile
  release_build_files/Android/firebase_dependencies.gradle
  release_build_files/readme.md
  remote_config/integration_test/Podfile
  storage/integration_test/Podfile
Labels: cla: yes, tests: succeeded

#561 Bugfix/app cmake exceptions private
  app/CMakeLists.txt
  app/tests/thread_test.cc
  release_build_files/readme.md
Labels: cla: yes

#576 Reset Android Emulator on test errors
  .github/workflows/integration_tests.yml
  scripts/gha/it_workflow.py
  scripts/gha/test_lab.py
  scripts/gha/test_simulator.py
Labels: cla: yes

#580 Cause Firestore build error if non-Android headers get included in an Android build
  firestore/src/main/collection_reference_main.h
  firestore/src/main/converter_main.h
  firestore/src/main/create_credentials_provider.h
  firestore/src/main/create_firebase_metadata_provider.h
  firestore/src/main/credentials_provider_desktop.h
  firestore/src/main/document_change_main.h
  firestore/src/main/document_reference_main.h
  firestore/src/main/document_snapshot_main.h
  firestore/src/main/field_value_main.h
  firestore/src/main/firebase_metadata_provider_desktop.h
  firestore/src/main/firestore_main.h
  firestore/src/main/listener_main.h
  firestore/src/main/listener_registration_main.h
  firestore/src/main/promise_factory_main.h
  firestore/src/main/promise_main.h
  firestore/src/main/query_main.h
  firestore/src/main/query_snapshot_main.h
  firestore/src/main/set_options_main.h
  firestore/src/main/source_main.h
  firestore/src/main/transaction_main.h
  firestore/src/main/user_data_converter_main.h
  firestore/src/main/util_main.h
  firestore/src/main/write_batch_main.h
Labels: api: firestore, cla: yes, tests: succeeded

#581 Tests against packaged SDK added to Nightly Test Report
  .github/workflows/cpp-packaging.yml
  .github/workflows/integration_tests.yml
  scripts/gha/github.py
  scripts/gha/it_workflow.py
Labels: cla: yes

#585 Fix ReferenceCountedFutureImpl to avoid using FirestoreInternal after its deletion.
  firestore/integration_test_internal/CMakeLists.txt
  firestore/integration_test_internal/src/android/promise_android_test.cc
  firestore/integration_test_internal/src/android/promise_factory_android_test.cc
  firestore/integration_test_internal/src/firestore_test.cc
  firestore/integration_test_internal/src/source_test.cc
  firestore/src/android/firestore_android.h
  firestore/src/android/promise_android.h
  firestore/src/android/promise_factory_android.h
Labels: api: firestore, cla: yes, tests: succeeded

#586 Add firestore/CPPLINT.cfg
  firestore/CPPLINT.cfg
Labels: api: firestore, cla: yes
