Repository firebase/firebase-cpp-sdk, pull requests merged in 2021-11, with the labels that each got.

#717 When downloading external projects, provide GitHub token if available
  README.md
  cmake/external/boringssl.cmake
  cmake/external/curl.cmake
  cmake/external/firebase_ios_sdk.cmake
  cmake/external/firestore.cmake
  cmake/external/flatbuffers.cmake
  cmake/external/googletest.cmake
  cmake/external/leveldb.cmake
  cmake/external/libuv.cmake
  cmake/external/nanopb.cmake
  cmake/external/uWebSockets.cmake
  cmake/external/zlib.cmake
  cmake/external_rules.cmake
Labels: cla: yes, tests: failed, skip-release-notes

#715 Analytics tvOS support.
  CMakeLists.txt
  analytics/integration_test/Podfile
  analytics/integration_test/integration_test.xcodeproj/project.pbxproj
  analytics/integration_test/integration_test_tvos/Base.lproj/LaunchScreen.storyboard
  analytics/integration_test/integration_test_tvos/Base.lproj/Main.storyboard
  release_build_files/readme.md
  scripts/gha/build_ios_tvos.py
  scripts/gha/integration_testing/build_testapps.json
Labels: cla: yes

#719 Update C++ SDK version to 8.7.0.
  cpp_sdk_version.json
  release_build_files/readme.md
Labels: cla: yes

#720 Add 8.7.0 release notes entries for Firestore
  release_build_files/readme.md
Labels: cla: yes

#725 Fix script to use Firebase/ subspecs.
  scripts/update_android_ios_dependencies.py
Labels: cla: yes, skip-release-notes

#727 Add GitHub token to saved credentials to avoid throttling.
  .github/workflows/android.yml
  .github/workflows/cpp-packaging.yml
  .github/workflows/desktop.yml
  .github/workflows/integration_tests.yml
  .github/workflows/ios.yml
Labels: cla: yes, skip-release-notes

#735 Ad Clicked fix, Android link error.
  admob/admob_resources/build.gradle
  admob/src_java/com/google/firebase/admob/internal/cpp/InterstitialAdHelper.java
  release_build_files/Android/firebase_dependencies.gradle
Labels: cla: yes

#738 Override ResponseJson::MarkFailed to set application_data_.
  app/rest/response_json.h
  release_build_files/readme.md
Labels: cla: yes

#739 Fix crash in Messaging on Android when Terminate is called while tasks are still pending.
  messaging/src/android/cpp/messaging.cc
  release_build_files/readme.md
Labels: cla: yes, skip-release-notes

#736 Fix app build for Android against prebuilt version
  app/src/include/google_play_services/availability.h
Labels: cla: yes, skip-release-notes

#713 Feature/admob 2021 adview, fullscreen listeners
  Android/firebase_dependencies.gradle
  admob/admob_resources/build.gradle
  admob/integration_test/src/integration_test.cc
  admob/src/android/admob_android.cc
  admob/src/android/admob_android.h
  admob/src/android/banner_view_internal_android.cc
  admob/src/android/banner_view_internal_android.h
  admob/src/android/interstitial_ad_internal_android.cc
  admob/src/android/interstitial_ad_internal_android.h
  admob/src/common/admob_common.cc
  admob/src/common/admob_common.h
  admob/src/common/banner_view.cc
  admob/src/common/banner_view_internal.cc
  admob/src/common/banner_view_internal.h
  admob/src/common/interstitial_ad.cc
  admob/src/common/interstitial_ad_internal.cc
  admob/src/common/interstitial_ad_internal.h
  admob/src/include/firebase/admob/banner_view.h
  admob/src/include/firebase/admob/interstitial_ad.h
  admob/src/include/firebase/admob/types.h
  admob/src/ios/FADBannerView.h
  admob/src/ios/FADBannerView.mm
  admob/src/ios/FADInterstitialDelegate.mm
  admob/src/ios/FADRequest.h
  admob/src/ios/FADRequest.mm
  admob/src/ios/ad_result_ios.mm
  admob/src/ios/adapter_response_info_ios.mm
  admob/src/ios/admob_ios.h
  admob/src/ios/admob_ios.mm
  admob/src/ios/banner_view_internal_ios.h
  admob/src/ios/banner_view_internal_ios.mm
  admob/src/ios/interstitial_ad_internal_ios.h
  admob/src/ios/interstitial_ad_internal_ios.mm
  admob/src/stub/banner_view_internal_stub.h
  admob/src/stub/interstitial_ad_internal_stub.h
  admob/src_java/com/google/firebase/admob/internal/cpp/BannerViewHelper.java
  admob/src_java/com/google/firebase/admob/internal/cpp/ConstantsHelper.java
  admob/src_java/com/google/firebase/admob/internal/cpp/InterstitialAdHelper.java
  release_build_files/Android/firebase_dependencies.gradle
Labels: cla: yes

#723 Remove LoadAdResult from new Admob.
  admob/CMakeLists.txt
  admob/integration_test/src/integration_test.cc
  admob/src/android/ad_result_android.cc
  admob/src/android/ad_result_android.h
  admob/src/android/adapter_response_info_android.cc
  admob/src/android/admob_android.cc
  admob/src/android/banner_view_internal_android.cc
  admob/src/android/banner_view_internal_android.h
  admob/src/android/interstitial_ad_internal_android.cc
  admob/src/android/interstitial_ad_internal_android.h
  admob/src/android/load_ad_result_android.cc
  admob/src/common/admob_common.cc
  admob/src/common/admob_common.h
  admob/src/common/banner_view.cc
  admob/src/common/banner_view_internal.cc
  admob/src/common/banner_view_internal.h
  admob/src/common/interstitial_ad.cc
  admob/src/common/interstitial_ad_internal.cc
  admob/src/common/interstitial_ad_internal.h
  admob/src/include/firebase/admob/banner_view.h
  admob/src/include/firebase/admob/interstitial_ad.h
  admob/src/include/firebase/admob/types.h
  admob/src/ios/ad_result_ios.h
  admob/src/ios/ad_result_ios.mm
  admob/src/ios/admob_ios.h
  admob/src/ios/admob_ios.mm
  admob/src/ios/banner_view_internal_ios.h
  admob/src/ios/banner_view_internal_ios.mm
  admob/src/ios/interstitial_ad_internal_ios.h
  admob/src/ios/interstitial_ad_internal_ios.mm
  admob/src/ios/load_ad_result_ios.mm
  admob/src/stub/ad_result_stub.cc
  admob/src/stub/banner_view_internal_stub.h
  admob/src/stub/interstitial_ad_internal_stub.h
  admob/src/stub/load_ad_result_stub.cc
  admob/src_java/com/google/firebase/admob/internal/cpp/InterstitialAdHelper.java
Labels: cla: yes

#734 Fix test on emulator workflow failures
  .github/workflows/integration_tests.yml
  scripts/gha/integration_testing/gameloop_android/build.gradle
  scripts/gha/test_simulator.py
Labels: cla: yes, skip-release-notes

#742 Return AdapterInitializationStatus from Initialize
  admob/integration_test/src/integration_test.cc
  admob/src/android/admob_android.cc
  admob/src/android/admob_android.h
  admob/src/common/admob_common.cc
  admob/src/common/admob_common.h
  admob/src/include/firebase/admob.h
  admob/src/include/firebase/admob/types.h
  admob/src/ios/admob_ios.mm
  admob/src/stub/ad_result_stub.cc
  admob/src/stub/admob_stub.cc
  admob/src_java/com/google/firebase/admob/internal/cpp/AdMobInitializationHelper.java
  app/src/util_android.cc
  app/src/util_android.h
Labels: cla: yes

#733 If simulator install ios app failed, reset simulator and try again
  scripts/gha/test_simulator.py
Labels: cla: yes, skip-release-notes

#746 Trigger workflow move github api cod to github.py
  .github/workflows/cpp-packaging.yml
  scripts/gha/github.py
  scripts/gha/trigger_workflow.py
Labels: cla: yes, tests: succeeded, skip-release-notes

#747 Fix a data race that could manifest as null pointer dereference in FutureBase::Release()
  app/src/include/firebase/future.h
  app/src/include/firebase/internal/future_impl.h
  release_build_files/readme.md
Labels: api: firestore, cla: yes, tests: succeeded

#744 Guard against Banner/Interstitial use of nullptr callbacks
  admob/src_java/com/google/firebase/admob/internal/cpp/BannerViewHelper.java
  admob/src_java/com/google/firebase/admob/internal/cpp/InterstitialAdHelper.java
Labels: cla: yes

#745 Cancel callbacks for messaging
  messaging/src/android/cpp/messaging.cc
  release_build_files/readme.md
Labels: cla: yes

#749 Remove "Android" tag from the release notes entry for #747
  release_build_files/readme.md
Labels: cla: yes

#706 Remove calls to LogInfo, LogError, LogDebug during obj-c +load.
  app/src/util_ios.mm
  messaging/src/ios/messaging.mm
Labels: cla: yes, tests: succeeded, skip-release-notes

#754 Rename Admob LeaderBoard AdSize to Leaderboard
  admob/integration_test/src/integration_test.cc
  admob/src/common/admob_common.cc
  admob/src/include/firebase/admob/types.h
Labels: cla: yes

#752 AdMob Rewarded Ads on iOS
  admob/CMakeLists.txt
  admob/integration_test/src/integration_test.cc
  admob/src/ios/FADRewardedAdDelegate.h
  admob/src/ios/FADRewardedAdDelegate.mm
  admob/src/ios/rewarded_ad_internal_ios.h
  admob/src/ios/rewarded_ad_internal_ios.mm
Labels: cla: yes

#760 Messaging crash during initialization
  messaging/src/android/cpp/messaging.cc
  release_build_files/readme.md
Labels: cla: yes

#762 Feature/admob 2021 stability in future usage
  admob/integration_test/src/integration_test.cc
  admob/src/android/banner_view_internal_android.cc
  admob/src/android/banner_view_internal_android.h
  admob/src/android/interstitial_ad_internal_android.cc
  admob/src/android/rewarded_ad_internal_android.cc
  admob/src/common/admob_common.cc
  admob/src/ios/banner_view_internal_ios.mm
  admob/src/ios/interstitial_ad_internal_ios.mm
  admob/src/ios/rewarded_ad_internal_ios.mm
  admob/src_java/com/google/firebase/admob/internal/cpp/BannerViewHelper.java
Labels: cla: yes

#731 Don't redeclare inherited state in CredentialsProviderDesktop
  firestore/src/main/credentials_provider_desktop.cc
  firestore/src/main/credentials_provider_desktop.h
Labels: cla: yes, tests: succeeded, skip-release-notes

#763 Reduce disk space usage when packaging the built SDK
  .github/workflows/cpp-packaging.yml
Labels: cla: yes

#764 Workaround for Linux x86 build: downgrade libraries on GitHub runners
  scripts/gha/build_desktop.py
Labels: cla: yes, tests: succeeded, skip-release-notes

#768 Fix link in readme
  README.md
Labels: cla: yes

#757 Update FTL devices to run tests
  scripts/gha/print_matrix_configuration.py
Labels: cla: yes
