Repository firebase/firebase-cpp-sdk, pull requests merged in 2022-03, with the labels that each got.

#824 Added logic to retry transient failures for all operations in desktop storage implementation.
  release_build_files/readme.md
  storage/integration_test/src/integration_test.cc
  storage/src/desktop/storage_reference_desktop.cc
  storage/src/desktop/storage_reference_desktop.h
Labels: tests: succeeded

#853 Heartbeat logging passthrough for FIS for mobile platforms.
  installations/src/android/installations_android.cc
  installations/src/android/installations_android.h
  installations/src/installations.cc
  installations/src/ios/installations_ios.h
  installations/src/ios/installations_ios.mm
  installations/src/stub/installations_stub.cc
  installations/src/stub/installations_stub.h
Labels: skip-release-notes

#862 Fix Linux x86 package installation on GH runners
  scripts/gha/build_desktop.py
Labels: skip-release-notes

#861 Don't report test error if it's indeed build errors
  .github/workflows/cpp-packaging.yml
  .github/workflows/integration_tests.yml
Labels: skip-release-notes

#865 Revert "Change workaround"
  scripts/gha/build_desktop.py
Labels: tests: succeeded, skip-release-notes

#867 Cancel workflows for previous commits in a PR when new commits are pushed
  .github/workflows/android.yml
  .github/workflows/checks.yml
  .github/workflows/checks_secure.yml
  .github/workflows/desktop.yml
  .github/workflows/ios.yml
  .github/workflows/lint.yml
Labels: skip-release-notes

#868 iOS: remove desktop sources that were mistakenly merged into app/CMakeLists.txt
  app/CMakeLists.txt
Labels: type: bug, tests: succeeded
