Repository firebase/firebase-cpp-sdk, pull requests merged in 2022-09, with the labels that each got.

#1065 Add heartbeat payload as a header to auth requests
  app/src/app_common.cc
  app/src/app_common.h
  auth/src/desktop/auth_desktop.cc
  auth/src/desktop/auth_providers/facebook_auth_credential.h
  auth/src/desktop/auth_providers/github_auth_credential.h
  auth/src/desktop/auth_providers/google_auth_credential.h
  auth/src/desktop/auth_providers/oauth_auth_credential.h
  auth/src/desktop/auth_providers/playgames_auth_credential.h
  auth/src/desktop/auth_providers/twitter_auth_credential.h
  auth/src/desktop/credential_util.cc
  auth/src/desktop/identity_provider_credential.h
  auth/src/desktop/rpcs/auth_request.cc
  auth/src/desktop/rpcs/auth_request.h
  auth/src/desktop/rpcs/create_auth_uri_request.cc
  auth/src/desktop/rpcs/create_auth_uri_request.h
  auth/src/desktop/rpcs/delete_account_request.cc
  auth/src/desktop/rpcs/delete_account_request.h
  auth/src/desktop/rpcs/get_account_info_request.cc
  auth/src/desktop/rpcs/get_account_info_request.h
  auth/src/desktop/rpcs/get_oob_confirmation_code_request.cc
  auth/src/desktop/rpcs/get_oob_confirmation_code_request.h
  auth/src/desktop/rpcs/reset_password_request.cc
  auth/src/desktop/rpcs/reset_password_request.h
  auth/src/desktop/rpcs/secure_token_request.cc
  auth/src/desktop/rpcs/secure_token_request.h
  auth/src/desktop/rpcs/set_account_info_request.cc
  auth/src/desktop/rpcs/set_account_info_request.h
  auth/src/desktop/rpcs/sign_up_new_user_request.cc
  auth/src/desktop/rpcs/sign_up_new_user_request.h
  auth/src/desktop/rpcs/verify_assertion_request.cc
  auth/src/desktop/rpcs/verify_assertion_request.h
  auth/src/desktop/rpcs/verify_custom_token_request.cc
  auth/src/desktop/rpcs/verify_custom_token_request.h
  auth/src/desktop/rpcs/verify_password_request.cc
  auth/src/desktop/rpcs/verify_password_request.h
  auth/src/desktop/sign_in_flow.cc
  auth/src/desktop/user_desktop.cc
  auth/tests/CMakeLists.txt
  auth/tests/desktop/auth_desktop_test.cc
  auth/tests/desktop/rpcs/auth_request_heartbeat_test.cc
  auth/tests/desktop/rpcs/create_auth_uri_test.cc
  auth/tests/desktop/rpcs/delete_account_test.cc
  auth/tests/desktop/rpcs/get_account_info_test.cc
  auth/tests/desktop/rpcs/get_oob_confirmation_code_test.cc
  auth/tests/desktop/rpcs/reset_password_test.cc
  auth/tests/desktop/rpcs/secure_token_test.cc
  auth/tests/desktop/rpcs/set_account_info_test.cc
  auth/tests/desktop/rpcs/sign_up_new_user_test.cc
  auth/tests/desktop/rpcs/test_util.cc
  auth/tests/desktop/rpcs/verify_assertion_test.cc
  auth/tests/desktop/rpcs/verify_custom_token_test.cc
  auth/tests/desktop/rpcs/verify_password_test.cc
Labels: tests: succeeded

#1060 Replace the FTL test script with FTL GHA
  .github/workflows/integration_tests.yml
  scripts/gha/integration_testing/ftl_gha_validator.py
  scripts/gha/print_matrix_configuration.py
  scripts/gha/read_ftl_test_result.py
  scripts/gha/test_lab.py
Labels: tests: succeeded, skip-release-notes

#1080 Remove vcpkg from testapp builder
  scripts/gha/build_testapps.py
Labels: skip-release-notes

#1077 Ignore Android native build folder
  .gitignore
Labels: skip-release-notes

#1086 Use aptitude for Ubuntu 86 dependencies
  scripts/gha/utils.py
Labels: skip-release-notes

#1081 Remove `brew update`
  scripts/gha/install_test_workflow_prereqs.sh
Labels: skip-release-notes

#1083 Add initial App Check headers and stubs
  CMakeLists.txt
  app_check/CMakeLists.txt
  app_check/build.gradle
  app_check/src/android/app_check_android.cc
  app_check/src/android/app_check_android.h
  app_check/src/common/app_check.cc
  app_check/src/common/common.h
  app_check/src/desktop/app_check_desktop.cc
  app_check/src/desktop/app_check_desktop.h
  app_check/src/include/firebase/app_check.h
  app_check/src/include/firebase/app_check/app_attest_provider.h
  app_check/src/include/firebase/app_check/debug_provider.h
  app_check/src/include/firebase/app_check/device_check_provider.h
  app_check/src/include/firebase/app_check/play_integrity_provider.h
  app_check/src/include/firebase/app_check/safety_net_provider.h
  app_check/src/ios/app_check_ios.h
  app_check/src/ios/app_check_ios.mm
  settings.gradle
Labels: skip-release-notes

#1088 Fix integration test build on heartbeat branch
  app/src/include/firebase/app.h
Labels: tests: in-progress, tests: failed

#1092 Make the ios tvos packaging use the product list
  build_scripts/ios/package.sh
  build_scripts/tvos/package.sh
Labels: skip-release-notes

#1093 Add stubs for the App Check providers
  app_check/CMakeLists.txt
  app_check/src/android/debug_provider_android.cc
  app_check/src/android/play_integrity_provider_android.cc
  app_check/src/android/safety_net_provider_android.cc
  app_check/src/desktop/debug_provider_desktop.cc
  app_check/src/include/firebase/app_check/app_attest_provider.h
  app_check/src/include/firebase/app_check/debug_provider.h
  app_check/src/include/firebase/app_check/device_check_provider.h
  app_check/src/include/firebase/app_check/play_integrity_provider.h
  app_check/src/include/firebase/app_check/safety_net_provider.h
  app_check/src/ios/app_attest_provider_ios.mm
  app_check/src/ios/debug_provider_ios.mm
  app_check/src/ios/device_check_provider_ios.mm
  app_check/src/stub/app_attest_provider_stub.cc
  app_check/src/stub/device_check_provider_stub.cc
  app_check/src/stub/play_integrity_provider_stub.cc
  app_check/src/stub/safety_net_provider_stub.cc
Labels: skip-release-notes
