Repository firebase/firebase-cpp-sdk, pull requests merged in 2022-05, with the labels that each got.

#889 Remove gnustl support and update NDK
  .github/workflows/android.yml
  .github/workflows/cpp-packaging.yml
  .github/workflows/integration_tests.yml
  CMakeLists.txt
  admob/build.gradle
  analytics/build.gradle
  app/build.gradle
  app/src/include/firebase/app.h
  auth/build.gradle
  build_scripts/android/build.sh
  build_scripts/android/install_prereqs.sh
  build_scripts/android/package.sh
  build_scripts/desktop/get_variant.sh
  database/build.gradle
  dynamic_links/build.gradle
  firestore/build.gradle
  functions/build.gradle
  installations/build.gradle
  messaging/build.gradle
  release_build_files/CMakeLists.txt
  release_build_files/readme.md
  remote_config/build.gradle
  storage/build.gradle
Labels: tests: succeeded

#917 Change macos runners to macos-12. (requires updating xcode to 13.1)
  .github/workflows/android.yml
  .github/workflows/cpp-packaging.yml
  .github/workflows/desktop.yml
  .github/workflows/integration_tests.yml
  .github/workflows/ios.yml
  .github/workflows/update-dependencies.yml
  scripts/gha/print_matrix_configuration.py
Labels: tests: succeeded, skip-release-notes

#920 Update linter to allow non-const references to match more recent goog…
  scripts/gha/lint_commenter.py
Labels: skip-release-notes

#924 update gradle version
  admob/integration_test/gradle/wrapper/gradle-wrapper.properties
  analytics/integration_test/gradle/wrapper/gradle-wrapper.properties
  app/integration_test/gradle/wrapper/gradle-wrapper.properties
  auth/integration_test/gradle/wrapper/gradle-wrapper.properties
  database/integration_test/gradle/wrapper/gradle-wrapper.properties
  dynamic_links/integration_test/gradle/wrapper/gradle-wrapper.properties
  firestore/integration_test/gradle/wrapper/gradle-wrapper.properties
  firestore/integration_test_internal/gradle/wrapper/gradle-wrapper.properties
  functions/integration_test/gradle/wrapper/gradle-wrapper.properties
  gradle/wrapper/gradle-wrapper.properties
  installations/integration_test/gradle/wrapper/gradle-wrapper.properties
  messaging/integration_test/gradle/wrapper/gradle-wrapper.properties
  remote_config/integration_test/gradle/wrapper/gradle-wrapper.properties
  scripts/gha/integration_testing/gameloop_android/gradle/wrapper/gradle-wrapper.properties
  storage/integration_test/gradle/wrapper/gradle-wrapper.properties
Labels: tests: succeeded, skip-release-notes

#922 Use build OS variables instead of hard coded build OS names
  .github/workflows/integration_tests.yml
  scripts/gha/print_matrix_configuration.py
Labels: skip-release-notes

#933 Pass in -j N to cmake to speed up desktop testapp build.
  scripts/gha/build_testapps.py
Labels: tests: succeeded, skip-release-notes

#938 Replace jcenter(), long deprecated, with mavenCentral().
  admob/admob_resources/build.gradle
  admob/build.gradle
  admob/integration_test/build.gradle
  analytics/build.gradle
  analytics/integration_test/build.gradle
  app/app_resources/build.gradle
  app/build.gradle
  app/google_api_resources/build.gradle
  app/integration_test/build.gradle
  app/invites_resources/build.gradle
  app/test_resources/build.gradle
  auth/auth_resources/build.gradle
  auth/build.gradle
  auth/integration_test/build.gradle
  database/build.gradle
  database/database_resources/build.gradle
  database/integration_test/build.gradle
  dynamic_links/build.gradle
  dynamic_links/integration_test/build.gradle
  firestore/build.gradle
  firestore/firestore_resources/build.gradle
  firestore/integration_test/build.gradle
  firestore/integration_test_internal/build.gradle
  functions/build.gradle
  functions/integration_test/build.gradle
  installations/build.gradle
  installations/integration_test/build.gradle
  messaging/build.gradle
  messaging/integration_test/build.gradle
  messaging/messaging_java/build.gradle
  remote_config/build.gradle
  remote_config/integration_test/build.gradle
  scripts/gha/integration_testing/gameloop_android/build.gradle
  storage/build.gradle
  storage/integration_test/build.gradle
  storage/storage_resources/build.gradle
  testing/build.gradle
Labels: tests: succeeded, skip-release-notes

#940 Fix building integration tests against packaged SDK on Linux x86
  release_build_files/CMakeLists.txt
Labels: skip-release-notes

#936 Update simulator min version
  scripts/gha/print_matrix_configuration.py
Labels: tests: succeeded, skip-release-notes

#944 Update C++ SDK version number to 9.0.0
  cpp_sdk_version.json
Labels: skip-release-notes

#945 Move x86 Linux setup to prereqs script
  .github/workflows/cpp-packaging.yml
  .github/workflows/desktop.yml
  .github/workflows/integration_tests.yml
  scripts/gha/build_desktop.py
  scripts/gha/install_prereqs_desktop.py
  scripts/gha/utils.py
Labels: tests: succeeded, skip-release-notes

#931 Add architectures to desktop integration test matrix, and enable arm64/x86 tests.
  .github/workflows/integration_tests.yml
  scripts/gha/build_desktop.py
  scripts/gha/build_testapps.py
  scripts/gha/desktop_tester.py
  scripts/gha/print_matrix_configuration.py
Labels: tests: succeeded, skip-release-notes

#953 Handle jniresultcallback not loading due to lack of gms.Task.
  Android/firebase_dependencies.gradle
  admob/integration_test/build.gradle
  app/src/app_android.cc
  app/src/util.cc
  app/src/util_android.cc
  release_build_files/Android/firebase_dependencies.gradle
  release_build_files/readme.md
  remote_config/integration_test/build.gradle
Labels: tests: succeeded

#956 Fix Windows boringssl build by disabling warning 4191.
  cmake/external/boringssl.cmake
  scripts/git/patches/boringssl/0001-disable-warnings.patch
Labels: tests: succeeded, skip-release-notes

#957 Propagate the Position Independent Code flag
  cmake/external_rules.cmake
Labels: skip-release-notes

#960 Handle Access Denied error when cleaning up build directory on Windows
  scripts/gha/build_testapps.py
Labels: tests: succeeded, skip-release-notes

#962 Update the nodejs version to 14, for Firebase CLI
  .github/workflows/desktop.yml
  .github/workflows/integration_tests.yml
Labels: tests: failed, skip-release-notes

#963 Update GHA CI Java Version
  .github/workflows/desktop.yml
  .github/workflows/integration_tests.yml
Labels: skip-release-notes

#975 Run setup-java for Firestore emulator in GitHub Actions
  .github/workflows/integration_tests.yml
Labels: api: firestore, tests: succeeded, skip-release-notes

#976 leveldb.cmake: add URL_HASH to improve security
  cmake/external/leveldb.cmake
Labels: api: firestore, tests: succeeded, skip-release-notes
