Repository firebase/firebase-cpp-sdk, pull requests merged in 2022-08, with the labels that each got.

#1042 time.h: fix integer overflow in MsToAbsoluteTimespec() on 32-bit architectures
  app/src/time.h
  app/tests/time_test.cc
  release_build_files/readme.md
Labels: tests: succeeded

#1044 pthread_condvar.h: Fix ConditionVariable::TimedWait() on 32-bit platforms
  app/src/pthread_condvar.h
  app/src/time.h
  app/tests/time_test.cc
Labels: tests: succeeded, skip-release-notes

#1047 Firestore: write_batch_test.cc: clean up assertion checks
  firestore/integration_test_internal/src/write_batch_test.cc
Labels: api: firestore, tests: succeeded, skip-release-notes

#1054 Add [C++] description to the nightly test report
  scripts/gha/it_workflow.py
Labels: skip-release-notes

#1052 firestore_test.cc: add assertions for snapshots existing
  firestore/integration_test_internal/src/firestore_test.cc
Labels: api: firestore, tests: succeeded, skip-release-notes

#1055 Send App Id when Firestore SDK delivers heartbeat
  firestore/src/main/create_firebase_metadata_provider_desktop.cc
  firestore/src/main/firebase_metadata_provider_desktop.cc
  firestore/src/main/firebase_metadata_provider_desktop.h
Labels: cla: yes, tests: succeeded, skip-release-notes

#1051 Firestore: Add SCOPED_TRACE to Await() calls in firestore_integration_test.h/cc
  firestore/integration_test_internal/src/firestore_integration_test.cc
  firestore/integration_test_internal/src/firestore_integration_test.h
Labels: api: firestore, tests: succeeded, skip-release-notes

#1057 Include logcat for failed Android emulator tests
  .github/workflows/integration_tests.yml
  scripts/gha/test_simulator.py
Labels: skip-release-notes

#1058 Fix Android and iOS emulator screen recording in GitHub Actions
  .github/workflows/integration_tests.yml
  scripts/gha/test_simulator.py
Labels: skip-release-notes

#1059 Add retry to npm installation of firebase-tools
  .github/workflows/desktop.yml
  .github/workflows/integration_tests.yml
Labels: skip-release-notes

#1063 Update Android Emulators
  scripts/gha/print_matrix_configuration.py
  scripts/gha/test_simulator.py
Labels: skip-release-notes

#1066 Updated link to Python documentation
  README.md
Labels: skip-release-notes

#1064 Upgrade node-version to 16 (was 14) in GitHub Actions workflows
  .github/workflows/desktop.yml
  .github/workflows/integration_tests.yml
Labels: api: firestore, skip-release-notes
