Repository firebase/firebase-cpp-sdk, pull requests merged in 2022-11, with the labels that each got.

#1132 Update gma to use mavenCentral
  gma/build.gradle
  gma/gma_resources/build.gradle
  gma/integration_test/build.gradle
  scripts/gha/ui_testing/uitest_android/build.gradle
Labels: skip-release-notes

#1133 Fix toolchain selection and packages on linux x86
  cmake/toolchains/linux_32.cmake
  release_build_files/readme.md
  scripts/gha/build_desktop.py
  scripts/gha/build_testapps.py
  scripts/gha/utils.py
Labels: tests: succeeded

#1139 Use the new linux32 logic when building the testapps from source
  scripts/gha/build_testapps.py
Labels: skip-release-notes

#1138 Use FTL Virtual Android devices to run tests
  .github/workflows/integration_tests.yml
  scripts/gha/print_matrix_configuration.py
  scripts/gha/summarize_test_results.py
Labels: skip-release-notes

#1136 Pin to a version of iOS with nanopb fix
  cmake/external/firestore.cmake
  firestore/src/main/query_main.cc
Labels: tests: succeeded, skip-release-notes

#1141 Disable GMA stress tests on iOS in CI to limit ad pool exhaustion errors
  gma/integration_test/src/integration_test.cc
Labels: skip-release-notes

#1142 Disable failing Messaging tests in our Android CI
  messaging/integration_test/src/integration_test.cc
Labels: skip-release-notes

#1143 Remove Firestore Emulator initilaization in CI
  .github/workflows/integration_tests.yml
Labels: skip-release-notes

#1144 integration_tests.yml: remove unnecessary node setup
  .github/workflows/integration_tests.yml
Labels: api: firestore, tests: succeeded, skip-release-notes

#1140 Firestore improve cmake file error message
  admob/integration_test/CMakeLists.txt
  analytics/integration_test/CMakeLists.txt
  app/integration_test/CMakeLists.txt
  app_check/integration_test/CMakeLists.txt
  auth/integration_test/CMakeLists.txt
  database/integration_test/CMakeLists.txt
  dynamic_links/integration_test/CMakeLists.txt
  firestore/integration_test/CMakeLists.txt
  firestore/integration_test_internal/CMakeLists.txt
  functions/integration_test/CMakeLists.txt
  gma/integration_test/CMakeLists.txt
  installations/integration_test/CMakeLists.txt
  messaging/integration_test/CMakeLists.txt
  remote_config/integration_test/CMakeLists.txt
  storage/integration_test/CMakeLists.txt
Labels: api: firestore, tests: succeeded, skip-release-notes

#1151 On Linux, install and use GCC 10 if currently not using 9 or 10.
  scripts/gha/install_prereqs_desktop.py
Labels: tests: succeeded, skip-release-notes

#1153 Fix Storage test errors on iOS.
  storage/integration_test/src/integration_test.cc
Labels: tests: succeeded, skip-release-notes

#1155 Replace OrderByList by std::vector<OrderBy> and Skip nested structure inside IN filter test case
  firestore/integration_test_internal/src/query_test.cc
  firestore/src/main/query_main.cc
Labels: tests: succeeded, tests: failed, skip-release-notes

#1156 Use find_program to get python in cmake
  CMakeLists.txt
Labels: tests: succeeded, skip-release-notes

#1158 Remove Strawberry Perl as part of GHA setup
  scripts/gha/install_prereqs_desktop.py
Labels: tests: succeeded, skip-release-notes
