Repository firebase/firebase-cpp-sdk, pull requests merged in 2022-12, with the labels that each got.

#1159 Ignore C5264 ('const' variable is not used) warning in boringssl.
  scripts/git/patches/boringssl/0001-disable-warnings.patch
Labels: skip-release-notes

#1149 Implement main App Check classes for iOS
  app/src/app_ios.h
  app/src/app_ios.mm
  app_check/integration_test/src/integration_test.cc
  app_check/src/ios/app_check_ios.h
  app_check/src/ios/app_check_ios.mm
  app_check/src/ios/util_ios.h
  app_check/src/ios/util_ios.mm
Labels: tests: succeeded, skip-release-notes

#1160 Update integration tests to find python smarter
  admob/integration_test/CMakeLists.txt
  analytics/integration_test/CMakeLists.txt
  app/integration_test/CMakeLists.txt
  app_check/integration_test/CMakeLists.txt
  auth/integration_test/CMakeLists.txt
  database/integration_test/CMakeLists.txt
  dynamic_links/integration_test/CMakeLists.txt
  firestore/integration_test/CMakeLists.txt
  firestore/integration_test_internal/CMakeLists.txt
  functions/integration_test/CMakeLists.txt
  gma/integration_test/CMakeLists.txt
  installations/integration_test/CMakeLists.txt
  messaging/integration_test/CMakeLists.txt
  remote_config/integration_test/CMakeLists.txt
  storage/integration_test/CMakeLists.txt
Labels: tests: succeeded, skip-release-notes

#1150 Android emulator detection, and a few test fixes
  auth/integration_test/src/integration_test.cc
  database/integration_test/src/integration_test.cc
  gma/integration_test/src/integration_test.cc
  messaging/integration_test/src/integration_test.cc
  scripts/gha/print_matrix_configuration.py
  storage/integration_test/src/integration_test.cc
  testing/test_framework/src/android/android_firebase_test_framework.cc
  testing/test_framework/src/android/java/com/google/firebase/example/TestHelper.java
  testing/test_framework/src/desktop/desktop_firebase_test_framework.cc
  testing/test_framework/src/firebase_test_framework.h
  testing/test_framework/src/ios/ios_firebase_test_framework.mm
Labels: tests: succeeded, skip-release-notes

#1163 Fix for unresolved symbol IsRunningOnEmulator
  gma/integration_test/CMakeLists.txt
Labels: tests: succeeded, skip-release-notes

#1164 Patch sprintf in uWebsockets to use snprintf
  cmake/external/uWebSockets.cmake
  scripts/git/patches/uWebSockets/0001-fix-want-write-and-sprintf-deprecation.patch
Labels: skip-release-notes

#1113 Firestore build and testing improvements and documentation
  .gitignore
  firestore/CONTRIBUTING.md
  firestore/README.md
  firestore/architecture.png
  firestore/edit_ios_scheme_firestore_emulator.png
  firestore/integration_test_internal/CMakeLists.txt
  firestore/integration_test_internal/integration_test.xcodeproj/project.pbxproj
  firestore/integration_test_internal/prepare_xcworkspace.sh
  firestore/integration_test_internal/src/firestore_integration_test.cc
  firestore/integration_test_internal/src/integration_test.cc
  firestore/integration_test_internal/src/util/locate_emulator.cc
  firestore/integration_test_internal/src/util/locate_emulator.h
Labels: skip-release-notes

#1161 Feature: Analytics SetConsent function.
  analytics/integration_test/src/integration_test.cc
  analytics/src/analytics_android.cc
  analytics/src/analytics_ios.mm
  analytics/src/analytics_stub.cc
  analytics/src/include/firebase/analytics.h
  release_build_files/readme.md
Labels: tests: succeeded

#1173 Exempt from go/allstar check
  .allstar/binary_artifacts.yaml
Labels: skip-release-notes

#1172 Token-changed listeners for iOS AppCheck
  app_check/integration_test/src/integration_test.cc
  app_check/src/include/firebase/app_check.h
  app_check/src/ios/app_check_ios.h
  app_check/src/ios/app_check_ios.mm
Labels: skip-release-notes

#1162 Setup Desktop test workflow that detects C++ SDK breakage caused by iOS SDK changes
  .github/workflows/integration_tests.yml
  scripts/gha/build_desktop.py
  scripts/gha/it_workflow.py
Labels: skip-release-notes
