Repository firebase/firebase-cpp-sdk, pull requests merged in 2022-10, with the labels that each got.

#1099 Add missing virtual destructors for App Check
  app_check/src/common/app_check.cc
  app_check/src/include/firebase/app_check.h
Labels: skip-release-notes

#1110 remove @ref after @deprecated to bypass devsite check
  auth/src/include/firebase/auth/credential.h
Labels: skip-release-notes

#1098 Add an initial version of App Check integration test
  Android/firebase_dependencies.gradle
  app/CMakeLists.txt
  app_check/integration_test/AndroidManifest.xml
  app_check/integration_test/CMakeLists.txt
  app_check/integration_test/Images.xcassets/AppIcon.appiconset/Contents.json
  app_check/integration_test/Images.xcassets/LaunchImage.launchimage/Contents.json
  app_check/integration_test/Info.plist
  app_check/integration_test/LaunchScreen.storyboard
  app_check/integration_test/LibraryManifest.xml
  app_check/integration_test/Podfile
  app_check/integration_test/build.gradle
  app_check/integration_test/googletest.cmake
  app_check/integration_test/gradle/wrapper/gradle-wrapper.jar
  app_check/integration_test/gradle/wrapper/gradle-wrapper.properties
  app_check/integration_test/gradlew
  app_check/integration_test/gradlew.bat
  app_check/integration_test/integration_test.xcodeproj/project.pbxproj
  app_check/integration_test/integration_test.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  app_check/integration_test/integration_test.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  app_check/integration_test/integration_test_tvos/Base.lproj/LaunchScreen.storyboard
  app_check/integration_test/integration_test_tvos/Base.lproj/Main.storyboard
  app_check/integration_test/proguard.pro
  app_check/integration_test/res/layout/main.xml
  app_check/integration_test/res/values/strings.xml
  app_check/integration_test/settings.gradle
  app_check/integration_test/src/integration_test.cc
  ios_pod/Podfile
  scripts/gha-encrypted/app_check/GoogleService-Info.plist.gpg
  scripts/gha-encrypted/app_check/google-services.json.gpg
  scripts/gha/build_ios_tvos.py
  scripts/gha/integration_testing/build_testapps.json
Labels: skip-release-notes

#1111 Firestore: Remove copies in FieldValueInternal to reduce global refs consumption.
  firestore/src/android/field_value_android.cc
  firestore/src/android/field_value_android.h
  release_build_files/readme.md
Labels: api: firestore, tests: succeeded

#1105 Fix integration tests settings.gradle
  .gitignore
  admob/integration_test/settings.gradle
  analytics/integration_test/settings.gradle
  app/integration_test/settings.gradle
  auth/integration_test/settings.gradle
  database/integration_test/settings.gradle
  dynamic_links/integration_test/settings.gradle
  firestore/integration_test/settings.gradle
  firestore/integration_test_internal/settings.gradle
  functions/integration_test/settings.gradle
  gma/integration_test/settings.gradle
  installations/integration_test/settings.gradle
  messaging/integration_test/settings.gradle
  remote_config/integration_test/settings.gradle
  storage/integration_test/settings.gradle
Labels: tests: succeeded, skip-release-notes

#1103 CMakeLists.txt: Add `FIREBASE_FLATC_CMAKE_COMMAND`
  CMakeLists.txt
Labels: skip-release-notes

#1115 update workflow files to reduce warnings
  .github/workflows/android.yml
  .github/workflows/checks.yml
  .github/workflows/checks_secure.yml
  .github/workflows/cpp-packaging.yml
  .github/workflows/desktop.yml
  .github/workflows/integration_tests.yml
  .github/workflows/ios.yml
  .github/workflows/lint.yml
  .github/workflows/reviewer-roulette.yml
  .github/workflows/update-dependencies.yml
Labels: skip-release-notes

#1116 Update README.md
  README.md
Labels: tests: succeeded, skip-release-notes

#1118 Update gitignore for integration test files
  .gitignore
Labels: skip-release-notes

#1123 Disable failing iOS storage integration test cases
  storage/integration_test/src/integration_test.cc
Labels: skip-release-notes

#1109 Update Test Devices & other minor fixes
  .github/workflows/integration_tests.yml
  scripts/gha/github.py
  scripts/gha/print_matrix_configuration.py
Labels: skip-release-notes

#1124 Temporarily disable broken ios tests on tvos as well
  storage/integration_test/src/integration_test.cc
Labels: tests: in-progress, skip-release-notes

#1125 Fix error with request ToString
  app/rest/request.cc
Labels: skip-release-notes
