Repository firebase/firebase-cpp-sdk, pull requests merged in 2022-02, with the labels that each got.

#830 Create Integration Test Nightly Report for firestore
  .github/workflows/cpp-packaging.yml
  .github/workflows/integration_tests.yml
  scripts/gha/it_workflow.py
Labels: tests: succeeded, skip-release-notes

#839 Add missing :gma:gma_resources to firebaseResourceDependenciesMap
  Android/firebase_dependencies.gradle
Labels: skip-release-notes

#837 GMA AdView::ad_size()
  gma/integration_test/src/integration_test.cc
  gma/src/android/ad_view_internal_android.cc
  gma/src/android/ad_view_internal_android.h
  gma/src/common/ad_view.cc
  gma/src/common/ad_view_internal.h
  gma/src/include/firebase/gma/ad_view.h
  gma/src/ios/ad_view_internal_ios.h
  gma/src/ios/ad_view_internal_ios.mm
  gma/src/stub/ad_view_internal_stub.h
Labels: skip-release-notes

#840 Fix a typo in the firebase_dependencies.gradle file.
  Android/firebase_dependencies.gradle
Labels: tests: succeeded, skip-release-notes

#841 Add "reviewer roulette" workflow.
  .github/workflows/reviewer-roulette.yml
Labels: skip-release-notes

#843 Don't call FIRConfiguration setLoggerLevel: before FIRApp exists.
  app/src/app_ios.h
  app/src/app_ios.mm
  app/src/log_ios.mm
  app/src/util.cc
  release_build_files/readme.md
Labels: tests: succeeded

#842 Remove the "unapproved C++ header" lint warning.
  scripts/gha/lint_commenter.py
Labels: skip-release-notes

#851 Fix error in default RC Fetch timeout, and add test for Fetch(seconds).
  release_build_files/readme.md
  remote_config/integration_test/src/integration_test.cc
  remote_config/src/remote_config.cc
Labels: tests: succeeded

#856 Fix cancel workflow run
  .github/workflows/integration_tests.yml
Labels: skip-release-notes

#846 Heartbeat logging passthrough for Auth on Mobile Platforms
  auth/src/android/auth_android.cc
  auth/src/auth.cc
  auth/src/common.h
  auth/src/desktop/auth_desktop.cc
  auth/src/include/firebase/auth.h
  auth/src/ios/auth_ios.mm
Labels: skip-release-notes

#852 Enable Firestore Emulator only when needed
  .github/workflows/integration_tests.yml
Labels: tests: succeeded, skip-release-notes

#855 (Desktop) Firestore C++ Core from TIP by default
  cmake/external/firestore.cmake
  cmake/external_rules.cmake
  scripts/gha/build_desktop.py
Labels: tests: succeeded, skip-release-notes
