Repository firebase/firebase-cpp-sdk, pull requests merged in 2022-06, with the labels that each got.

#968 Remove protobuf and nanopb setup
  CMakeLists.txt
  README.md
  build_scripts/android/install_prereqs.sh
  build_scripts/tvos/install_prereqs.sh
  cmake/external/CMakeLists.txt
  cmake/external/nanopb.cmake
  cmake/external_rules.cmake
  remote_config/CMakeLists.txt
Labels: tests: succeeded, skip-release-notes

#982 Remove iOS 11.4 from FTL list.
  scripts/gha/print_matrix_configuration.py
Labels: skip-release-notes

#981 Add RE2 library to desktop packaging & Update MSVC dependencies
  build_scripts/desktop/package.sh
  firestore/integration_test/CMakeLists.txt
  release_build_files/readme.md
Labels: api: firestore

#986 Use NDK r21e (installed by prereqs script) for Android builds.
  .github/workflows/android.yml
  .github/workflows/integration_tests.yml
Labels: skip-release-notes

#949 Switch from individual Firebase Android SDK versions to Android BoM
  Android/firebase_dependencies.gradle
  admob/admob_resources/build.gradle
  app/app_resources/build.gradle
  app/google_api_resources/build.gradle
  app/integration_test/build.gradle
  app/invites_resources/build.gradle
  auth/auth_resources/build.gradle
  database/database_resources/build.gradle
  firestore/firestore_resources/build.gradle
  messaging/messaging_java/build.gradle
  release_build_files/Android/firebase_dependencies.gradle
  release_build_files/readme.md
  storage/storage_resources/build.gradle
Labels: tests: succeeded

#990 updated Android gma version to 21.0.0
  Android/firebase_dependencies.gradle
  gma/gma_resources/build.gradle
  release_build_files/Android/firebase_dependencies.gradle
Labels: api: gma

#995 Update Android BOM to 30.1.0 in integration tests and readme
  admob/admob_resources/build.gradle
  app/app_resources/build.gradle
  app/google_api_resources/build.gradle
  app/invites_resources/build.gradle
  auth/auth_resources/build.gradle
  database/database_resources/build.gradle
  firestore/firestore_resources/build.gradle
  messaging/messaging_java/build.gradle
  release_build_files/readme.md
  storage/storage_resources/build.gradle
Labels: tests: succeeded

#991 Add an API flag to restore_secrets script
  scripts/gha/restore_secrets.py
Labels: tests: succeeded, skip-release-notes

#999 Fix #994 Remove unnecessary error for FCM
  messaging/src/ios/messaging.mm
Labels: skip-release-notes

#998 Fix #973 Make sure all resources are closed in RegistrationIntentService
  messaging/src/android/java/com/google/firebase/messaging/cpp/RegistrationIntentService.java
  release_build_files/readme.md
Labels: tests: succeeded

#992 In RTDB, create app data directory if it doesn't exist. Modify AppDataDir to create the whole path if needed.
  app/src/filesystem_desktop_linux.cc
  database/src/desktop/core/repo.cc
  release_build_files/readme.md
Labels: tests: succeeded

#1002 GMA updates to release notes
  release_build_files/readme.md
Labels: cla: yes

#1004 Update GMA feature branch with main (June 23)
  admob/integration_test/Podfile
  analytics/integration_test/Podfile
  analytics/ios_headers/FIREventNames.h
  analytics/ios_headers/FIRParameterNames.h
  analytics/ios_headers/FIRUserPropertyNames.h
  app/integration_test/Podfile
  auth/integration_test/Podfile
  cmake/external/firestore.cmake
  cmake/external/firestore.patch.txt
  cmake/external/firestore_snappy.patch.txt
  cmake/external/leveldb.cmake
  database/integration_test/Podfile
  dynamic_links/integration_test/Podfile
  firestore/integration_test/Podfile
  firestore/integration_test_internal/Podfile
  functions/integration_test/Podfile
  gma/gma_resources/build.gradle
  gma/integration_test/Podfile
  installations/integration_test/Podfile
  ios_pod/Podfile
  ios_pod/swift_headers/FirebaseAnalyticsSwift-Swift.h
  ios_pod/swift_headers/FirebaseCoreInternal-Swift.h
  ios_pod/swift_headers/FirebaseDatabaseSwift-Swift.h
  ios_pod/swift_headers/FirebaseFirestoreSwift-Swift.h
  ios_pod/swift_headers/FirebaseFunctions-Swift.h
  ios_pod/swift_headers/FirebaseInAppMessagingSwift-Swift.h
  ios_pod/swift_headers/FirebaseMLModelDownloader-Swift.h
  ios_pod/swift_headers/FirebaseRemoteConfigSwift-Swift.h
  ios_pod/swift_headers/FirebaseSharedSwift-Swift.h
  ios_pod/swift_headers/FirebaseStorage-Swift.h
  ios_pod/swift_headers/SwiftProtobuf-Swift.h
  messaging/integration_test/Podfile
  release_build_files/readme.md
  remote_config/integration_test/Podfile
  storage/integration_test/Podfile
Labels: tests: succeeded

#1006 Change Firestore external ref to one with patch.exe bugfix
  cmake/external/firestore.cmake
Labels: skip-release-notes

#966 Firestore TransactionOptions added, to specify maxAttempts
  app/CMakeLists.txt
  firestore/CMakeLists.txt
  firestore/integration_test_internal/CMakeLists.txt
  firestore/integration_test_internal/integration_test.xcodeproj/project.pbxproj
  firestore/integration_test_internal/src/android/transaction_options_android_test.cc
  firestore/integration_test_internal/src/transaction_options_test.cc
  firestore/integration_test_internal/src/transaction_test.cc
  firestore/src/android/firestore_android.cc
  firestore/src/android/firestore_android.h
  firestore/src/android/transaction_options_android.cc
  firestore/src/android/transaction_options_android.h
  firestore/src/android/transaction_options_builder_android.cc
  firestore/src/android/transaction_options_builder_android.h
  firestore/src/common/firestore.cc
  firestore/src/common/transaction_options.cc
  firestore/src/include/firebase/firestore.h
  firestore/src/include/firebase/firestore/transaction_options.h
  firestore/src/main/firestore_main.cc
  firestore/src/main/firestore_main.h
  release_build_files/readme.md
Labels: api: firestore, tests: succeeded
