Repository firebase/firebase-cpp-sdk, pull requests merged in 2023-06, with the labels that each got.

#1310 Internal updates 4
  gma/integration_test/src/integration_test.cc
  gma/src/android/gma_android.cc
  gma/src/android/native_ad_image_android.cc
  gma/src/android/native_ad_image_android.h
  gma/src/common/gma_common.cc
  gma/src/common/gma_common.h
  gma/src/common/native_ad.cc
  gma/src/common/native_ad_image_internal.h
  gma/src/common/native_ad_internal.h
  gma/src/include/firebase/gma/internal/native_ad.h
  gma/src/include/firebase/gma/types.h
  gma/src/ios/gma_ios.h
  gma/src/ios/gma_ios.mm
  gma/src/ios/native_ad_image_ios.mm
  gma/src/stub/native_ad_image_stub.cc
  gma/src_java/com/google/firebase/gma/internal/cpp/DownloadHelper.java
Labels: tests: succeeded, skip-release-notes

#1300 Internal updates 3
  gma/CMakeLists.txt
  gma/integration_test/src/integration_test.cc
  gma/src/android/gma_android.cc
  gma/src/android/native_ad_image_android.cc
  gma/src/android/native_ad_image_android.h
  gma/src/common/gma_common.cc
  gma/src/common/gma_common.h
  gma/src/common/native_ad.cc
  gma/src/common/native_ad_image_internal.h
  gma/src/common/native_ad_internal.cc
  gma/src/common/native_ad_internal.h
  gma/src/include/firebase/gma/internal/native_ad.h
  gma/src/include/firebase/gma/types.h
  gma/src/ios/gma_ios.h
  gma/src/ios/gma_ios.mm
  gma/src/ios/native_ad_image_ios.h
  gma/src/ios/native_ad_image_ios.mm
  gma/src/ios/native_ad_internal_ios.mm
  gma/src/stub/native_ad_image_stub.cc
  gma/src_java/com/google/firebase/gma/internal/cpp/DownloadHelper.java
  gma/src_java/com/google/firebase/gma/internal/cpp/NativeAdHelper.java
Labels: skip-release-notes

#1269 Internal updates 2
  gma/CMakeLists.txt
  gma/integration_test/src/integration_test.cc
  gma/src/android/gma_android.cc
  gma/src/android/native_ad_image_android.cc
  gma/src/android/native_ad_image_android.h
  gma/src/common/gma_common.cc
  gma/src/common/gma_common.h
  gma/src/common/native_ad.cc
  gma/src/common/native_ad_image_internal.h
  gma/src/common/native_ad_internal.cc
  gma/src/common/native_ad_internal.h
  gma/src/include/firebase/gma/internal/native_ad.h
  gma/src/include/firebase/gma/types.h
  gma/src/ios/FADNativeDelegate.h
  gma/src/ios/FADNativeDelegate.mm
  gma/src/ios/gma_ios.h
  gma/src/ios/gma_ios.mm
  gma/src/ios/native_ad_image_ios.h
  gma/src/ios/native_ad_image_ios.mm
  gma/src/ios/native_ad_internal_ios.h
  gma/src/ios/native_ad_internal_ios.mm
  gma/src/stub/native_ad_image_stub.cc
  gma/src_java/com/google/firebase/gma/internal/cpp/DownloadHelper.java
  gma/src_java/com/google/firebase/gma/internal/cpp/NativeAdHelper.java
Labels: tests: succeeded, skip-release-notes

#1332 Handle time zone environment variable having international characters.
  app/src/locale.cc
  app/tests/CMakeLists.txt
  release_build_files/readme.md
  remote_config/CMakeLists.txt
  remote_config/integration_test/CMakeLists.txt
Labels: tests: succeeded

#1339 Fix App and App Check headers for doxygen
  app/src/include/firebase/app.h
  app_check/src/include/firebase/app_check/app_attest_provider.h
  app_check/src/include/firebase/app_check/debug_provider.h
  app_check/src/include/firebase/app_check/device_check_provider.h
  app_check/src/include/firebase/app_check/play_integrity_provider.h
Labels: skip-release-notes

#1340 Add a dashboard of build/test status to the nightly build page.
  .github/workflows/build-report.yml
  scripts/gha/it_workflow.py
  scripts/gha/report_build_status.py
  scripts/gha/update_issue_comment.py
Labels: skip-release-notes

#1342 Redo build dashboard with integration test script fix
  .github/workflows/build-report.yml
  scripts/gha/it_workflow.py
  scripts/gha/report_build_status.py
  scripts/gha/update_issue_comment.py
Labels: tests: failed

#1251 Internal updates
  app/CMakeLists.txt
  gma/CMakeLists.txt
  gma/integration_test/src/integration_test.cc
  gma/src/android/gma_android.cc
  gma/src/android/native_ad_image_android.cc
  gma/src/android/native_ad_image_android.h
  gma/src/android/native_ad_internal_android.cc
  gma/src/android/native_ad_internal_android.h
  gma/src/common/gma_common.cc
  gma/src/common/gma_common.h
  gma/src/common/native_ad.cc
  gma/src/common/native_ad_image_internal.h
  gma/src/common/native_ad_internal.cc
  gma/src/common/native_ad_internal.h
  gma/src/include/firebase/gma.h
  gma/src/include/firebase/gma/internal/README.md
  gma/src/include/firebase/gma/internal/native_ad.h
  gma/src/include/firebase/gma/types.h
  gma/src/ios/FADNativeDelegate.h
  gma/src/ios/FADNativeDelegate.mm
  gma/src/ios/gma_ios.h
  gma/src/ios/gma_ios.mm
  gma/src/ios/native_ad_image_ios.h
  gma/src/ios/native_ad_image_ios.mm
  gma/src/ios/native_ad_internal_ios.h
  gma/src/ios/native_ad_internal_ios.mm
  gma/src/stub/native_ad_image_stub.cc
  gma/src/stub/native_ad_internal_stub.h
  gma/src_java/com/google/firebase/gma/internal/cpp/DownloadHelper.java
  gma/src_java/com/google/firebase/gma/internal/cpp/NativeAdHelper.java
Labels: tests: succeeded, skip-release-notes

#1343 Additional small fixes for the build report.
  .github/workflows/build-report.yml
  scripts/gha/it_workflow.py
  scripts/gha/report_build_status.py
Labels: skip-release-notes

#1347 .gitignore: add CMakeUserPresets.json
  .gitignore
Labels: tests: succeeded, skip-release-notes

#1351 Add a summary of the most often failing tests to the daily build report
  .github/workflows/build-report.yml
  scripts/gha/report_build_status.py
Labels: skip-release-notes

#1344 Firestore: integration_test_internal/build.gradle: improvements for local dev: targets and abiFilters
  firestore/integration_test_internal/build.gradle
Labels: api: firestore, tests: succeeded, skip-release-notes

#1345 Firestore: env.cc: avoid calling ok() in the destructor if there is no exception handler
  firestore/src/jni/env.cc
Labels: api: firestore, tests: succeeded, skip-release-notes

#1356 format_code.py: fix NameError when --d is specified
  scripts/format_code.py
Labels: skip-release-notes

#1357 Firestore: Improve Android tests to use the new env() helper function rather than creating an Env on the stack
  firestore/integration_test_internal/src/android/firestore_integration_test_android.cc
  firestore/integration_test_internal/src/android/firestore_integration_test_android.h
  firestore/integration_test_internal/src/android/firestore_integration_test_android_test.cc
  firestore/integration_test_internal/src/android/geo_point_android_test.cc
  firestore/integration_test_internal/src/android/jni_runnable_android_test.cc
  firestore/integration_test_internal/src/android/promise_android_test.cc
  firestore/integration_test_internal/src/android/promise_factory_android_test.cc
  firestore/integration_test_internal/src/android/settings_android_test.cc
  firestore/integration_test_internal/src/android/snapshot_metadata_android_test.cc
  firestore/integration_test_internal/src/android/timestamp_android_test.cc
  firestore/integration_test_internal/src/android/transaction_options_android_test.cc
  firestore/integration_test_internal/src/firestore_test.cc
  firestore/integration_test_internal/src/jni/task_test.cc
Labels: api: firestore, tests: succeeded, skip-release-notes

#1349 Internal updates
  app/src/util_android.h
  gma/integration_test/src/integration_test.cc
  gma/src/android/native_ad_internal_android.cc
  gma/src/android/native_ad_internal_android.h
  gma/src/common/gma_common.cc
  gma/src/common/gma_common.h
  gma/src/common/native_ad.cc
  gma/src/common/native_ad_internal.h
  gma/src/include/firebase/gma/internal/native_ad.h
  gma/src/ios/GADNativeAdCpp.h
  gma/src/ios/native_ad_internal_ios.h
  gma/src/ios/native_ad_internal_ios.mm
  gma/src/stub/native_ad_internal_stub.h
  gma/src_java/com/google/firebase/gma/internal/cpp/NativeAdHelper.java
Labels: tests: succeeded, skip-release-notes

#1360 Fix PhoneAuthOptions Timeout overflow on some platforms
  auth/src/android/credential_android.cc
  release_build_files/readme.md
Labels: tests: succeeded

#1363 Fix gma flaky tests caused by nofill error
  gma/integration_test/src/integration_test.cc
Labels: tests: succeeded, skip-release-notes

#1366 Increase the wait time for realtime integration test from 10s to 30s
  remote_config/integration_test/src/integration_test.cc
Labels: skip-release-notes

#1368 Improve the iOS simulator install logic
  scripts/gha/test_simulator.py
Labels: skip-release-notes

#1362 Update to June 2022 release of boringssl.
  CMakeLists.txt
  cmake/external/boringssl.cmake
  cmake/external_rules.cmake
  scripts/git/patches/boringssl/0001-disable-warnings.patch
Labels: tests: succeeded, skip-release-notes

#1358 Clean up JNI task listeners per object
  app/src/util.cc
  app/src/util.h
  app/tests/util_test.cc
  app_check/src/android/app_check_android.cc
  app_check/src/android/app_check_android.h
  app_check/src/android/common_android.cc
  app_check/src/android/common_android.h
  auth/src/auth.cc
  database/src/android/database_android.cc
  database/src/android/database_android.h
  database/src/android/database_reference_android.cc
  database/src/android/disconnection_android.cc
  functions/src/android/callable_reference_android.cc
  functions/src/android/functions_android.cc
  functions/src/android/functions_android.h
  installations/src/android/installations_android.cc
  installations/src/android/installations_android.h
  remote_config/src/android/remote_config_android.cc
  remote_config/src/android/remote_config_android.h
  storage/src/android/storage_android.cc
  storage/src/android/storage_android.h
  storage/src/android/storage_reference_android.cc
Labels: tests: succeeded, skip-release-notes

#1371 Add a GitHub warning to the iOS simulator logic
  scripts/gha/test_simulator.py
Labels: skip-release-notes

#1373 Release load_ad futures in flaky gma tests
  gma/integration_test/src/integration_test.cc
Labels: tests: succeeded, skip-release-notes

#1376 Use core implementation of aggregate query equality operator.
  firestore/src/main/aggregate_query_main.cc
  firestore/src/main/aggregate_query_snapshot_main.cc
Labels: skip-release-notes

#1359 Firestore: Various small improvements to the Android integration tests
  firestore/integration_test_internal/src/android/firestore_integration_test_android.cc
  firestore/integration_test_internal/src/android/firestore_integration_test_android_test.cc
  firestore/integration_test_internal/src/jni/task_test.cc
Labels: api: firestore, tests: succeeded, skip-release-notes

#1370 Add step to C++ packaging to create Windows package.
  .github/workflows/cpp-packaging.yml
Labels: skip-release-notes

#1364 Firestore: Fix global refs exhaustion issue in Android
  firestore/CMakeLists.txt
  firestore/integration_test_internal/CMakeLists.txt
  firestore/integration_test_internal/src/android/arena_ref_android_test.cc
  firestore/integration_test_internal/src/document_reference_test.cc
  firestore/integration_test_internal/src/field_value_test.cc
  firestore/src/android/document_reference_android.cc
  firestore/src/android/field_value_android.cc
  firestore/src/android/field_value_android.h
  firestore/src/android/firestore_android.cc
  firestore/src/android/query_android.cc
  firestore/src/android/util_android.cc
  firestore/src/android/util_android.h
  firestore/src/android/wrapper.cc
  firestore/src/android/wrapper.h
  firestore/src/android/write_batch_android.cc
  firestore/src/android/write_batch_android.h
  firestore/src/jni/arena_ref.cc
  firestore/src/jni/arena_ref.h
  firestore/src/jni/env.h
  firestore/src/jni/loader.h
  firestore/src_java/com/google/firebase/firestore/internal/cpp/ObjectArena.java
  release_build_files/readme.md
Labels: api: firestore, tests: succeeded

#1379 Run iOS simulator install as root
  scripts/gha/test_simulator.py
Labels: tests: succeeded, skip-release-notes
