Repository firebase/firebase-cpp-sdk, pull requests merged in 2023-05, with the labels that each got.

#1299 Update Firestore dependency to use patched SDK.
  cmake/external/firestore.cmake
Labels: skip-release-notes

#1292 Add App Check to the packaging logic
  .github/workflows/cpp-packaging.yml
  .github/workflows/integration_tests.yml
  app_check/integration_test/CMakeLists.txt
  app_check/integration_test/Podfile
  app_check/integration_test/build.gradle
  app_check/integration_test/integration_test.xcodeproj/xcshareddata/xcschemes/integration_test.xcscheme
  app_check/integration_test/integration_test.xcodeproj/xcshareddata/xcschemes/integration_test_tvos.xcscheme
  app_check/integration_test/src/integration_test.cc
  app_check/src/android/app_check_android.cc
  app_check/src/desktop/debug_token_request.h
  build_scripts/packaging.conf
  release_build_files/CMakeLists.txt
  scripts/gha/build_ios_tvos.py
  scripts/gha/integration_testing/build_testapps.json
  scripts/gha/print_matrix_configuration.py
  scripts/gha/restore_secrets.py
Labels: tests: succeeded, skip-release-notes

#1255 Auth Google IO 23
  app_check/integration_test/src/integration_test.cc
  auth/CMakeLists.txt
  auth/integration_test/src/integration_test.cc
  auth/samples/src/doc_samples.cc
  auth/src/android/auth_android.cc
  auth/src/android/common_android.cc
  auth/src/android/common_android.h
  auth/src/android/credential_android.cc
  auth/src/android/user_android.cc
  auth/src/auth.cc
  auth/src/common.cc
  auth/src/common.h
  auth/src/credential.cc
  auth/src/data.h
  auth/src/desktop/auth_desktop.cc
  auth/src/desktop/auth_desktop.h
  auth/src/desktop/auth_providers/federated_auth_provider.cc
  auth/src/desktop/auth_providers/phone_auth_provider.cc
  auth/src/desktop/auth_util.cc
  auth/src/desktop/auth_util.h
  auth/src/desktop/authentication_result.cc
  auth/src/desktop/authentication_result.h
  auth/src/desktop/credential_desktop.cc
  auth/src/desktop/sign_in_flow.h
  auth/src/desktop/user_desktop.cc
  auth/src/include/firebase/auth.h
  auth/src/include/firebase/auth/credential.h
  auth/src/include/firebase/auth/user.h
  auth/src/ios/auth_ios.mm
  auth/src/ios/common_ios.h
  auth/src/ios/credential_ios.mm
  auth/src/ios/user_ios.mm
  auth/src/user.cc
  auth/tests/auth_test.cc
  auth/tests/desktop/auth_desktop_test.cc
  auth/tests/desktop/user_desktop_test.cc
  auth/tests/user_test.cc
  database/integration_test/src/integration_test.cc
  firestore/integration_test/src/integration_test.cc
  firestore/integration_test_internal/src/integration_test.cc
  functions/integration_test/src/integration_test.cc
  release_build_files/readme.md
  storage/integration_test/src/integration_test.cc
Labels: tests: succeeded

#1303 Fix RemoteConfigError enum values
  remote_config/src/include/firebase/remote_config.h
Labels: skip-release-notes

#1306 Fix use of handle in AppCheck block
  app_check/src/ios/app_check_ios.mm
Labels: skip-release-notes

#1307 Removed @ref flags that are messing up internal doc generation.
  auth/src/include/firebase/auth.h
  auth/src/include/firebase/auth/user.h
Labels: skip-release-notes

#1309 Fix `credential.is_valid()` crash on iOS
  auth/integration_test/src/integration_test.cc
  auth/src/ios/auth_ios.mm
  auth/src/ios/common_ios.h
  auth/src/ios/user_ios.mm
  release_build_files/readme.md
Labels: tests: succeeded

#1319 Support international paths on Windows in app
  app/rest/request_file.cc
  app/src/log.cc
Labels: tests: succeeded, skip-release-notes

#1315 Patch leveldb for Windows UTF16 path support
  cmake/external/firestore.patch.txt
  cmake/external/leveldb.cmake
  release_build_files/readme.md
  scripts/git/patches/leveldb/0001-leveldb-1.23-windows-paths.patch
Labels: tests: succeeded

#1313 Modify heartbeat local storage to use wide strings on Windows.
  app/src/app_desktop.cc
  app/src/heartbeat/heartbeat_storage_desktop.cc
  app/src/heartbeat/heartbeat_storage_desktop.h
  app/tests/heartbeat_storage_desktop_test.cc
Labels: tests: succeeded, skip-release-notes

#1322 Patch flatbuffers to fix a warning that occurs with some compiler versions
  cmake/external/flatbuffers.cmake
  scripts/git/patches/flatbuffers/0001-remove-unused-var.patch
Labels: skip-release-notes

#1316 On Windows desktop, use wide path strings in Remote Config.
  app/src/filesystem.h
  remote_config/src/desktop/file_manager.cc
  remote_config/src/desktop/file_manager.h
  remote_config/src/desktop/remote_config_desktop.cc
Labels: tests: succeeded, skip-release-notes

#1326 Update ios and tvos simulator versions for GitHub runners
  scripts/gha/print_matrix_configuration.py
Labels: tests: failed, skip-release-notes

#1328 Update ios and tvos simulator versions for GitHub runners (a second time)
  scripts/gha/print_matrix_configuration.py
Labels: tests: succeeded, skip-release-notes

#1330 Fix for a deadlock in JniResultCallback
  app/src_java/com/google/firebase/app/internal/cpp/JniResultCallback.java
  release_build_files/readme.md
Labels: tests: succeeded

#1327 add api to get allApps
  .gitignore
  app/integration_test/src/integration_test.cc
  app/src/app_android.cc
  app/src/app_common.cc
  app/src/app_common.h
  app/src/app_desktop.cc
  app/src/app_ios.mm
  app/src/app_stub.cc
  app/src/include/firebase/app.h
  app/src/util_android.h
Labels: skip-release-notes
