Repository firebase/firebase-cpp-sdk, pull requests merged in 2023-01, with the labels that each got.

#1181 [Bugfx] Fix Nightly Test Report template
  scripts/gha/it_workflow.py
Labels: skip-release-notes

#1180 Reduce number of RewardedAd loads on iOS in CI
  gma/integration_test/src/integration_test.cc
Labels: skip-release-notes

#1135 Add GetSessionId implementation for Android, iOS, and stub.
  analytics/integration_test/src/integration_test.cc
  analytics/src/analytics_android.cc
  analytics/src/analytics_common.h
  analytics/src/analytics_ios.mm
  analytics/src/analytics_stub.cc
  analytics/src/include/firebase/analytics.h
  release_build_files/readme.md
Labels: tests: succeeded

#1190 Change the GetSessionId docs to match GetAnalyticsInstanceId's phrasing.
  analytics/src/include/firebase/analytics.h
Labels: skip-release-notes

#1191 Auto update GMA deps on iOS.
  scripts/update_android_ios_dependencies.py
Labels: skip-release-notes

#1193 Disable getSessionId test on emulators.
  analytics/integration_test/src/integration_test.cc
Labels: tests: failed, skip-release-notes

#1196 Mark GMA stress tests as requiring user interaction on Android as well.
  gma/integration_test/src/integration_test.cc
Labels: skip-release-notes

#1197 Handle NoFill errors in TestRewardedAdLoad tests.
  gma/integration_test/src/integration_test.cc
Labels: api: ads, tests: succeeded, skip-release-notes
