Repository firebase/firebase-cpp-sdk, pull requests merged in 2023-04, with the labels that each got.

#1207 Firestore COUNT
  .gitignore
  app/CMakeLists.txt
  firestore/CMakeLists.txt
  firestore/CONTRIBUTING.md
  firestore/integration_test_internal/CMakeLists.txt
  firestore/integration_test_internal/src/aggregate_count_test.cc
  firestore/integration_test_internal/src/aggregate_query_snapshot_test.cc
  firestore/integration_test_internal/src/aggregate_query_test.cc
  firestore/integration_test_internal/src/firestore_integration_test.cc
  firestore/integration_test_internal/src/firestore_integration_test.h
  firestore/integration_test_internal/src/query_snapshot_test.cc
  firestore/src/android/aggregate_query_android.cc
  firestore/src/android/aggregate_query_android.h
  firestore/src/android/aggregate_query_snapshot_android.cc
  firestore/src/android/aggregate_query_snapshot_android.h
  firestore/src/android/aggregate_source_android.cc
  firestore/src/android/aggregate_source_android.h
  firestore/src/android/firestore_android.cc
  firestore/src/android/firestore_android.h
  firestore/src/android/load_bundle_task_progress_android.cc
  firestore/src/android/promise_android.h
  firestore/src/android/query_android.cc
  firestore/src/android/query_android.h
  firestore/src/common/aggregate_query.cc
  firestore/src/common/aggregate_query_snapshot.cc
  firestore/src/common/query.cc
  firestore/src/common/type_mapping.h
  firestore/src/include/firebase/firestore.h
  firestore/src/include/firebase/firestore/aggregate_query.h
  firestore/src/include/firebase/firestore/aggregate_query_snapshot.h
  firestore/src/include/firebase/firestore/aggregate_source.h
  firestore/src/include/firebase/firestore/query.h
  firestore/src/main/aggregate_query_main.cc
  firestore/src/main/aggregate_query_main.h
  firestore/src/main/aggregate_query_snapshot_main.cc
  firestore/src/main/aggregate_query_snapshot_main.h
  firestore/src/main/converter_main.h
  firestore/src/main/query_main.cc
  firestore/src/main/query_main.h
  release_build_files/readme.md
Labels: tests: succeeded

#1270 Pass database_id from GetInstance() down to CreateFirestore()
  firestore/integration_test_internal/src/util/integration_test_util.cc
  firestore/integration_test_internal/src/validation_test.cc
  firestore/src/common/firestore.cc
  firestore/src/include/firebase/firestore.h
  firestore/src/main/firestore_main.cc
  firestore/src/main/firestore_main.h
Labels: skip-release-notes

#1275 Default no-op for deprecated virtual function
  auth/src/include/firebase/auth/credential.h
Labels: skip-release-notes

#1277 Firestore: Fix args to AggregateQuerySnapshot constructor
  auth/integration_test/build.gradle
  database/integration_test/build.gradle
  firestore/integration_test/build.gradle
  firestore/integration_test_internal/build.gradle
  firestore/src/android/aggregate_query_snapshot_android.cc
  firestore/src_java/com/google/firebase/firestore/internal/cpp/AggregateQuerySnapshotHelper.java
  functions/integration_test/build.gradle
  storage/integration_test/build.gradle
Labels: api: firestore, tests: failed, skip-release-notes

#1279 Add support for symbols with {lambda...#1} to merge_libraries.py
  scripts/merge_libraries.py
  scripts/merge_libraries_test.py
Labels: skip-release-notes

#1281 Fixes for the App Check Android testapp
  app_check/integration_test/build.gradle
  app_check/integration_test/src/integration_test.cc
  app_check/src/android/app_check_android.cc
Labels: skip-release-notes

#1287 Wrap the App Check Obj C pointers to fix memory issues
  app_check/src/ios/debug_provider_ios.h
  app_check/src/ios/debug_provider_ios.mm
  app_check/src/ios/device_check_provider_ios.h
  app_check/src/ios/device_check_provider_ios.mm
Labels: skip-release-notes

#1280 Android Implementation of Realtime RC
  Android/firebase_dependencies.gradle
  remote_config/CMakeLists.txt
  remote_config/build.gradle
  remote_config/integration_test/src/integration_test.cc
  remote_config/remote_config_resources/build.gradle
  remote_config/src/android/remote_config_android.cc
  remote_config/src/config_update_listener_registration.cc
  remote_config/src/include/firebase/remote_config/config_update_listener_registration.h
  remote_config/src_java/com/google/firebase/remoteconfig/internal/cpp/JniConfigUpdateListener.java
  settings.gradle
Labels: tests: failed

#1288 Add ability to set the App Check Debug Factory token
  app_check/integration_test/build.gradle
  app_check/src/android/app_check_android.cc
  app_check/src/android/debug_provider_android.cc
  app_check/src/android/debug_provider_android.h
  app_check/src/android/play_integrity_provider_android.cc
  app_check/src/common/debug_provider_common.cc
  app_check/src/desktop/debug_provider_desktop.cc
  app_check/src/desktop/debug_provider_desktop.h
  app_check/src/include/firebase/app_check/app_attest_provider.h
  app_check/src/include/firebase/app_check/debug_provider.h
  app_check/src/include/firebase/app_check/device_check_provider.h
  app_check/src/include/firebase/app_check/play_integrity_provider.h
  app_check/src/ios/app_attest_provider_ios.mm
  app_check/src/ios/debug_provider_ios.h
  app_check/src/ios/debug_provider_ios.mm
  app_check/src/ios/device_check_provider_ios.mm
  app_check/src_java/com/google/firebase/appcheck/internal/cpp/JniAppCheckDebugHelper.java
Labels: skip-release-notes
