Repository firebase/firebase-cpp-sdk, pull requests merged in 2023-08, with the labels that each got.

#1409 Kick off nightly packaging an hour earlier
  .github/workflows/cpp-packaging.yml
Labels: skip-release-notes

#1320 Fix crash on gma::Initialize without a Firebase App
  gma/integration_test/src/integration_test.cc
  gma/src/android/gma_android.cc
  release_build_files/readme.md
Labels: tests: succeeded

#1410 build: pass along the CMake path
  cmake/external_rules.cmake
Labels: tests: succeeded, skip-release-notes

#1411 Add log to gsutil fetch.
  scripts/gha/integration_testing/ftl_gha_validator.py
Labels: tests: succeeded, skip-release-notes

#1421 Update release version number for M135, 11.4.0
  cpp_sdk_version.json
Labels: skip-release-notes

#1422 Internal Updates.
  gma/src/android/native_ad_image_android.cc
Labels: skip-release-notes

#1412 Add User Messaging Platform iOS support
  gma/CMakeLists.txt
  gma/integration_test/Info.plist
  gma/integration_test/Podfile
  gma/integration_test/integration_test.xcodeproj/project.pbxproj
  gma/integration_test/src/integration_test.cc
  gma/src/common/ump/consent_info_internal.cc
  gma/src/common/ump/consent_info_internal.h
  gma/src/include/firebase/gma/ump/types.h
  gma/src/ios/ump/consent_info_internal_ios.h
  gma/src/ios/ump/consent_info_internal_ios.mm
  gma/src/stub/ump/consent_info_internal_stub.cc
  gma/src/stub/ump/consent_info_internal_stub.h
  ios_pod/Podfile
  testing/test_framework/src/android/android_firebase_test_framework.cc
  testing/test_framework/src/desktop/desktop_firebase_test_framework.cc
  testing/test_framework/src/firebase_test_framework.h
  testing/test_framework/src/ios/ios_firebase_test_framework.mm
Labels: tests: succeeded

#1437 add UseEmulator api to auth
  auth/src/android/auth_android.cc
  auth/src/desktop/auth_desktop.cc
  auth/src/desktop/auth_desktop.h
  auth/src/desktop/rpcs/auth_request.cc
  auth/src/desktop/rpcs/auth_request.h
  auth/src/include/firebase/auth.h
  auth/src/ios/auth_ios.mm
Labels: skip-release-notes
