Repository firebase/firebase-cpp-sdk, pull requests merged in 2023-03, with the labels that each got.

#1215 Refactor the App Check internal call logic used by other products
  app_check/src/common/common.h
  app_check/src/desktop/app_check_desktop.cc
  app_check/src/desktop/app_check_desktop.h
  app_check/src/include/firebase/app_check.h
  storage/src/desktop/storage_reference_desktop.cc
Labels: skip-release-notes

#1220 Android AppCheck main implementation
  Android/firebase_dependencies.gradle
  app/CMakeLists.txt
  app/src/app_android.cc
  app_check/CMakeLists.txt
  app_check/app_check_resources/build.gradle
  app_check/build.gradle
  app_check/integration_test/build.gradle
  app_check/integration_test/src/integration_test.cc
  app_check/src/android/app_check_android.cc
  app_check/src/android/app_check_android.h
  app_check/src/android/common_android.cc
  app_check/src_java/com/google/firebase/appcheck/internal/cpp/JniAppCheckProvider.java
  app_check/src_java/com/google/firebase/appcheck/internal/cpp/JniAppCheckProviderFactory.java
  app_check/src_java/com/google/firebase/appcheck/internal/cpp/JniAppCheckToken.java
  settings.gradle
Labels: skip-release-notes

#1225 Add App Check support to desktop Functions
  app_check/integration_test/CMakeLists.txt
  app_check/integration_test/Podfile
  app_check/integration_test/build.gradle
  app_check/integration_test/functions/README.md
  app_check/integration_test/functions/firebase.json
  app_check/integration_test/functions/functions/index.js
  app_check/integration_test/functions/functions/package.json
  app_check/integration_test/src/integration_test.cc
  functions/src/desktop/callable_reference_desktop.cc
Labels: tests: succeeded, skip-release-notes

#1223 Make OAuth client_id optional in the google-services-desktop.json conversion script.
  generate_xml_from_google_services_json.py
Labels: tests: succeeded

#1217 Fix user-agent register timing in C++ and Unity SDK
  app/src/app_android.cc
  app/src/app_android.h
  app/src/app_common.cc
  app/src/app_common.h
  app/src/app_desktop.cc
  app/src/app_ios.mm
  app/src/app_stub.cc
  app/src/include/firebase/app.h
  app/src/util_android.h
  app/tests/app_test.cc
  firestore/src/main/firestore_main.cc
Labels: tests: succeeded, skip-release-notes

#1229 Implement AppCheck Android token-changed listeners
  app_check/integration_test/src/integration_test.cc
  app_check/src/android/app_check_android.cc
  app_check/src/android/app_check_android.h
  app_check/src_java/com/google/firebase/appcheck/internal/cpp/JniAppCheckListener.java
Labels: skip-release-notes

#1234 Disable SessionID test on Android
  analytics/integration_test/src/integration_test.cc
Labels: tests: succeeded, skip-release-notes

#1235 Check Google Play services version in Analytics test
  analytics/integration_test/src/integration_test.cc
  testing/test_framework/src/android/android_firebase_test_framework.cc
  testing/test_framework/src/android/java/com/google/firebase/example/TestHelper.java
  testing/test_framework/src/desktop/desktop_firebase_test_framework.cc
  testing/test_framework/src/firebase_test_framework.h
  testing/test_framework/src/ios/ios_firebase_test_framework.mm
Labels: tests: succeeded, skip-release-notes

#1238 Change GetGooglePlayServices to use reflection to avoid build errors
  analytics/integration_test/src/integration_test.cc
  testing/test_framework/src/android/java/com/google/firebase/example/TestHelper.java
  testing/test_framework/src/firebase_test_framework.h
Labels: tests: succeeded, skip-release-notes

#1228 Add App Check support for Firestore
  app/src/function_registry.h
  app_check/integration_test/CMakeLists.txt
  app_check/integration_test/Podfile
  app_check/integration_test/build.gradle
  app_check/integration_test/src/integration_test.cc
  app_check/src/desktop/app_check_desktop.cc
  app_check/src/desktop/app_check_desktop.h
  firestore/CMakeLists.txt
  firestore/integration_test_internal/src/util/integration_test_util.cc
  firestore/src/main/app_check_credentials_provider_desktop.cc
  firestore/src/main/app_check_credentials_provider_desktop.h
  firestore/src/main/create_app_check_credentials_provider.h
  firestore/src/main/create_app_check_credentials_provider_desktop.cc
  firestore/src/main/create_app_check_credentials_provider_ios.mm
  firestore/src/main/firestore_main.cc
  firestore/src/main/firestore_main.h
Labels: tests: succeeded, skip-release-notes

#1219 Add compile time warning for C++14 upgrade
  admob/src/include/firebase/admob.h
  analytics/src/include/firebase/analytics.h
  app/CMakeLists.txt
  app/src/include/firebase/app.h
  app/src/include/firebase/cpp_version_warning.h
  app_check/src/include/firebase/app_check.h
  auth/src/include/firebase/auth.h
  database/src/include/firebase/database.h
  dynamic_links/src/include/firebase/dynamic_links.h
  firestore/src/include/firebase/firestore.h
  functions/src/include/firebase/functions.h
  gma/src/include/firebase/gma.h
  installations/src/include/firebase/installations.h
  messaging/src/include/firebase/messaging.h
  performance/src/include/firebase/performance.h
  release_build_files/readme.md
  remote_config/src/include/firebase/remote_config.h
  storage/src/include/firebase/storage.h
  testlab/src/include/firebase/testlab.h
Labels: tests: succeeded

#1241 Don't dismiss stale approvals on users with write permission either.
  .github/workflows/checks_secure.yml
Labels: skip-release-notes

#1249 Update IOS FTL device model and os version
  scripts/gha/print_matrix_configuration.py
Labels: skip-release-notes
