Repository firebase/firebase-cpp-sdk, pull requests merged in 2023-09, with the labels that each got.

#1430 On Android, set dynamic code files to readonly
  app/src/util_android.cc
  app/src/util_android.h
  release_build_files/readme.md
Labels: tests: succeeded

#1444 Apply unused variables patch to Flatbuffers on Android as well.
  messaging/messaging_java/build.gradle
Labels: tests: succeeded, skip-release-notes

#1428 Add support for User Messaging Platform SDK on Android
  Android/firebase_dependencies.gradle
  gma/CMakeLists.txt
  gma/gma_resources/build.gradle
  gma/integration_test/build.gradle
  gma/integration_test/src/integration_test.cc
  gma/src/android/gma_android.cc
  gma/src/android/gma_android.h
  gma/src/android/ump/consent_info_internal_android.cc
  gma/src/android/ump/consent_info_internal_android.h
  gma/src/common/ump/consent_info.cc
  gma/src/common/ump/consent_info_internal.h
  gma/src/include/firebase/gma/ump/consent_info.h
  gma/src/ios/ump/consent_info_internal_ios.mm
  gma/src_java/com/google/firebase/gma/internal/cpp/ConsentInfoHelper.java
  messaging/messaging_java/build.gradle
  release_build_files/Android/firebase_dependencies.gradle
  testing/test_framework/src/android/android_firebase_test_framework.cc
  testing/test_framework/src/android/java/com/google/firebase/example/TestHelper.java
Labels: tests: succeeded

#1449 Fix iOS test version from deprecated 16.5 to 16.6.
  scripts/gha/print_matrix_configuration.py
Labels: tests: succeeded, skip-release-notes

#1452 Add a matrix label to FTL test runs, to make sorting them easier.
  .github/workflows/integration_tests.yml
Labels: tests: succeeded, skip-release-notes

#1439 Internal Updates
  gma/src/android/gma_android.cc
  gma/src/common/gma_common.cc
  gma/src/common/gma_common.h
  gma/src/common/native_ad.cc
  gma/src/common/native_ad_internal.cc
  gma/src/common/native_ad_internal.h
  gma/src/include/firebase/gma/internal/native_ad.h
  gma/src/ios/GADNativeAdCpp.h
  gma/src/ios/native_ad_internal_ios.mm
  gma/src_java/com/google/firebase/gma/internal/cpp/NativeAdHelper.java
Labels: skip-release-notes

#1454 Merge main into UMP feature branch 9/21
  .github/workflows/integration_tests.yml
  Android/firebase_dependencies.gradle
  analytics/integration_test/Podfile
  analytics/ios_headers/FIREventNames.h
  analytics/ios_headers/FIRParameterNames.h
  analytics/ios_headers/FIRUserPropertyNames.h
  app/app_resources/build.gradle
  app/google_api_resources/build.gradle
  app/integration_test/Podfile
  app/invites_resources/build.gradle
  app/src/util_android.cc
  app/src/util_android.h
  app_check/app_check_resources/build.gradle
  app_check/integration_test/Podfile
  auth/auth_resources/build.gradle
  auth/integration_test/Podfile
  cmake/external/firestore.cmake
  cpp_sdk_version.json
  database/database_resources/build.gradle
  database/integration_test/Podfile
  dynamic_links/integration_test/Podfile
  firestore/firestore_resources/build.gradle
  firestore/integration_test/Podfile
  firestore/integration_test_internal/Podfile
  functions/integration_test/Podfile
  gma/gma_resources/build.gradle
  gma/integration_test/Podfile
  installations/integration_test/Podfile
  ios_pod/Podfile
  ios_pod/swift_headers/FirebaseAnalyticsSwift-Swift.h
  ios_pod/swift_headers/FirebaseCoreInternal-Swift.h
  ios_pod/swift_headers/FirebaseDatabaseSwift-Swift.h
  ios_pod/swift_headers/FirebaseFirestoreSwift-Swift.h
  ios_pod/swift_headers/FirebaseFunctions-Swift.h
  ios_pod/swift_headers/FirebaseInAppMessagingSwift-Swift.h
  ios_pod/swift_headers/FirebaseMLModelDownloader-Swift.h
  ios_pod/swift_headers/FirebaseRemoteConfigSwift-Swift.h
  ios_pod/swift_headers/FirebaseSharedSwift-Swift.h
  ios_pod/swift_headers/FirebaseStorage-Swift.h
  ios_pod/swift_headers/SwiftProtobuf-Swift.h
  messaging/integration_test/Podfile
  messaging/messaging_java/build.gradle
  release_build_files/Android/firebase_dependencies.gradle
  release_build_files/readme.md
  remote_config/integration_test/Podfile
  remote_config/remote_config_resources/build.gradle
  scripts/gha/print_matrix_configuration.py
  storage/integration_test/Podfile
  storage/storage_resources/build.gradle
Labels: tests: succeeded
