Repository firebase/firebase-cpp-sdk, pull requests merged in 2023-07, with the labels that each got.

#1378 Update build_testapps script to log generated files.
  scripts/gha/build_testapps.py
Labels: tests: succeeded, skip-release-notes

#1372 Upgrade python calls to python3
  README.md
  analytics/integration_test/build.gradle
  app/integration_test/build.gradle
  app_check/integration_test/build.gradle
  auth/integration_test/build.gradle
  build_scripts/android/install_prereqs.sh
  build_scripts/ios/install_prereqs.sh
  build_scripts/tvos/install_prereqs.sh
  database/integration_test/build.gradle
  dynamic_links/integration_test/build.gradle
  firestore/integration_test/build.gradle
  firestore/integration_test_internal/build.gradle
  functions/integration_test/build.gradle
  gma/integration_test/build.gradle
  installations/integration_test/build.gradle
  messaging/integration_test/Podfile
  messaging/integration_test/build.gradle
  remote_config/integration_test/build.gradle
  scripts/gha/build_desktop.py
  scripts/gha/build_testapps.py
  scripts/gha/create_pull_request.py
  scripts/gha/desktop_tester.py
  scripts/gha/dismiss_reviews.py
  scripts/gha/gcs_uploader.py
  scripts/gha/inspect_built_libraries.py
  scripts/gha/install_test_workflow_prereqs.sh
  scripts/gha/it_workflow.py
  scripts/gha/lint_commenter.py
  scripts/gha/pr_file_commenter.py
  scripts/gha/print_matrix_configuration.py
  scripts/gha/read_ftl_test_result.py
  scripts/gha/report_build_status.py
  scripts/gha/restore_secrets.py
  scripts/gha/summarize_test_results.py
  scripts/gha/test_simulator.py
  scripts/gha/trigger_workflow.py
  scripts/gha/update_issue_comment.py
  storage/integration_test/build.gradle
Labels: tests: succeeded, skip-release-notes

#1380 On Ubuntu, GetTimezone should return the long time zone name.
  app/src/locale.cc
Labels: tests: in-progress, skip-release-notes

#1375 Fix for windows time zone name and other Unicode issues
  app/src/heartbeat/heartbeat_storage_desktop.cc
  app/src/locale.cc
  app/src/locale.h
  app/tests/locale_test.cc
  release_build_files/readme.md
  remote_config/src/desktop/file_manager.cc
Labels: tests: succeeded

#1385 Fix for gma android failing assert
  gma/integration_test/src/integration_test.cc
  gma/src/android/gma_android.cc
  gma/src/ios/native_ad_internal_ios.mm
Labels: skip-release-notes

#1383 Windows: Convert path from UTF-8 to UTF-16 before loading google-services.json
  app/src/app_desktop.cc
  app/tests/CMakeLists.txt
  app/tests/app_desktop_test.cc
  release_build_files/readme.md
Labels: tests: succeeded

#1387 Add a retry decorator to the GitHub log downloader.
  external/pip_requirements.txt
  scripts/gha/integration_testing/ftl_gha_validator.py
  scripts/gha/python_requirements.txt
Labels: tests: succeeded, skip-release-notes

#1386 iOS: Remove Analytics dependency from GMA integration test
  gma/integration_test/Podfile
  release_build_files/readme.md
Labels: tests: succeeded

#1394 Add script to merge main into all active feature branches on a regular schedule.
  .github/workflows/update-feature-branches.yml
Labels: skip-release-notes

#1402 Increase retry for GS log fetch.
  scripts/gha/integration_testing/ftl_gha_validator.py
Labels: tests: succeeded, skip-release-notes

#1403 Add Firestore test history report
  .github/workflows/build-report.yml
  scripts/gha/report_build_status.py
Labels: skip-release-notes

#1399 Revert "OR Query Implementation (#1335)"
  app/CMakeLists.txt
  firestore/CMakeLists.txt
  firestore/integration_test_internal/CMakeLists.txt
  firestore/integration_test_internal/integration_test.xcodeproj/project.pbxproj
  firestore/integration_test_internal/src/aggregate_count_test.cc
  firestore/integration_test_internal/src/aggregate_query_test.cc
  firestore/integration_test_internal/src/filter_test.cc
  firestore/src/android/filter_android.cc
  firestore/src/android/filter_android.h
  firestore/src/android/query_android.cc
  firestore/src/android/query_android.h
  firestore/src/common/filter.cc
  firestore/src/common/query.cc
  firestore/src/common/type_mapping.h
  firestore/src/include/firebase/firestore.h
  firestore/src/include/firebase/firestore/field_path.h
  firestore/src/include/firebase/firestore/filter.h
  firestore/src/include/firebase/firestore/query.h
  firestore/src/main/composite_filter_main.cc
  firestore/src/main/composite_filter_main.h
  firestore/src/main/converter_main.h
  firestore/src/main/filter_main.cc
  firestore/src/main/filter_main.h
  firestore/src/main/query_main.cc
  firestore/src/main/query_main.h
  firestore/src/main/unary_filter_main.cc
  firestore/src/main/unary_filter_main.h
  release_build_files/readme.md
Labels: tests: succeeded

#1406 Wrap the realtime RC test in flaky-block to automatically retry.
  remote_config/integration_test/src/integration_test.cc
Labels: tests: succeeded, skip-release-notes

#1408 Update the iOS version used by FTL
  scripts/gha/print_matrix_configuration.py
Labels: skip-release-notes
