Repository firebase/firebase-cpp-sdk, pull requests merged in 2023-10, with the labels that each got.

#1458 Merge main into UMP feature branch and update readme
  app/CMakeLists.txt
  firestore/CMakeLists.txt
  firestore/integration_test_internal/CMakeLists.txt
  firestore/integration_test_internal/integration_test.xcodeproj/project.pbxproj
  firestore/integration_test_internal/src/aggregate_count_test.cc
  firestore/integration_test_internal/src/aggregate_query_test.cc
  firestore/integration_test_internal/src/filter_test.cc
  firestore/src/android/filter_android.cc
  firestore/src/android/filter_android.h
  firestore/src/android/firestore_android.cc
  firestore/src/android/query_android.cc
  firestore/src/android/query_android.h
  firestore/src/common/filter.cc
  firestore/src/common/query.cc
  firestore/src/common/type_mapping.h
  firestore/src/include/firebase/firestore.h
  firestore/src/include/firebase/firestore/field_path.h
  firestore/src/include/firebase/firestore/filter.h
  firestore/src/include/firebase/firestore/query.h
  firestore/src/main/composite_filter_main.cc
  firestore/src/main/composite_filter_main.h
  firestore/src/main/converter_main.h
  firestore/src/main/filter_main.cc
  firestore/src/main/filter_main.h
  firestore/src/main/query_main.cc
  firestore/src/main/query_main.h
  firestore/src/main/unary_filter_main.cc
  firestore/src/main/unary_filter_main.h
  gma/src/android/gma_android.cc
  gma/src/common/gma_common.cc
  gma/src/common/gma_common.h
  gma/src/common/native_ad.cc
  gma/src/common/native_ad_internal.cc
  gma/src/common/native_ad_internal.h
  gma/src/include/firebase/gma/internal/native_ad.h
  gma/src/ios/GADNativeAdCpp.h
  gma/src/ios/native_ad_internal_ios.mm
  gma/src_java/com/google/firebase/gma/internal/cpp/NativeAdHelper.java
  release_build_files/readme.md
Labels: tests: succeeded

#1463 UMP iOS crash fix
  gma/integration_test/src/integration_test.cc
  gma/src/ios/ump/consent_info_internal_ios.h
  gma/src/ios/ump/consent_info_internal_ios.mm
Labels: tests: succeeded

#1461 Add User Messaging Platform C++ SDK
  Android/firebase_dependencies.gradle
  app/CMakeLists.txt
  gma/CMakeLists.txt
  gma/gma_resources/build.gradle
  gma/integration_test/AndroidManifest.xml
  gma/integration_test/Info.plist
  gma/integration_test/Podfile
  gma/integration_test/build.gradle
  gma/integration_test/integration_test.xcodeproj/project.pbxproj
  gma/integration_test/src/integration_test.cc
  gma/src/android/gma_android.cc
  gma/src/android/gma_android.h
  gma/src/android/ump/consent_info_internal_android.cc
  gma/src/android/ump/consent_info_internal_android.h
  gma/src/common/ump/consent_info.cc
  gma/src/common/ump/consent_info_internal.cc
  gma/src/common/ump/consent_info_internal.h
  gma/src/include/firebase/gma/ump.h
  gma/src/include/firebase/gma/ump/consent_info.h
  gma/src/include/firebase/gma/ump/types.h
  gma/src/ios/ump/consent_info_internal_ios.h
  gma/src/ios/ump/consent_info_internal_ios.mm
  gma/src/stub/ump/consent_info_internal_stub.cc
  gma/src/stub/ump/consent_info_internal_stub.h
  gma/src_java/com/google/firebase/gma/internal/cpp/ConsentInfoHelper.java
  ios_pod/Podfile
  release_build_files/Android/firebase_dependencies.gradle
  release_build_files/readme.md
  testing/test_framework/src/android/android_firebase_test_framework.cc
  testing/test_framework/src/android/java/com/google/firebase/example/TestHelper.java
  testing/test_framework/src/desktop/desktop_firebase_test_framework.cc
  testing/test_framework/src/firebase_test_framework.h
  testing/test_framework/src/ios/ios_firebase_test_framework.mm
Labels: tests: succeeded

#1472 Skip a UMP test that doesn't work on iOS simulator.
  gma/integration_test/src/integration_test.cc
Labels: skip-release-notes

#1468 Distribute FTL tests amongst different device models
  .github/workflows/integration_tests.yml
  scripts/gha/print_matrix_configuration.py
  scripts/gha/summarize_test_results.py
  scripts/gha/test_simulator.py
Labels: tests: succeeded, skip-release-notes

#1474 Remove validation tests on inequality restrictions
  firestore/integration_test_internal/src/validation_test.cc
Labels: tests: succeeded, skip-release-notes

#1477 Switch FTL Android tests to be triggered from Ubuntu.
  .github/workflows/integration_tests.yml
Labels: tests: succeeded

#1478 Retry nightly test failures
  .github/workflows/integration_tests.yml
  .github/workflows/retry-test-failures.yml
  scripts/gha/firebase_github.py
  scripts/gha/retry_test_failures.py
  scripts/gha/trigger_workflow.py
Labels: tests: succeeded, skip-release-notes

#1480 Add retry to LoadConsentForm for timeouts.
  gma/integration_test/src/integration_test.cc
Labels: tests: succeeded, skip-release-notes
