Repository firebase/firebase-cpp-sdk, pull requests merged in 2024-09, with the labels that each got.

#1639 Fix RemoteConfig info initialization issues
  release_build_files/readme.md
  remote_config/src/android/remote_config_android.cc
  remote_config/src/include/firebase/remote_config.h
  remote_config/src/ios/remote_config_ios.mm
Labels: tests: succeeded

#1642 Update upload-artifact actions
  .github/workflows/desktop.yml
Labels: tests: succeeded, skip-release-notes

#1641 Remove unnecessary swig logic from Analytics
  analytics/src/include/firebase/analytics.h
Labels: skip-release-notes

#1643 Revert "Bump actions/download-artifact from 3 to 4.1.7 (#1638)"
  .github/workflows/cpp-packaging.yml
  .github/workflows/integration_tests.yml
Labels: skip-release-notes

#1653 Update to Firebase Android BoM 33.3.0 while also including the Gradle 7 change.
  Android/firebase_dependencies.gradle
  app/app_resources/build.gradle
  app/google_api_resources/build.gradle
  app/invites_resources/build.gradle
  app_check/app_check_resources/build.gradle
  auth/auth_resources/build.gradle
  cpp_sdk_version.json
  database/database_resources/build.gradle
  firestore/firestore_resources/build.gradle
  gma/gma_resources/build.gradle
  messaging/messaging_java/build.gradle
  release_build_files/Android/firebase_dependencies.gradle
  release_build_files/readme.md
  remote_config/remote_config_resources/build.gradle
  storage/storage_resources/build.gradle
Labels: tests: succeeded
