Repository firebase/firebase-cpp-sdk, pull requests merged in 2024-01, with the labels that each got.

#1509 UMP: Fix TestUmpLoadFormUnavailableDueToAgeOfConsent flaky test.
  gma/integration_test/src/integration_test.cc
Labels: tests: succeeded, skip-release-notes

#1511 Firestore: Small Count API documentation improvements
  firestore/src/include/firebase/firestore/aggregate_source.h
  firestore/src/include/firebase/firestore/query.h
Labels: api: firestore, skip-release-notes

#1515 Add retry to SignInAnonymously to avoid network issues.
  auth/integration_test/src/integration_test.cc
Labels: tests: succeeded, skip-release-notes

#1512 Mark the Dynamic Links SDK as deprecated.
  dynamic_links/src/include/firebase/dynamic_links.h
  release_build_files/readme.md
Labels: tests: succeeded

#1513 Fix storage large download timeout.
  storage/integration_test/src/integration_test.cc
Labels: tests: succeeded, skip-release-notes

#1514 Add the ability to wait and retry futures based on multiple expected …
  testing/test_framework/src/firebase_test_framework.cc
  testing/test_framework/src/firebase_test_framework.h
Labels: tests: succeeded, skip-release-notes

#1517 UMP iOS: Add extra locks around async operations.
  gma/integration_test/src/integration_test.cc
  gma/src/ios/ump/consent_info_internal_ios.mm
Labels: tests: succeeded, skip-release-notes

#1516 Reference untrusted git branch names via environment variables.
  .github/workflows/checks.yml
  .github/workflows/integration_tests.yml
Labels: tests: succeeded, skip-release-notes

#1518 Clean up handling of GMA NoFill errors.
  gma/integration_test/src/integration_test.cc
Labels: tests: succeeded, skip-release-notes

#1523 Add explicit SDK version to messaging AAR.
  messaging/messaging_java/build.gradle
  release_build_files/readme.md
Labels: tests: succeeded

#1525 Pin OpenSSL version to 3.1.1 on Windows runners.
  scripts/gha/install_prereqs_desktop.py
Labels: tests: succeeded, skip-release-notes

#1521 Re-enable WrongInstance test with fixed logic and debug logs
  gma/integration_test/src/integration_test.cc
  gma/src/ios/ump/consent_info_internal_ios.mm
Labels: tests: succeeded, skip-release-notes

#1520 Fix a few flaky tests in several products (Auth, Analytics, Storage, RTDB, Firestore)
  .github/workflows/integration_tests.yml
  analytics/integration_test/src/integration_test.cc
  auth/integration_test/src/integration_test.cc
  database/integration_test/src/integration_test.cc
  storage/integration_test/src/integration_test.cc
Labels: tests: succeeded, skip-release-notes

#1527 Add retry to C++ packaging step.
  .github/workflows/cpp-packaging.yml
  scripts/gha/retry_test_failures.py
Labels: skip-release-notes

#1529 Move SetConsent test to the end to not break GetAnalyticsInstanceId tests.
  analytics/integration_test/src/integration_test.cc
Labels: tests: succeeded, skip-release-notes

#1531 Update messaging aar path for Unity in CMake
  messaging/CMakeLists.txt
Labels: skip-release-notes
